### ISSUE TITLE
Refactor `deploy_new_node.sls` orchestrate

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#1017]
Currently `deploy_new_node.sls` doesn't work as expected.

- We should configure salt-minion with salt-ssh only if the minion not already configured https://github.com/scality/metalk8s/pull/967#discussion_r276267290
- etcd is configured with the wrong IP https://github.com/scality/metalk8s/pull/967#discussion_r276267716

**Comment by NicolasT** [comment]
One more:

- [x] `control_plane_ip` can't ever be `localhost`, not a reasonable default
