### ISSUE TITLE
Fix multi-nodes env in CI

### ISSUE THREAD

**Issue by slaperche-scality** [scality/metalk8s#1038]
Currently the multi-nodes CI environment *does not* spawn extra nodes (just the bootstrap).
Consequently, we can't run cluster expansion test in the CI.

This is explained by a comment in `eve/workers/openstack-multiple-nodes/terraform/nodes.tf`:

```
  # FIXME: this syntax does not work (but will in v0.12)
  # see https://github.com/hashicorp/terraform/issues/17048
  # nodes = ["${openstack_compute_instance_v2.nodes.*.network.0.fixed_ip_v4}"]
```

So we either have to wait for the release of the v0.12, or find a workaround.

**Comment by gdemonet** [comment]
We _do_ spawn extra nodes, however we _do not_ populate the SSH config files with their IPs. The comment included describes how one could get the IP addresses from the `nodes` resource with Terraform 0.12 syntax.

**Comment by NicolasT** [comment]
Can't we migrate to 0.12.0-beta2 to get the required functionality? https://releases.hashicorp.com/terraform/0.12.0-beta2/

**Comment by gdemonet** [comment]
We can try, there are a few things we would need to vendor with it (the openstack "provider" most notably)
