### ISSUE TITLE
Node Management: We can not deploy a new node if a node is still not deployed correctly

### ISSUE THREAD

**Issue by carlito-scality** [scality/metalk8s#1042]
Actually, we can not deploy a new node if a node is still not deployed correctly or only registered.

Typical error:
```
nodes_|-ps.pkill_|-function": {"comment": "Running function ps.pkill failed on minions: node1 Function ps.pkill ran on node1, node2, bootstrap.", "name": "ps.pkill", "start_time": "20:40:43.204051", "result": false, "duration": 351.545, "__run_num__": 6, "__sls__": "metalk8s.orchestrate.deploy_new_node", "changes": {"ret": {"node1": false, "node2": null, "bootstrap": {"killed": [15417]}}, "out": "highstate"}
```

**Comment by NicolasT** [comment]
@carlito-scality Could you try the `bugfix/1042-allow-kcm-kill-to-fail` branch in your environment?

**Comment by MonPote** [comment]
@NicolasT I can try

**Comment by NicolasT** [comment]
@MonPote Ping?

**Comment by carlito-scality** [comment]
@NicolasT I just tested your branch ```bugfix/1042-allow-kcm-kill-to-fail``` but there is still the problem.
scenario: I create the node1 but do not deploy it. then I create the node2 and deploy it => 
![image](https://user-images.githubusercontent.com/47394132/57613452-3018cb00-7577-11e9-9d07-b001f0990c17.png)
