### ISSUE TITLE
Node Management: mine.update problem

### ISSUE THREAD

**Issue by carlito-scality** [scality/metalk8s#1044]
When we deploy a registerd node, we had the mine error (see attached error.txt
[error.txt](https://github.com/scality/metalk8s/files/3131001/error.txt)

A workaround is to launch ``` sudo salt-call mine.update ``` on the boostrap machine and then re-launch the deploy

**Comment by TeddyAndrieux** [comment]
It's more a deployment issue than a ui IMO.

For me this should be fixed by #896

**Comment by ramanduh** [comment]
This part of the code will be removed in this PR :https://github.com/scality/metalk8s/pull/1062 and we force mine refresh in this PR: https://github.com/scality/metalk8s/pull/1082/
I think we can close this issue
