### ISSUE TITLE
Adding NFS PV support

### ISSUE THREAD

**Issue by ssalaues** [scality/metalk8s#1052]
After a bare metal install on a hardware lab using CentOS 7.4 minimal, I realized that a MetalK8s install would not support the use of an NFS `PersistentVolume` out of the box due to needing the `nfs-utils` package. Is this something I could add as a new ansible role and open a PR for?

**Comment by ssalaues** [comment]
Actually found that there is a simple list of `preinstall` packages here: https://github.com/scality/metalk8s/blob/4e4ab1a6ea16bc5e6bc3f7bc4e4ed5798b34f985/vendor/kubespray/roles/kubernetes/preinstall/vars/centos.yml#L2

**Comment by ssalaues** [comment]
Ended up moving the package install to the `prepare_os` role
https://github.com/scality/metalk8s/blob/development/1.1/roles/prepare_os/tasks/main.yml

**Comment by NicolasT** [comment]
I guess this can now be closed, @ssalaues ?
