### ISSUE TITLE
Create and package a "hello world" Solution

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#1060]
In order to test our tooling for validating/deploying/upgrading Solutions, we would need a sample Solution.

To do so, we want to:

- [ ] create a dedicated repository (e.g. `scality/metalk8s-solution-example`)
- [ ] define and build a "random exporter" component, using sample code provided by Prometheus (from their "Getting started" guide), available [here](https://github.com/prometheus/client_golang/tree/master/examples/random)
- [ ] create an Operator with the [Operator SDK](https://github.com/operator-framework/operator-sdk)
- [ ] add a CRD to describe a "random exporter" deployment
- [ ] watch this resource in the Operator to deploy "random exporters" as a `Deployment`
- [ ] let the Operator set up `Service` and `ServiceMonitor` objects to monitor the "random exporters"
- [ ] build the complete Operator image and Operator manifests defined in #953 
- [ ] build an ISO following the Solution archive guidelines from #952 
- [ ] study usage of `kustomize`/`kubectl apply -k` for deploying Operators

Notes:

- Building of this example Solution should be simple (a single Makefile at the repo root should suffice)
- Testing the integration of this Solution with MetalK8s could be included in MetalK8s CI directly, as a way to validate our tooling
- Building a UI for this example Solution should be done in another issue

**Comment by sayf-eddine-scality** [comment]
Closing this for now, this is an acceptable alpha1 example but will need more polishing right after the second iteration of the solution management
