### ISSUE TITLE
Write a quickstart guide

### ISSUE THREAD

**Issue by slaperche-scality** [scality/metalk8s#1070]
In `docs/quickstart`, write documentation on:
- how to create a bootstrap node
- how to add a new node (move the examples from `examples` inside this doc and remove the `examples` top directory)
- how to access the GUI

**Comment by thomasdanan** [comment]
@slaperche-scality isn't it where we should explain how to install?

**Comment by slaperche-scality** [comment]
Yes.

Later we can move this part into the installation guide and refer it from here, but for now it can lives here indeed.

I'll update the description
