### ISSUE TITLE
have etcd cluster address in grain

### ISSUE THREAD

**Issue by ramanduh** [scality/metalk8s#1074]
In `salt/metalk8s/kubernetes/apiserver/installed.sls`, when we pass the argument `--etcd-servers` to the apiserver command, we use the grain `metalk8s.control_plane_ip`. We should create a grain for the etcd cluster address and update the arg properly

This may work now (and so does the old approach), but we'll need to change this at some point in time to point to the actual etcd cluster addresses. Could you file a tracking ticket?

_Originally posted by @NicolasT in https://github.com/scality/metalk8s/pull/1062/files_

**Comment by NicolasT** [comment]
That's not exactly what I meant with that comment.

There should be no *grain* for the *etcd* address. We know *etcd* is bound to the `control_plane_ip` of a node. What I meant is that in that place we should set the value of `etcd-endpoints` to the set of known/assumed `etcd` servers (based on their role), and for each, their `control_plane_ip` from the mine.

**Comment by TeddyAndrieux** [comment]
Nowadays we retrieve etcd members from etcd API and then add "local member" to this is, so it's done
