### ISSUE TITLE
Monitor Nodes with Prometheus

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#1077]
**Goal:**
Create a salt state to deploy Prometheus monitoring for Nodes, using node-exporter.

**Dependencies:**
- [x] #786
- [x] #997
- [x] #1008

**Details:**
In order to monitor Nodes, we need to deploy node-exporter with the following object (based on kube-prometheus manifests):

Daemonset: https://github.com/coreos/prometheus-operator/blob/v0.24.0/contrib/kube-prometheus/manifests/node-exporter-daemonset.yaml
ClusterRole: https://github.com/coreos/prometheus-operator/blob/v0.24.0/contrib/kube-prometheus/manifests/node-exporter-clusterRole.yaml
ClusterRoleBinding: https://github.com/coreos/prometheus-operator/blob/v0.24.0/contrib/kube-prometheus/manifests/node-exporter-clusterRoleBinding.yaml
Service: https://github.com/coreos/prometheus-operator/blob/v0.24.0/contrib/kube-prometheus/manifests/node-exporter-service.yaml
ServiceAccount: https://github.com/coreos/prometheus-operator/blob/v0.24.0/contrib/kube-prometheus/manifests/node-exporter-serviceAccount.yaml
ServiceMonitor: https://github.com/coreos/prometheus-operator/blob/v0.24.0/contrib/kube-prometheus/manifests/node-exporter-serviceMonitor.yaml

These manifests should maybe not be used as-is, but rather tuned to fit our needs.
Also, these manifests are those for the 0.24.0 version (the one compatible with development/2.0), they must be changed for development/2.1 & development/2.2 branches to use respectively 0.28.0 & 0.29.0 versions.

/!\ In MetalK8s-1.0, node-exporter is not deployed as a DaemonSet but rather directly installed on the host via a RPM.
This is done like that because of some limitation with volume propagation (new volumes not automatically seen by the node-exporter pod), we need to check if this problem is now fixed, otherwise we'll need to install the package instead of using a DaemonSet.

**Comment by slaperche-scality** [comment]
Done in #1168
