### ISSUE TITLE
Ship a debug/utilities container image

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#1093]
For operational use, it would be useful to have a container (image) available offline which contains tooling like `ping`, `telnet`, `curl`,...

**Comment by NicolasT** [comment]
Some other tools we may want to add:
- `netcat`
- `bind-util`
- `httpie`
- `openssl` (CLI tools)

**Comment by gdemonet** [comment]
For `netcat`, it seems we have either `nmap-ncat` or `socat` in RedHat repos... Which one should we pick?

**Comment by NicolasT** [comment]
> For `netcat`, it seems we have either `nmap-ncat` or `socat` in RedHat repos... Which one should we pick?

`socat`

**Comment by NicolasT** [comment]
Also, this may be a good container (heh) for `iperf`.
