### ISSUE TITLE
Handle networking MTUs

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#1095]
We currently hard-code the `veth` MTU to `1440` (the Calico self-hosted manifest default). However, this is a 'pessimistic' default, based on GCP deployment infrastructure.

Instead, since we don't enable IPIP by default, we should

- Ensure the MTU as configured in the CNI configuration file is equal to the MTU of the workload-plane interface on the node, I believe, and
- Set the MTU of the created IPIP tunnels to either a configurable value, or the MTU of the workload-plane interface minus the IPIP header size, i.e. 20 bytes

This would at least allow for 60bytes extra per packet on 'regular' ethernet networks, or 7560 bytes on networks configured with jumbo-frames.

**Comment by gdemonet** [comment]
For reference: https://docs.projectcalico.org/networking/mtu
