### ISSUE TITLE
Moonshot/non-moonshot and version tracking in project issues

### ISSUE THREAD

**Issue by jbertran** [scality/metalk8s#1097]
**Component**: Github
 
**Why this is needed**: The `moonshot` label is not descriptive enough for outside users as the `2.X` version marker for issues.

> We'll need to find something better than `moonshot` for labels to manage different versions (if people want to report bugs on MetalK8s 1, they/we could be surprised), maybe even asking for affected version(s) in the issue body. Probably not necessary for this PR though, but it needs to be tracked at least.

_Originally posted by @gdemonet in https://github.com/scality/metalk8s/pull/1063_

**What should be done**: Set up more granular and meaningful labels for versions of metal.

**Implementation proposal** (strongly recommended): Better labels.

**Test plan**: Meaningful labels to differentiate `1.X` and `2.X` for an unsuspecting Github visitor.

**Comment by thomasdanan** [comment]
won't do
