### ISSUE TITLE
Add real e2e test login

### ISSUE THREAD

**Issue by MonPote** [scality/metalk8s#1107]
**Component**:
Tests

**Why this is needed**:
We are only testing if the UI is up right now.
The login is the first "real" e2e test that can be done and it's  a good start to introduce e2e tests.

**What should be done**:

1. Find a way to get the certification of the API by Cypress (tricky)
2. Implement the Javascript test (easy)

**Implementation proposal** (strongly recommended):
The Javascript test is pretty straightforward : 
Put `data-cy` into the username input, password input and validation button.
Use the `data-cy` to fill the input and click on the button with cypress. It should redirect you to the correct page.

**Test plan**:
Run : 
```bash
WORKLOAD_IP=$(ip a show eth0 | grep -Po "inet \K[\d.]+")
UI_NODEPORT=$(sudo kubectl --kubeconfig=/etc/kubernetes/admin.conf get svc metalk8s-ui -n kube-system -o jsonpath='{.spec.ports[0].nodePort}')
./node_modules/cypress/bin/cypress run -s cypress/integration/login.js -e target_url="http://${WORKLOAD_IP}:${UI_NODEPORT}"
```
Cypress should type `admin`,`admin` as username and password, click on the button and redirect you the dashboard page.

**Comment by carlito-scality** [comment]
https://github.com/scality/metalk8s/issues/1014
