### ISSUE TITLE
TLS for SaltAPI

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#1115]
We currently deploy SaltAPI as a plain HTTP service. This should, however, be an HTTPS service to ensure secrecy of authentication, as well as data transmitted between Salt and the client.

It likely makes sense to use a certificate signed by the 'API server' root CA for this purpose.

**Comment by slaperche-scality** [comment]
So, to clarify a bit what we need here is:
- to have a new SLS in `salt/metalk8s/kubernetes/apiserver/certs/` to create a certs for salt-api
- update the `rest_cherrypy` section in the Salt master config file to use those certs
- update the code calling the Salt API to use HTTPS (storage-operator, UI also maybe?, …)

Did I miss something?

**Comment by TeddyAndrieux** [comment]
For me the SLS for certificate should be in `salt/metalk8s/salt/master/certs/` as it's a cert for salt-api

**Comment by NicolasT** [comment]
> to have a new SLS in salt/metalk8s/kubernetes/apiserver/certs/ to create a certs for salt-api

Not sure that's the right SLS, because `salt-api` is deployed elsewhere. It may also require us to create the K8s API server CA earlier (i.e., before we actually deploy K8s API server, because `salt-master` comes really early)

> update the code calling the Salt API to use HTTPS (storage-operator, UI also maybe?, …)

UI should use HTTPS but you could run into cert acceptance issues (still self-signed...). For the operator, yes indeed, and you can even let it validate the provided cert because we have the K8s API server root CA in `/var/run/kubernetes/....`.

**Comment by sayf-eddine-scality** [comment]
LGTM, As per saltstack docs check CherryPy version https://github.com/cherrypy/cherrypy/issues/1298 and that PyOpenSSL is insatlled

**Comment by slaperche-scality** [comment]
@NicolasT 

> For the operator, yes indeed, and you can even let it validate the provided cert because we have the K8s API server root CA in /var/run/kubernetes/....

Do I need to update the Operator deployment for that? Or it's already mounted/somehow available?

Also, what about running the operator outside of the cluster?
Do I need to document a new step (copy the ca.crt locally and give the path in a env variable)?

**Comment by NicolasT** [comment]
> @NicolasT
> 
> > For the operator, yes indeed, and you can even let it validate the provided cert because we have the K8s API server root CA in /var/run/kubernetes/....
> 
> Do I need to update the Operator deployment for that? Or it's already mounted/somehow available?

It's available as part of the `ServiceAccount` data: from https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/

> If available, a certificate bundle is placed into the filesystem tree of each container at /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, and should be used to verify the serving certificate of the API server.

Now, also see below...

> 
> Also, what about running the operator outside of the cluster?
> Do I need to document a new step (copy the ca.crt locally and give the path in a env variable)?

I'm not sure, but I expect you should be able to get the APIserver CA cert also from the kubeconfig, which you already use within the operator... So no need even to read `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`, or make a distinction between in-cluster and out-of-cluster, just get it from KubeConfig.

**Comment by slaperche-scality** [comment]
Question: this should target which branch?
I went for 2.4, but maybe we want it from 2.0?
(and maybe we should have a label or something to indicate which version is targeted by the issue…)
