### ISSUE TITLE
Link to external documentation for technical terms used in docs

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#1124]
**Component**: docs

**Why this is needed**:

The current docs use terms from the K8s world, which users are not required to know about.

**What should be done**:

Either link to K8s docs, or find other words that could be defined in our Glossary (see #1123)

**Comment by NicolasT** [comment]
I think we should do what was done in the MetalK8s 1.x docs: have the glossary define all terms where applicable (and use the relevant `:term:` ReST roles), and from there, if need be, link to external sources. I.e., external sources are always a 'second' step.

@lucieleonard may want to weigh in here...?
