### ISSUE TITLE
Freeze cypress version in cypress.sh

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#1129]
Currently, the queue is out of order because latest cypress version has been bumped to `3.3.0` which requires `gtk3` instead of `gtk2`.
We need to fix the version of cypress to 3.2.0 in `ui/cypress.sh`

**Comment by gdemonet** [comment]
Ahh, breaking minor upgrades.... :roll_eyes:

**Comment by slaperche-scality** [comment]
That's because they upgraded their version of Electron.

**Comment by alexandre-allard** [comment]
Fixed in #1130
