### ISSUE TITLE
Start unit testing custom Salt logic

### ISSUE THREAD

**Issue by jbertran** [scality/metalk8s#1136]
**Component**: salt

**Why this is needed**: 

We are beginning to have a very significant amount of custom code in salt states. In particular, the addition of a port of `kubectl drain` to the custom modules motivates this request, since it introduces complex logic that we __should__ test if we don't want to die in a fire due to stupid and preventable bugs.

**What should be done**:

Add unit testing for MetalK8s custom Salt logic for a simple custom module

**Implementation proposal** (strongly recommended):

https://docs.saltstack.com/en/master/topics/development/tests/unit.html
https://docs.saltstack.com/en/master/topics/tutorials/writing_tests.html

**Comment by TeddyAndrieux** [comment]
Make this ticket only for salt unit testing create a new ticket dedicated for linting (#2649) and python formatter (#2650)
