### ISSUE TITLE
Support Downgrade

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#1143]
**Component**:

'salt', 'upgrade'

**Why this is needed**:

Currently we can't downgrade a cluster because of a yum issue. Not able to downgrade a package that have dependencies on a specific version of another package only by giving the package we want to downgrade.

Small example about kubelet
If you want to downgrade kubelet you need to say to yum that you want to downgrade kubelet AND kubernetes-cni
`yum downgrade kubelet-1.12.6 kubernetes-cni`

You can do that using `pkgs` from `pkg.installed` state in salt BUT salt first check each element of the `pkgs` list before doing the `yum` command so you need to pass the exact version you want.

**What should be done**:

We need to get the exact version of the dependencies we want and give this to `pkgs` of `pkg.installed` salt states.

```
Install kubelet:
  pkg.installed:
    - pkgs:
      - kubelet: 1.12.6
      - kubernetes-cni: 0.6.0
```

**Implementation proposal** (strongly recommended):

So two choice: (TBD)
- generate at the build time a list of all packages with version that we will use in salt to get the version of the dependencies we need to give to `pkg.installed`
- create a custom state for install that will check dependencies dynamically and automatically give to the classic `pkgs` of `pkg.installed` the list of dependencies with the right version (a kind of workaround on yum "problem")

**Test plan**:

TBD

**Comment by Ebaneck** [comment]
> **Component**:
> 
> 'salt', 'upgrade'
> 
> **Why this is needed**:
> 
> Currently we can't downgrade a cluster because of a yum issue. Not able to downgrade a package that have dependencies on a specific version of another package only by giving the package we want to downgrade.
> 
> Small example about kubelet
> If you want to downgrade kubelet you need to say to yum that you want to downgrade kubelet AND kubernetes-cni
> `yum downgrade kubelet-1.12.6 kubernetes-cni`
> 

On a second thought @TeddyAndrieux  is it not possible that we can use `yum swap`??
- Allowing yum to intelligently resolve the new package dependencies and
- Allowing yum to also remove previous package and deps.

**yum swap kubelet-1.12.6 kubelet-1.11.7**

I think here, kubelet-1.12.6 and its deps will be removed while kubelet-1.11.7 and it's deps will be installed. no???

> You can do that using `pkgs` from `pkg.installed` state in salt BUT salt first check each element of the `pkgs` list before doing the `yum` command so you need to pass the exact version you want.
> 
> **What should be done**:
> 
> We need to get the exact version of the dependencies we want and give this to `pkgs` of `pkg.installed` salt states.
> 
> ```
> Install kubelet:
>   pkg.installed:
>     - pkgs:
>       - kubelet: 1.12.6
>       - kubernetes-cni: 0.6.0
> ```
> 
> **Implementation proposal** (strongly recommended):
> 
> So two choice: (TBD)
> 
>     * generate at the build time a list of all packages with version that we will use in salt to get the version of the dependencies we need to give to `pkg.installed`
> 
>     * create a custom state for install that will check dependencies dynamically and automatically give to the classic `pkgs` of `pkg.installed` the list of dependencies with the right version (a kind of workaround on yum "problem")
> 
> 
> **Test plan**:
> 
> TBD

**Comment by TeddyAndrieux** [comment]
> On a second thought @TeddyAndrieux is it not possible that we can use `yum swap`??
> 
> * Allowing yum to intelligently resolve the new package dependencies and
> * Allowing yum to also remove previous package and deps.
> 
> **yum swap kubelet-1.12.6 kubelet-1.11.7**
> 
> I think here, kubelet-1.12.6 and its deps will be removed while kubelet-1.11.7 and it's deps will be installed. no???
> 

Oh yes that should work indeed but I don't know if salt already have an option to do this.
But we can also create our custom module that will do that. 
Or we can also have 2 states 1 removing the package and just after one installing the new one. But don't really like this approach has if we can't install the new version we will end the state without any kubelet. And I don't know if swap handle this also ... Need to investigate but yes could be a good solution.
