### ISSUE TITLE
DNS test failed due to busybox version

### ISSUE THREAD

**Issue by ycointe** [scality/metalk8s#1146]
**Component**:
tests 

**What happened**:
dns tests failed when call local environment 

**What was expected**:
DNS test should ended succesfully

**Steps to reproduce**
`$ tox -e tests`

**Resolution proposal** (optional):
Bug with the latest busybox version
-> freeze the version to the v1.28

**Comment by NicolasT** [comment]
Any reason this hasn't triggered in CI?

**Comment by gdemonet** [comment]
Probably due to Docker cache

**Comment by jbertran** [comment]
Closed by #1147
