### ISSUE TITLE
eve/get_product_version.sh should only output numbers separated by a dot

### ISSUE THREAD

**Issue by bertranddemiddelaer** [scality/metalk8s#1166]
**Component**:

'build'

**What happened**:

artifacts are not processed by expiration and promotion, due to a version considered as invalid in the artifacts_name property

**What was expected**:

correct processing of artifacts expiration (ie good format of get_product_version.sh output)

**Steps to reproduce**

see builds listing, entries with a version suffix have not been expired.

**Resolution proposal** (optional):

fix all dev branches having the issue by removing the VERSION_SUFFIX of the output. If you want to use the current format of the suffixed version, please do not use get_product_version for that, as it is designed and used by the CI with its own requirements.

**Comment by bertranddemiddelaer** [comment]
the output must conform to this regexp '^[0-9]+(\.[0-9]+){1,3}$'

**Comment by gdemonet** [comment]
@bertranddemiddelaer Thanks for the bug report, we'll take care of it ASAP. Would you mind adding this information to Eve documentation so that others won't make the same mistake in the future? Should I open a ticket?

Currently, it only states:

> The file `get_product_version.sh` must [...] return a string representing the version of the product/repository on that branch.

**Comment by bertranddemiddelaer** [comment]
@gdemonet the doc update is already in the Eve PR ;)

**Comment by bertranddemiddelaer** [comment]
@gdemonet Please note that the next Eve deployment will check the output of get_product_version.sh and fail if it is considered as invalid
