### ISSUE TITLE
Tolerations missing on monitoring object

### ISSUE THREAD

**Issue by ycointe** [scality/metalk8s#1171]
**Component**: monitoring 

**What happened**: Monitoring pods did not start
All pods missing tolerations "node-role.kubernetes.io/bootstrap" and "node-role.kubernetes.io/infra"

**What was expected**: monitoring pods start

**Steps to reproduce**: kubectl get nodes -n monitoring

**Resolution proposal** (optional): add the tolerations

**Comment by jbertran** [comment]
Tackled by #1077  in c447c14
