### ISSUE TITLE
kubelet version missmatch

### ISSUE THREAD

**Issue by ycointe** [scality/metalk8s#1174]
**Component**: local repository

**What happened**: the kubelet version called missmatch with version in the repo

**What was expected**: install  kubelet v 1.12.6

**Steps to reproduce**
```
git checkout w/2.1/bugfix/fix-monitoring-tolerations
./doit.sh vagrant_up
```
**Resolution proposal** (optional):

**Comment by NicolasT** [comment]
Is this still an issue? If so, what was the cause?

**Comment by ycointe** [comment]
outdated due to the tests done (which was online so version not controled)
