### ISSUE TITLE
Remove compatibility band-aid in Secret handler

### ISSUE THREAD

**Issue by jbertran** [scality/metalk8s#1183]
**Component**: salt

**Why this is needed**:

Currently we vendor the monitoring components as upstreamed, autogenerated salt states using a custom renderer. Using this renderer to glue the manifests with the k8s salt module means that all secrets **should** be plain text to be used by the salt module (which doesn't necessarily make a lot of sense).

This means that we have a compatibility patch on the renderer for Secrets for the sole purpose of passing data for Secrets to the salt module.

**What should be done**:

Remove the need for this layer.

**Implementation proposal** (strongly recommended):

Ideally, this takes place during a refactor of the whole salt module.

**Test plan**:

No more secrets in plain text, isofunctional monitoring stack otherwise.

**Comment by gdemonet** [comment]
Fixed by #1972
