### ISSUE TITLE
Provide `clean` definition for local images

### ISSUE THREAD

**Issue by jbertran** [scality/metalk8s#1189]
**Component**: buildchain

**Why this is needed**:

Currently, we do not have a custom `clean` definition for local images, which would do `docker rmi`.

**What should be done**:

Use the Python API to clean images that were built.

**Implementation proposal** (strongly recommended):

Just do it!

**Test plan**:

We should now be able to:

1. Build a local image
2. Ask `doit` to clean that local image
3. Observe via `docker images` that the image was deleted from the local registry

**Comment by slaperche-scality** [comment]
@jbertran is this still relevant?

After you've implemented it, I think we said let's not do it (because it would negate the optimisation that was done for the UI image build)

**Comment by jbertran** [comment]
Ah I closed the PR that tackled this among other things. No longer relevant indeed.
