### ISSUE TITLE
Ensure etcd logs are ingested in Elasticsearch

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#119]
We must make sure `etcd` logs get ingested in Elasticsearch. This may be the case on servers part of the `k8s-cluster` group where `fluentd` already accesses `/var/log` from the host (to be validated!), but not when `etcd` is deployed on a separate set of servers, where Kubernetes *DaemonSet* containers are not scheduled.

**Comment by thomasdanan** [comment]
@gdemonet @NicolasT I guess this will be natively the case once we have integrated Loki: https://github.com/scality/metalk8s/issues/1992. closing it ...
