### ISSUE TITLE
Setting ssh key path when adding a node could be more intuitive

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#1204]
**Component**:

metalk8s-ui

**Why this is needed**:

It is easy to do mistakes when setting the ssh key path (when adding a node)

**What should be done**:

From what I understood, the path must always contain /etc/metalk8s/pki/ so may be this should be enforced so that user only choose the ssh key name (or even choose among available ssh key ?)

**Implementation proposal** (strongly recommended):

default value with the absolute path: /etc/metalk8s/pki/salt-bootstrap

**Test plan**:

**Comment by ycointe** [comment]
Would it be possible to add a question mark icon to the right of the field which will explain that is the path where is the id_rsa file on the bootstrap node ?

**Comment by thomasdanan** [comment]
@ycointe I think what you are suggesting is super important: we must have online help available in the UI ... I suggest you open an improvement issue to tackle this.
On this specific issue, I think the user should not even enter this path if this is the only path that can work ...
