### ISSUE TITLE
Node Management: Cypress tests

### ISSUE THREAD

**Issue by carlito-scality** [scality/metalk8s#1208]
**Component**: UI

**Why this is needed**:
Add cypress test to cover this feature
**What should be done**:
This ticket is mainly about defining a strategy for UI testing ... how we leverage what is already done on the backend side, how we make sure we are not running the same time consuming e2e test several times
**Implementation proposal** (strongly recommended):
**Test plan**:

**Comment by ChengYanJin** [comment]
We have already worked on Pragmatic Front-End Testing Strategy and will enrich the content. https://docs.google.com/document/d/183srtEL2JiMnBRO40S16Z3zJqToP9BjCFDG1zSXv4PI/edit#heading=h.52nvabd8svbt
