### ISSUE TITLE
hard coded path for bootstrap repository

### ISSUE THREAD

**Issue by xaf-scality** [scality/metalk8s#1216]
When running the bootstrap.sh script, the mount path of the iso is hard coded for repository.
This makes no sense as we don't know which version we currently have (mvp1 is 2.0 and the iso is metalk8s.iso ...)
I know that documentation is asking to create the mount path with the right version.
If we cannot find something more flexible then I suggest that bootstrap.sh should check its own path before running the installation.

**Comment by gdemonet** [comment]
Probably related to #924

**Comment by TeddyAndrieux** [comment]
Fixed by #924
