### ISSUE TITLE
Add more details about how to access the UIs

### ISSUE THREAD

**Issue by charlesprost** [scality/metalk8s#1220]
**Component**:

documentation

**Why this is needed**:

Because the current explanations about how to access the UIs are not so clear (both Platform UI and Grafana).

**What should be done**:

* Add a note about the Platform UI
* Change the explanation about Grafana

**Implementation proposal** (strongly recommended):

* About Platform UI:

 the Web browser accessing it must have direct access to both control plane and workload plane networks (not port forwarding can work because the UI harcodes the URL to the APIserver using the control plane IP); we could imagine some IPIP tunnels but because we are using NAT on VPN to access scality.cloud, that's very difficult to set up; a solution can be launching a VM with a Web browser in scality.cloud and link this VM to both networks

* About Grafana:

There is no need for the whole `kubectl` stuff; let's just build a SSH tunnel and it's working!

Run `kubectl --kubeconfig=/etc/kubernetes/admin.conf get service grafana -n monitoring`, get CLUSTER-IP and PORT.
Then build a SSH tunnel from your host such as: `ssh <ssh_user>@<bootstrap_ip> -L 0:<free_port_on_your_host>:<CLUSTER-IP>:<PORT>`.
Then open your local Web browser and go to: http://localhost:<free_port_on_your_host>

**Test plan**:

Test the new documentation.

**Comment by gdemonet** [comment]
> There is no need for the whole kubectl stuff; let's just build a SSH tunnel and it's working!

Mmh, that works indeed, but the `kubectl port-forward` is actually documented in [`kube-prometheus` README](https://github.com/coreos/kube-prometheus#access-the-dashboards).

In any case, the real solution for both of these issues is setting up Ingress rules for all those UIs and Services. Let's not spend too much time for workarounding the fact that we don't have an Ingress yet.

**Comment by charlesprost** [comment]
It's not about workarounding, it's how to work with the current version.
We should have a documentation that matches the current state of the product.

**Comment by gdemonet** [comment]
Yes and no - we're not released yet, Ingress is coming in a month or two, should we spend time documenting something that will become obsolete before the first official release? I agree that we should have _something_ documenting the current state as much as possible, but having the most accurate and efficient docs for each stage of development is going to slow the development cycle even more IMHO. Adding a warning in the docs mentioning that _"the host"_ must belong to both control- and workload-plane networks should be sufficient I believe.

**Comment by thomasdanan** [comment]
adding this one to Ingress Controller project so that we update the doc once ingress is in place

**Comment by gdemonet** [comment]
Old issue - Ingress controllers are in place, documentation for accessing UIs is in place as well: see [Installation/Accessing Cluster Services](https://metal-k8s.readthedocs.io/en/latest/installation/services.html)
