### ISSUE TITLE
UI: Improve Sexiness

### ISSUE THREAD

**Issue by carlito-scality** [scality/metalk8s#1231]
**Component**:UI

**Why this is needed**:
- Actually, some icons ("Cluster Monitoring, Nodes...") are not suitable and need to be customized.

**What should be done**:
- Design new SVG icons and integrate them
- https://github.com/scality/core-ui/issues/39 => done in https://github.com/scality/metalk8s/pull/1434
- https://github.com/scality/core-ui/issues/40 => done in https://github.com/scality/metalk8s/pull/1434
- https://github.com/scality/core-ui/issues/43

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by thomasdanan** [comment]
already addressed with Node/Volume page refactoring
