### ISSUE TITLE
Generate prometheus templates at build time

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#1244]
**Component**:

'salt', 'kubernetes', 'monitoring'

**Why this is needed**:

Currently we generate upstream manifests using a "hack" script on the prometheus-operator github repository https://github.com/coreos/prometheus-operator
And then edit manually the resulting manifest to add tolerations and changes nodeSelector

**What should be done**:

Create some build scripts to generate this manifest file automatically at build time.

**Implementation proposal** (strongly recommended):

Changes from this PR https://github.com/scality/metalk8s/pull/1159 needed

**Comment by NicolasT** [comment]
This relates to #1565

**Comment by NicolasT** [comment]
Should, given #1565, now be fixed if we ever implement #1449

**Comment by TeddyAndrieux** [comment]
It's no longer true, nowadays we have a render script (that only need to be included in the buildchain as Nicolas mention in a previous comment)
