### ISSUE TITLE
UI - ClusterHealth Improvement

### ISSUE THREAD

**Issue by carlito-scality** [scality/metalk8s#1269]
**Component**:UI

**Why this is needed**:
- Missing detailed information for advanced users P2
- Missing refresh P1
- Texts should be aligned
![image](https://user-images.githubusercontent.com/47394132/60191884-5186fb00-9835-11e9-95b0-acf96074def3.png)

**What should be done**:
- Add more details about Everything is up and running" => need design
- Refresh the page automatically to display the lastest status

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by MonPote** [comment]
Split this issue on 2 differents issues. #1340 #1341
