### ISSUE TITLE
Install python from salt-ssh

### ISSUE THREAD

**Issue by ycointe** [scality/metalk8s#1278]
Component: Workload plane node

Why this is needed:

    Python is an essential component required for node deployment

What should be done:

    Find a way to install python from the salt-ssh

Implementation proposal (strongly recommended):

Test plan:

**Comment by jbertran** [comment]
As a first step, might we specify Python as a prerequisite on the node instead? 

It's not a stretch to expect it to be present on the machine pre-"bootstrap", and we can document its necessity _for Ubuntu only_ until we get to installing it as part of the initial commands. Additionally, that step may not be worth your time as much as working out a clean way to integrate debian stuff in the buildchain.

Besides, from what we've seen we *need* Python on the node for the salt-ssh stuff to run correctly.

**Comment by sayf-eddine-scality** [comment]
Agreeing with @jbertran , without python salt-ssh itself is super limited (no execution modules, no salt states !) so better go with requiring python as a prerequisites in the nodes

**Comment by ycointe** [comment]
All right, then I close this issue for the moment.
