### ISSUE TITLE
Design Node Dashboard

### ISSUE THREAD

**Issue by MonPote** [scality/metalk8s#1284]
**Component**: grafana

**Why this is needed**:
As a customer/TS I would like to monitor the nodes state.

**What should be done**:
Add a design document in the folder `/docs/developer/architecture/monitoring/grafana`
The design document should contain at least : 
- the list of graphs
- prometheus queries

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by thomasdanan** [comment]
@MonPote @sayf-eddine-scality the idea would be to reuse the node details dashboard we have in MetalK8S 1.X, no new dashboard to develop ...

**Comment by MonPote** [comment]
> @MonPote @sayf-eddine-scality the idea would be to reuse the node details dashboard we have in MetalK8S 1.X, no new dashboard to develop ...

Ok then, I will close this issue.
