### ISSUE TITLE
Add node Dashboard

### ISSUE THREAD

**Issue by MonPote** [scality/metalk8s#1285]
**Component**: grafana

**Why this is needed**:
Implementation followed the design document from #1284 

**What should be done**:
Add the json as ConfigMap :
`metalk8s/salt/metalk8s/addons/monitoring/grafana/deployed.sls`

**Implementation proposal** (strongly recommended):
Copy-Paste from MetalK8S 1.X

**Test plan**:

**Comment by NicolasT** [comment]
We have existing Node dashboard(s), no?
