### ISSUE TITLE
Check kube-apiserver healthz before uncordon node

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#1297]
**Component**:

'salt', 'kubernetes'

**What happened**:

When we call `deploy_node` in the highstate if we update apiserver then the apiserver is not ready when we try to uncordon the node so we get a traceback

```
__id__:
    Uncordon the node
__run_num__:
    5
__sls__:
    metalk8s.orchestrate.deploy_node
changes:
    ----------
comment:
    An exception occurred in this state: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 1919, in call
        **cdata['kwargs'])
      File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1918, in wrapper
        return f(*args, **kwargs)
      File "/var/cache/salt/master/extmods/states/metalk8s_cordon.py", line 73, in node_uncordoned
        return _node_set_unschedulable(name, False, **kwargs)
      File "/var/cache/salt/master/extmods/states/metalk8s_cordon.py", line 18, in _node_set_unschedulable
        'metalk8s_kubernetes.node_unschedulable'](name, **kwargs)
      File "/var/cache/salt/master/extmods/modules/metalk8s_kubernetes.py", line 2368, in node_unschedulable
        match = node(node_name, **kwargs)
      File "/var/cache/salt/master/extmods/modules/metalk8s_kubernetes.py", line 331, in node
        raise CommandExecutionError(exc)
    CommandExecutionError: HTTPSConnectionPool(host='10.100.3.220', port=6443): Max retries exceeded with url: /api/v1/nodes (Caused by ProtocolError('Connection aborted.', error(111, 'Connection refused')))
```

**What was expected**:

Working `deploy_node` state when changing the apiserver.

**Steps to reproduce**

Change the apiserver manifest try to run the orchestrate `metalk8s.orchestrate.deploy_node` on this node.

**Resolution proposal** (optional):

Add a check just after the highstate to check the healthz of apiserver

**Comment by Ebaneck** [comment]
This looks to me like a special scenario where we are modifying the manifest file for Kube-apiserver then trying to uncordon a node almost at the same time. no??

I expected Kubelet to notice the differences in the updated manifest file and to respawn the pod in no time.
Of course, this renders Kube-apiserver unavailable for a **very very short period** of time. no??

@TeddyAndrieux it would be nice to confirm that the  Kube-apiserver pod still runs??

Also, can you share some of the changes you made to manifest file that caused this issue?

Was this complete over-write of the manifest file??

**Comment by TeddyAndrieux** [comment]
> This looks to me like a special scenario where we are modifying the manifest file for Kube-apiserver then trying to uncordon a node almost at the same time. no??
> 

No because in `salt/metalk8s/orchestrate/deploy_node.sls` we execute the highstate that will potentially edit the apiserver manifest so restart the pod and just after the highstate we uncordon the node.

> I expected Kubelet to notice the differences in the updated manifest file and to respawn the pod in no time.
> Of course, this renders Kube-apiserver unavailable for a **very very short period** of time. no??

Yes should, but when I tested it that was not the case, the pod is running yes but apiserver still not ready. In the state that install apiserver we check that the pod is running but that's all. Kube-apiserver service may take time to start in the pod

> @TeddyAndrieux it would be nice to confirm that the Kube-apiserver pod still runs??

In `salt/metalk8s/orchestrate/bootstrap/init.sls` we already have a state checking the status of apiserver. 
```
Wait for API server to be available:
  http.wait_for_successful_query:
  - name: https://{{ pillar.metalk8s.api_server.host }}:6443/healthz
  - match: 'ok'
  - status: 200
  - verify_ssl: false
```
We should just do the same in deploy_node btw IMO

> Also, can you share some of the changes you made to manifest file that caused this issue?
> 
> Was this complete over-write of the manifest file??

For me that were in a case of upgrade but for testing... I'm not able to reproduce for the moment ...

Maybe this come from elsewhere but IMO it's still good to have it anyway

**Comment by Ebaneck** [comment]
> > This looks to me like a special scenario where we are modifying the manifest file for Kube-apiserver then trying to uncordon a node almost at the same time. no??
> 
> No because in `salt/metalk8s/orchestrate/deploy_node.sls` we execute the highstate that will potentially edit the apiserver manifest so restart the pod and just after the highstate we uncordon the node.
> 
Should we not instead be introducing a wait signal(e.g 5s) or delay after the highstate?? 

It looks to me like adding healthcheck after the highstate will just confirm that Kube-apiserver is alive but no ready and consequently the same outcome.
> > I expected Kubelet to notice the differences in the updated manifest file and to respawn the pod in no time.
> > Of course, this renders Kube-apiserver unavailable for a **very very short period** of time. no??
> 
> Yes should, but when I tested it that was not the case, the pod is running yes but apiserver still not ready. In the state that install apiserver we check that the pod is running but that's all. Kube-apiserver service may take time to start in the pod
> 
> > @TeddyAndrieux it would be nice to confirm that the Kube-apiserver pod still runs??
> 
> In `salt/metalk8s/orchestrate/bootstrap/init.sls` we already have a state checking the status of apiserver.
> 
> ```
> Wait for API server to be available:
>   http.wait_for_successful_query:
>   - name: https://{{ pillar.metalk8s.api_server.host }}:6443/healthz
>   - match: 'ok'
>   - status: 200
>   - verify_ssl: false
> ```
> 
> We should just do the same in deploy_node btw IMO
> 
> > Also, can you share some of the changes you made to manifest file that caused this issue?
> > Was this complete over-write of the manifest file??
> 
> For me that were in a case of upgrade but for testing... I'm not able to reproduce for the moment ...
> 
> Maybe this come from elsewhere but IMO it's still good to have it anyway

**Comment by TeddyAndrieux** [comment]
> Should we not instead be introducing a wait signal(e.g 5s) or delay after the highstate??
> 
> It looks to me like adding healthcheck after the highstate will just confirm that Kube-apiserver is alive but no ready and consequently the same outcome.
> 

No because here we check the `healthz` with htto when in the kube-apiserver state we only check that the pod is running.
A wait signal is not really good because we don't know how many time we need to wait and maybe sometimes we will wait for nothing. For me just checking the healthz it's enough
