### ISSUE TITLE
Documentation about `products` in bootstrap.yaml

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#1332]
**Component**:

'docs'

**Why this is needed**:

Currently we don't give strict instruction about what is needed in `products:metalk8s` in `bootstrap.yaml`

**What should be done**:

In `products:metalk8s` we can either put path to a directory where the iso is already mounted/extracted or a path to an iso. 
We should only describe one approach in the documentation.

2 options (IMO):

1. Path to a directory: describe how mount the iso and configure the fstab manually and then launch the bootstrap.sh
2. Path to the iso: mount the iso anywhere and just launch the bootstrap.sh (iso will be automatically mounted in the right directory and fstab configured automatically

**Implementation proposal** (strongly recommended):

Suggest solution 2. just above

**Comment by sayf-eddine-scality** [comment]
rename `products` into more meaningful name

**Comment by charlesprost** [comment]
As discussed, we could use `archives` instead of `products` and use a plain list instead of having the `:metalk8s` sub tree

**Comment by charlesprost** [comment]
Should be available starting from 2.0 also
