### ISSUE TITLE
UI - Improvement of ApiClient 

### ISSUE THREAD

**Issue by MonPote** [scality/metalk8s#1338]
**Component**: ui

**Why this is needed**:

Because it's something easy to improve.

**What should be done**:
Factorize some code in ApiClient

**Implementation proposal** (strongly recommended):

```javascript
async send(request) {
    const {
        method = 'get',
        endpoint,
        payload = {},
        headers = {},
        params
    } = request;

    try {
        const response = await axios({
        method,
        headers: { ...this.headers, ...headers },
        params,
        url: endpoint,
        data: payload,
        ...this.settings
        });
        return response.data;
    } catch (error) {
        return { error };
    }
  }
```
  get = (...request) => send({ ...request, method: 'get' })

**Test plan**:

**Comment by carlito-scality** [comment]
I just tried some solutions but nothing turns out to be better. Just keep it as it is for now.
