### ISSUE TITLE
documentation: No clear link to ISO in Bootstrap instructions

### ISSUE THREAD

**Issue by wabernat** [scality/metalk8s#1358]
**docs**:

In quickstart/bootstrap.html, I am thus instructed: 
"On your bootstrap node, download the MetalK8s ISO file. Mount this ISO file at the specific following path:"

I cannot find a MetalK8s ISO file in the code. Online searches of the RTD documentation expose references to "How to Build an ISO," involving "doit.sh", which I also cannot find. Searches with find and grep in the source are also unproductive. 

I expect to be provided with clear links to access essential files. 

To reproduce, use the documentation as an end user who does not know where to find things. Feel the love. 

Resolution proposal: Include a link to the ISO file on the "download the MetalK8s ISO file" text.

**Comment by NicolasT** [comment]
We do not and will not provide pre-built ISOs as part of the MetalK8s open-source project. However, indeed, given such ISO is a prerequisite for installation, we may want to re-organize the documentation, and/or provide proper links to the build instructions where applicable.

**Comment by JavierAbrego** [comment]
I agree with @wabernatScality, I just run through the documentation, and spend some time looking for the download link

**Comment by NicolasT** [comment]
@JavierAbrego As mentioned above, there is no download link. If you want to deploy MetalK8s 2.x, it's up to you (or your vendor) to build the artifact, validate it (if desired), etc. How to build this ISO is described in https://metal-k8s.readthedocs.io/en/latest/developer/building/requirements.html#mandatory and https://metal-k8s.readthedocs.io/en/latest/developer/building/building.html

Granted, this documentation could be improved.
