### ISSUE TITLE
Improvement of ClusterStatus design

### ISSUE THREAD

**Issue by MonPote** [scality/metalk8s#1367]
**Component**: ui

**Why this is needed**:
This design may be better for the ClusterStatus, so let's discuss if we want to implement it.
https://github.com/scality/metalk8s/pull/1364#issuecomment-508529549

**What should be done**:
[] - Discuss of wether or not we should change it that way.
[] - Do the actual implementation

**Comment by thomasdanan** [comment]
Once we have the Overview page, the alert page will only contain alerts. That information will be available when looking at current alert on core service and monitoring service entities
