### ISSUE TITLE
Build offline

### ISSUE THREAD

**Issue by ycointe** [scality/metalk8s#1392]
**Component**: build

**Why this is needed**: Metalk8s installation offline

**What should be done**: 

**Implementation proposal** (strongly recommended):

**Test plan**:
Realize the metalk8s deployment/extension offline

**Comment by NicolasT** [comment]
Why is this a question?

**Comment by ycointe** [comment]
It's only because I haven't a real good view of what is should be done for this issue.

**Comment by gdemonet** [comment]
Outdated, not relevant to the current state of the project, and not much details, so closing this issue.
