### ISSUE TITLE
Override some defined values

### ISSUE THREAD

**Issue by xaf-scality** [scality/metalk8s#1404]
Some defined values need to be change at deployment stage, by example the storage needed for es-data pod, # of ES-data pod or the memory limit of fluent-bit ...

We can trick it of course by editing those values directly in files but this will not be keep on the next upgrade.
What is the best "production" way to do this ?

**Comment by NicolasT** [comment]
In MetalK8s 1.1, you can override these from your inventory / vars, see https://metal-k8s.readthedocs.io/en/1.1.0/operations-guide/advanced_configuration.html. These are based on the Helm chart 'values'.

Would this suit your needs?

**Comment by thomasdanan** [comment]
won't do
