### ISSUE TITLE
Improve the volume list for each node

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#1428]
**Component**: ui

**Why this is needed**:
We want to see the size of the volume. Since this involves more work, we will do it later at different milestones following #1423.

**What should be done**:
Add a new column to display the size of the volume.

**Implementation proposal** (strongly recommended):
We display the volume size for sparseLoopDevice. For the rawBlockDevice, we would have to fetch the PersistentVolume linked to the Volume.

**Test plan**:
We should update the E2E test to check the size column.

**Comment by slaperche-scality** [comment]
#1454 is merged
