### ISSUE TITLE
Reduce code duplication in our shell scripts

### ISSUE THREAD

**Issue by slaperche-scality** [scality/metalk8s#1441]
**Component**:

deployment

**Why this is needed**:

In order to our scripts to be consistent, we have copied/duplicated a lot of functions from one script to another.
It's a maintenance burden because they will likely starts to diverge at one point, and fixing a bug in one of these common feature require to patch N scripts.

**What should be done**:

Factor out the common functions into a "shell library" (`common.sh`, `utils.sh`, whatever…) that will be used by our Shell scripts.

**Test plan**:

The observable behavior should be unchanged.

**Comment by NicolasT** [comment]
Alternative title: reduce the usage of shell-scripts ;-)

**Comment by alexandre-allard** [comment]
Closing this as it's already done in #2036
