### ISSUE TITLE
We should notice the user when the ptf doesn't have any storage classes.

### ISSUE THREAD

**Issue by MonPote** [scality/metalk8s#1457]
**Component**: ui

**Why this is needed**:
When a user does not have any Storage Class he is stuck at the creation of volume without any hint to solve the issues.

**What should be done**:
We should told him, he does not have any storage class and he should create one.
However this message should be display only when we are sure he does not have any.
We don't want this message to be display when the app is fetching storage class for example.

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by gdemonet** [comment]
Maybe we should explain with a helptip that StorageClasses have to be created by the user, but there will always be existing StorageClasses available (we'll deploy some with the cluster addons, such as `metalk8s-monitoring` for instance). I doubt a warning can be implemented for this, and if it can, I doubt it's the good strategy.

**Comment by NicolasT** [comment]
How about adding functionality in the UI to *create* a new SC at that point
(or, more generally, list and edit/create them), including setting FS
formatting annotations that are specific to our operator, similar to the
MetalK8s-specific Node annotations we have?

**Comment by slaperche-scality** [comment]
In the long/medium term, yes it would be nice to have the ability to create SC from the UI.

The current issue we have is "No StorageClass == blank page with no warning/error (even in devtool console) when clicking on `Create a new Volume`".

We should at least "do something" here to avoid that (bare minimum would be a warning in the devtool console.)

**Comment by gdemonet** [comment]
> We should at least "do something" here to avoid that (bare minimum would be a warning in the devtool console.)

Browser console errors are not for users, but for developers, so I don't think it's enough.

> The current issue we have is "No StorageClass == blank page with no warning/error (even in devtool console) when clicking on Create a new Volume".

That's a real issue. The form should actually prevent you from clicking "Create" if the SC field is empty (since it's mandatory). To help users while not implementing the SC mgmt from the UI, one could add a helptip explaining that SCs need to be created by users before they can use them in Volumes.
