### ISSUE TITLE
Make Salt API client more robust when parsing JSON

### ISSUE THREAD

**Issue by slaperche-scality** [scality/metalk8s#1461]
**Component**:

operator

**Why this is needed**:

The current  JSON parsing logic is not very robust, e.g.:

```go
return result["return"].([]interface{})[0].(map[string]interface{}), nil
```

If the document doesn't have the expected structure, we will panic, which is bad…
We should be more robust and simply return an error instead of crashing.

**What should be done**:

Rewrite the parsing logic by using safe "operations" (i.e. ones that returns `false` instead of crashing when they fail).

**Implementation proposal** (strongly recommended):

Ideally we should unmarshall the JSON into a structure, but I'm not sure it's possible in our case.

What we can do though is:
- use two-value assignment for map lookup
- check the length of the array before accessing it
- use two-value assignment for type assertion

**Test plan**:

Add unit tests with valid JSON that have an invalid structure (missing `return` key, empty list, …)

**Comment by ftalbart** [comment]
Hi,

I got an issue related to this ticket. 2 comments:
- we should have a proper error handling with a clear error message
- if the error can be easily handled by trying again the operation, it would be nice to implement such mechanism.

Here is my traceback:

> {"level":"info","ts":1588684676.7975533,"logger":"salt-api","msg":"Auth","Salt.Address":"https://salt-master:4507","username":"storage-operator","type":"Bearer"}
> {"level":"info","ts":1588684676.8895946,"logger":"salt-api","msg":"POST","Salt.Address":"https://salt-master:4507","url":"https://salt-master:4507/login","StatusCode":200,"duration":92}
> E0505 13:17:56.950094       1 reflector.go:134] pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/tools/cache/reflector.go:95: Failed to list *unstructured.Unstructured: the server could not find the requested resource
> {"level":"info","ts":1588684676.9564252,"logger":"salt-api","msg":"POST","Salt.Address":"https://salt-master:4507","url":"https://salt-master:4507/","StatusCode":200,"duration":66}
> {"level":"info","ts":1588684676.9565904,"logger":"volume-controller","msg":"reconciling volume: STOP","Request.Name":"hd3-data1"}
> E0505 13:17:56.957058       1 runtime.go:69] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x13873a0), concrete:(*runtime._type)(nil), asserted:(*runtime._type)(0x1340120), missingMethod:""} (interface conversion: interface {} is nil, not string)
> /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/runtime/runtime.go:76
> /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/runtime/runtime.go:65
> /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/runtime/runtime.go:51
> /usr/local/go/src/runtime/panic.go:679
> /usr/local/go/src/runtime/iface.go:255
> /storage-operator/pkg/salt/client.go:104
> /storage-operator/pkg/controller/volume/volume_controller.go:656
> /storage-operator/pkg/controller/volume/volume_controller.go:620
> /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:215
> /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:158
> /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:133
> /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:134
> /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:88
> /usr/local/go/src/runtime/asm_amd64.s:1357
> panic: interface conversion: interface {} is nil, not string [recovered]
> 	panic: interface conversion: interface {} is nil, not string
> 
> goroutine 419 [running]:
> k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
> 	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/runtime/runtime.go:58 +0x105
> panic(0x13c5c40, 0xc0009c2fc0)
> 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
> github.com/scality/metalk8s/storage-operator/pkg/salt.(*Client).PrepareVolume(0xc0003d0100, 0x178b0a0, 0xc0008d7600, 0xc00057b008, 0x8, 0xc000ba0920, 0x9, 0xc0008f22e0, 0xe, 0xc00045fab8, ...)
> 	/storage-operator/pkg/salt/client.go:104 +0x83b
> github.com/scality/metalk8s/storage-operator/pkg/controller/volume.(*ReconcileVolume).deployVolume(0xc000228330, 0x178b0a0, 0xc0008d7600, 0xc0004ddc00, 0xc0008f22e0, 0xe, 0x0, 0x0, 0x0, 0x0)
> 	/storage-operator/pkg/controller/volume/volume_controller.go:656 +0x3ad
> github.com/scality/metalk8s/storage-operator/pkg/controller/volume.(*ReconcileVolume).Reconcile(0xc000228330, 0x0, 0x0, 0xc00057afd4, 0x9, 0x0, 0x0, 0x0, 0x0)
> 	/storage-operator/pkg/controller/volume/volume_controller.go:620 +0xa04
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000bd680, 0x44bf00)
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:215 +0x20a
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:158 +0x36
> k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000445a60)
> 	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:133 +0x5e
> k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000445a60, 0x3b9aca00, 0x0, 0x1, 0xc0005bc0c0)
> 	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:134 +0xf8
> k8s.io/apimachinery/pkg/util/wait.Until(0xc000445a60, 0x3b9aca00, 0xc0005bc0c0)
> 	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:88 +0x4d
> created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:157 +0x32e
