### ISSUE TITLE
Unprepare volume with Salt

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#1475]
**Component**: salt, storage

**Dependencies**:
- [x] #1473 
- [x] #1474

**Why this is needed**: To be able to remove device previously created with Salt

**What should be done**: Create a salt formula which will do the reverse of #1474

**Implementation proposal** (strongly recommended):

**Test plan**: We need to be able to completely "unprepare" a volume.

**Comment by NicolasT** [comment]
For reference: while #1474 is about a *state* that can be invoked for something to exist (idempotently), this is about an *action* that can be invoked for something to not-exist (kinda idempotently, but only to be invoked in known, well-defined cases).

**Comment by NicolasT** [comment]
(That action can be a state, of course, my bad)

**Comment by slaperche-scality** [comment]
What does it means to "unprepare" in this case?
- `losetup --detach` and `rm the/sparse/file` for `sparseLoopDevice`?
- `wipefs` (through the Salt module `disk.wipe`) on the device for `rawBlockDevice`?

**Comment by NicolasT** [comment]
Something like that, yes.

Although we may want to check whether we actually want to 'unprepare' behind the users' back... Any opinion @xaf-scality ?

**Comment by NicolasT** [comment]
Checked with @xaf-scality in-person.

For `rawBlockDevice`, `unprepare` should basically do nothing. Let's keep the FS around (such that if someone deletes a `Volume` by mistake, data can still be recovered).
For `sparseLoopDevice`, because this accumulates on `/var/lib/metalk8s/...`, let's remove the backing sparse file upon deletion. This is for test/dev/demo purposes only anyway.

**Comment by NicolasT** [comment]
Over time, we could add a `reclaimPolicy` similar to how it exists on a `PersistentVolume` which could then be `Retain` (don't delete anything), `Delete` (`wipefs`/remove sparse file/...), or whatnot. Given some sensible default (`Retain`, most likely), we could allow a user to choose what must happen.
