### ISSUE TITLE
Update Prometheus deployment to use a PVC

### ISSUE THREAD

**Issue by slaperche-scality** [scality/metalk8s#1515]
**Component**:

salt, monitoring, tests, documentation

**Why this is needed**:

In order to have persistent storage for the monitoring stack, we need Prometheus to us a PV for its storage.

**What should be done**:

- update the Prometheus deployment to come with a PVC (which size do we request?)
- update the E2E tests: between the bootstrap and the execution of the E2E test we need to create a PV that can satisfy the PVC (otherwise Prometheus won't start and lot of things won't work…)
- update the documentation to inform the users that they should create a PV for Prometheus after the bootstraping.

**Test plan**:

Check that Prometheus does use persistent storage (data should be preserved accross pod restart).

**Comment by slaperche-scality** [comment]
Currently the UI depends on Prometheus, so if Prometheus is not running (because it waits for a Volume) the bootstrap will fail and the UI won't work.

We need to use the Ingress to avoid that, so this issue is blocked until then.

**Comment by gdemonet** [comment]
Maybe also consider use one for Alertmanager

**Comment by NicolasT** [comment]
Removing this from `2.4.0-beta1` after input from @xaf-scality. We want to deliver this ASAP,  but it requires a user-friendly way to manage to manage volume labels (#1500) which is necessary for #1681 to be not overly complex.
