### ISSUE TITLE
On-disk encryption of secrets etc.

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#1558]
Kubernetes has built-in support for encryption of data being stored in `etcd`, which would otherwise end up in plaintext on-disk.

Let's make sure to set this up.

**Comment by jbertran** [comment]
First iteration plans:

* On-disk key only - a KMS provider can be a second step
* `aescbc` since it's the most conservative choice
* Enable encryption via salt (i.e. create encryption key, encrypt and replace all secrets)
* Disable encryption via salt (decrypt and replace all secrets, remove encryption key)

We can either wait for a KMS provider and set up rotation when we get that, set up key rotation with an on-disk key now, or set up key rotation with an on-disk key later. I'm not sure what the scope of this ticket should be in that regard.

@NicolasT does that match with your expectations?

**Comment by NicolasT** [comment]
- Chances are slim we'd ever need/want KMS
- I'd start with implementing `identity` such that all configuration is in place
- Then indeed set up `aescbc`
- The key is to be generated during bootstrap, but should obviously not be recreated when re-applying some state...

So,

> Enable encryption via salt (i.e. create encryption key, encrypt and replace all secrets)

We only support encrypted data. One single key generated during bootstrap. No need to 'encrypt and replace'. We may implement key rotation later, if need be.

> Disable encryption via salt (decrypt and replace all secrets, remove encryption key)

Nope. Why would we want this?

No need for any kind of rotation, for now. This 'feature' is merely there such that a disk which contains the `etcd` database doens't contain any plain-text secret data. As such, if `/etc` and `/var/lib/etcd` sit on the same disk, no level of security is provided anyway. *Rotation* is not much of an issue either (at least for now): if one is able to retrieve the encryption key, one can likely at the same point in time read the `etcd` data.

This 'feature' is merely about: if someone deploys MetalK8s (with `/var/lib/etcd` on a separate device), then throws away that disk (only) without erasing it, an 'attacker' shouldn't be able to read secrets from said database.

So, KIS:
- Deploy config file, `identity` 'encryption'
- Deploy config file but with `aescbc` enabled, using a deployment-time-generated key
- Ensure this config (including the key) ends up on all API server nodes (i.e., may need to go in the `metalk8s_private` pillar?)
- Ensure that re-applying the deployment state (the one which initially would generate a new key) will not regenerate the config with a *different* key (hence, this may require a custom state/module to manage this configuration file properly)

**Comment by NicolasT** [comment]
Keep in mind
- we want this in `development/2.0` and up, because otherwise upgrades may become a hassle
- the 'lowest level' encryption must be `identity` so we can upgrade a pre-existing non-encrypted cluster to `development/2.0` (at which point we may want to enforce a crypt round of everything, but that'd be part of the manual procedure)
- the resulting key/config file *must* be part of the backup archive discussed in #1615

**Comment by jbertran** [comment]
I have to pay some idiot tax due to not thinking about allowing plain-text secrets to keep existing. Second PR to follow.

**Comment by NicolasT** [comment]
One more reason we need automated upgrade tests ;-)

**Comment by jbertran** [comment]
Closed by #1633 and #1665
