### ISSUE TITLE
Include documentation in the UI

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#1595]
It'd be valuable to have direct access to the MetalK8s documentation from within the UI (a link from one of the menus on the top, I guess, later on maybe to particular sections of the docs from within particular views/forms/... in the UI).

There are several ways to achieve this:

## Include a HTML rendering of the docs in the UI container and have this served by its `nginx`
The difficulty here lies in the fact that the docs sources are outside of the Docker build context of the UI container.

Some possible approaches:
- Change the build context of the UI container to `/`, and render the HTML as part of the UI `Dockerfile` execution (in a separate intermediate container), then copy things over
- Change the way we handle UI builds: instead of building it in Docker, built an SRPM/RPM, do the same for the (rendered) docs, and build the final UI container by installing those RPMs (next to `nginx` and whatnot)
- Build the docs as a separate container which only includes `busybox` and the rendered HTML, then, in the `metalk8s-ui` *Pod*, introduce an `emptyDir` volume, an `initContainer` which copies the HTML into this volume, and let the UI container's `nginx` serve the docs from this volume.

## Consider the docs/HTML to be a separate application
In this case, we can build the docs in some `Dockerfile`, `FROM nginx`, and serve the docs as-is. We can then either run `metalk8s-docs` as a separate *Pod* and let `/docs` (or whatever) be served by it in the `metalk8s-ui` `Ingress`, or run this *docs* container as a second container in the `metalk8s-ui` *Pod*, on a different port (bound to `127.0.0.1` only), and configure the main `metalk8s-ui` `nginx` to proxy `/docs` (or whatever) requests to this one.

There may be other approaches... Having the docs as static files in the the `metalk8s-ui` container somehow seems like the 'best' approach to me (no need to run one more `nginx` or other nonsense, and those HTMLs belong with the UI container if the UI actually links to them in the first place...), however not sure how to achieve this technically (at least with Docker. `buildah` would make this trivial).

Currently putting in milestone [2.4.0-beta1](https://github.com/scality/metalk8s/milestone/15) because it'd be really cool to have this from the start, given the UX evaluation feedback.

**Comment by NicolasT** [comment]
I guess what we *could* do is change `ui/Dockerfile` to build stuff only, then have a `Dockerfile` that builds the docs, then have another one in `images/metalk8s-ui` which is `FROM nginx`, then `COPY --from=metalk8s-ui-build:... ...` and `COPY --from=metalk8s-docs:... ...`, and ensure (in `doit`) that these are built 'in the correct order'.

A bit like building 2 RPMs and installing them in the target container...

**Comment by slaperche-scality** [comment]
If we plan to reuse the doc from elsewhere, a separate container could make sense.

But if we haven't plan for that yet, it's not worth the extra complexity: let's just copy the HTML into the UI container.


Also, we currently build our whole doc as a single document.
I wonder if it's pertinent to ship stuff like the Developer Guide to our end users (looks like its adding noise to me), not sure they care about our Python best practice or how to build an ISO from the sources.

**Comment by NicolasT** [comment]
@slaperche-scality We will reuse the docs elsewhere (on ReadTheDocs, our own hosting, whatnot). I don't think we'll reuse it *inside* the product at any other place.

Copying the HTML in the container image could work, but there's this `context` issue... so not sure how that copying could work practically?


When it comes to *content* of the doc: I think this is orthogonal to this issue. Once we figured out how to get it built and included properly, we could make the doc rendering 'parametrized' (likely using Sphinx tags?) which would then allow to create a build to be included with the product (e.g., excluding dev docs), a different build for open-source publication (including everything), one for https://documentation.scality.com which may yet again have a slightly different content,... Up to @scality/technical-publications to figure *that* part out (from a content PoV, not necessarily the technical/how side).

**Comment by slaperche-scality** [comment]
Yes indeed, content can be managed by tags and be addressed in another issue.

As for the context thing, using the root of the repo (+ a .`.dockerignore`) is probably the easiest (albeit not the cleanest) way to do it.
I feel like the RPM or 'container copy" approach is cleaner.

**Comment by NicolasT** [comment]
Using the root + `.dockerignore` won't be great, because the `.dockerignore` depends on *which* container is being built, and such.

I suggest we take the following approach:
- *Build* the UI as part of the build-chain: this can be in a container, sure, but the artifact (an RPM, a tarball, a directory tree, whatever) is *not* inside some container, but in `_build/...whatever` (not `_build/root/...`!)
- *Build* the docs as part of the build-chain: this can be in a container, sure, but the artifact (an RPM, a tarball, a directory tree, whatever) is *not* inside some container, but in `_build/..whatever` (not `_build/root/...`!)
- The build-chain takes these two artifacts and (if required) puts them in some directory *which we can then use as a Docker build context*
- We have a `Dockerfile` in `packages/metalk8s-ui` (similar to the others we already have in there) which will then take these artifacts, put them in a `nginx` container, set up an `nginx` configuration fille,...

This way, we could e.g. also turn the `ui/Dockerfile` into one which doesn't *build* (or does so only when invoked with a particular entrypoint argument), but runs `webpack-dev-server` by default instead.

Ping @carlito-scality @MonPote

**Comment by slaperche-scality** [comment]
LGTM, and sounds easy to implement on the buildchain side
