### ISSUE TITLE
Expose MetalK8s UI (and dependencies) on control-plane network (only)

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#1602]
Currently, the MetalK8s UI is exposed using a *nodePort* *Service*, which means it's bound to the workload-plane network. Similarly, if we were to set up an *Ingress* as-is, this would also be on a workload-plane address.

Instead, the UI (and its dependencies) should *only* be available on a (more restricted) control-plane address.

*How* to achieve this is another matter... It'll likely involve multiple ingress controllers, *if* the control-plane and workload-plane networks are *not* the same.

CC @xaf-scality

**Comment by charlesprost** [comment]
Let's tackle the ingress thing on other tickets then.

For this one, let's move the UI from the workload plane network (where it is now) to the control plane network (where it belongs because the UI gives access to critical features and management of the k8s cluster).

On top of changing the network, that would also require some configuration changes in the UI to use the new IP address. So the UI would be available on the same IP address as the one hosting the K8S API. But on a different port of course (due to the nodePort service).

**Comment by NicolasT** [comment]
> For this one, let's move the UI from the workload plane network (where it is now) to the control plane network (where it belongs because the UI gives access to critical features and management of the k8s cluster).
> 
> On top of changing the network, that would also require some configuration changes in the UI to use the new IP address. So the UI would be available on the same IP address as the one hosting the K8S API. But on a different port of course (due to the nodePort service).

That's not how it works. You can't nilly-willy change the address on which a `NodePort` *Service* is exposed: a `NodePort` *Service* is available on that specific port on *every* *Node* in the cluster (or at least, those running `kube-proxy`), so you can't configure one address or whatever on which the service is exposed (since every *Node* has a different address, of course).

The per-node address on which a `NodePort` *Service* is exposed is defines by the `kube-proxy` configuration, and (in our architecture) must be the workload-plane one.

**Comment by NicolasT** [comment]
Also, from a security PoV, *there is no issue* right now: both K8s API as well as SaltAPI are *only* expose on the control-plane network, and in the end, those are what we (mainly) care about. The UI itself is 100% public (heck, it's open-source), so fetching that HTML/JS/CSS code from the workload-plane IP is maybe not great, but doesn't harm from a security PoV. One could argue about Prometheus, sure, but that ain't super-critical either (at this stage of the project).

**Comment by NicolasT** [comment]
To summarize: this ticket is important and needs to be 'solved' at some point, but unless we do the *Ingress* thing, there's very little **actionable** here.
