### ISSUE TITLE
Build 'example' solution in CI

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#1605]
The 'example' solution was imported in https://github.com/scality/metalk8s/pull/1601 but isn't (AFAIK) built as part of a CI run, so the code could bit-rot easily. Furthermore, we need the resulting ISO image to perform any kind of automated testing of solutions.

The building of this 'example' solution should *not* be integrated in the MetalK8s build-system, since they're not related. At the same time, this (easily) allows to add a build-step to the Eve configuration which builds (and uploads) the solution ISO concurrently with the build of MetalK8s.

Next to pure building, setting up some linting, running unit-tests,... would be worth some time.

**Comment by gdemonet** [comment]
Closed by #2312
