### ISSUE TITLE
Solution lifecycle - rewording and improvements

### ISSUE THREAD

**Issue by sayf-eddine-scality** [scality/metalk8s#1609]
**Component**:
operators, solutions

**Why this is needed**:
Demo session feedback
**What should be done**:

- [x] Solutions menu entry on Platform UI should be always visible
- [ ] ~Namespace should be a free form (no need for part of when created)~ Not applicable
- [x] CR creation rewording: Custom resource --> ~application~ Component
- [ ] ~CR creation rewording: replicas --> instance/config~ Not useful
- [ ] ~CR creation form: clear separation between CRD config (name, namespace, version) and application CR config (replicas etc )~ Not useful
- [x] Version field should be a dropdown menu (information from solutions configmap)
**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by carlito-scality** [comment]
Done with https://github.com/scality/metalk8s/pull/1783
