### ISSUE TITLE
Deploy solutions from UI

### ISSUE THREAD

**Issue by sayf-eddine-scality** [scality/metalk8s#1610]
**Component**:
operators, solutions

**Why this is needed**:
switching between CLI and UI is not a good practice
**What should be done**:
The same thing done for deploying a new node, there can be a button to deploy the solution directly from the UI
**Implementation proposal** (strongly recommended):
- [ ] There is two orchestrator to call from salt api in order
- `metalk8s.orchestrate.solutions.available pillar={'bootstrap_id': xxxx } saltenv=metalk8s-xxxx` to mount solutions
- `metalk8s.orchestrate.solutions  pillar={'bootstrap_id': xxxx } saltenv=metalk8s-xxxx` to install/remove solutions
- [ ] After deployment check that deployment/pods are scheduled and running
**Test plan**:

**Comment by gdemonet** [comment]
There should be no need for this feature to avoid switching back-and-forth between UI and CLI. This kind of action should only be performed a small number of times, so I'd suggest we keep doing it from CLI, where we can benefit from a shell to inspect a local ISO archive.

Future enhancements could indeed support management of ISO archives from the UI, but would require more design (why do we need it there, what kind of use-case would be improved by such a UI integration...).

Moved out of high priorities.

**Comment by gdemonet** [comment]
Was implemented in #2318 and #2350
