### ISSUE TITLE
Improve the UX of the volume listing

### ISSUE THREAD

**Issue by slaperche-scality** [scality/metalk8s#1612]
**Component**:

UI

**Why this is needed**:

On a platform with a lof of volumes, the current design is not convenient/comfortable to use.

**What should be done**:

- Allow to filter the list of volume (using a search bar?) on status, on name, …
- Add a new column showing if the volume is bound or not (the info is only available in the Details page for now)

**Implementation proposal**:
*TBD*

**Test plan**:

*TBD*

**Comment by carlito-scality** [comment]
The search bar is available in core-ui https://scality.github.io/core-ui/?path=/story/searchinput--default.

**Comment by ChengYanJin** [comment]
split this issue into #1621 and #1622
