### ISSUE TITLE
MetalK8s 0.2.0 pre-release test-plan

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#162]
Prior to the MetalK8s 0.2.0 release, we'll want to validate a couple of things manually. Think of this as a poor-mans TestLink :wink:

Prior to testing, deploy a MetalK8s cluster _from scratch_ on _new VMs_ using MetalK8s 0.2.0-rc1 (to be created). Any cluster topology consisting of at least 3 `kube-node` servers should do.

When a test succeeds, put _Success_ in the *Status* column.
When a test fails, file an issue, and put the issue ID in the *Status* column, then we take it from there.

Whenever a test has no current owner, feel free to pick it up: add your Github ID in the *Owner* column, run the scenario, and report back.

| Test | Owner | Status |
| ----- | ---------| ------ |
| From-scratch deployment succeeds | @ssalaues | :heavy_check_mark: |
| Re-running the `deploy` playbook works | @NicolasT | :heavy_check_mark:  |
| Running the `services` playbook works | @NicolasT | :heavy_check_mark:  |
| Running the `reclaim-storage` playbook works, after deleting some PVC | @ssalaues | :heavy_check_mark: |
| Check etcd Grafana dashboard is deployed and working (#150) | @NicolasT | :heavy_check_mark:  |
| Check Elasticsearch Grafana dashboard is deployed and working (#150) | @NicolasT | :heavy_check_mark:  |
| Check node-exporter-full Grafana dashboard is deployed and working (#150) | @NicolasT | :heavy_check_mark:  |
| Check Prometheus Grafana dashboard is deployed and working (#150) | @NicolasT | :heavy_check_mark:  |
| New container log entries flow into Kibana (#159, #51) | @NicolasT | :heavy_check_mark:  |
| The `MetalK8s` Elasticsearch cluster is pre-configured in Cerebro (#145) | @NicolasT | :heavy_check_mark:  |
| 'Old-style' storage configuration in the inventory is detected and causes an error | NicolasT | :heavy_check_mark: (see note) |
| Ensure old log indices get cleaned up (#62, may be hard to test) | | Pending |
| Deploying Zenko succeeds, and Zenko basic functionality works (#149) | @ssalaues | :heavy_check_mark: |

Also: feel free to add more tests!

**Comment by ssalaues** [comment]
What should we expect when running the services playbook on an already deployed cluster? Is this simply setting these services back to MetalK8s defaults?

**Comment by NicolasT** [comment]
> What should we expect when running the services playbook on an already deployed cluster? Is this simply setting these services back to MetalK8s defaults?

Something like that, yes. There used to be a bug in the playbook due to which it couldn't be executed in isolation.

An interesting test could be to deploy MetalK8s with Elasticsearch etc. disabled (`metalk8s_elasticsearch_enabled=false`), then enable the var again (or remove the override, the default is `true`), finally run the `services.yml` playbook and assert Elasticsearch and all the services that come with it are now installed.

**Comment by ssalaues** [comment]
So far testing the latest on `development/0.2` passed from scratch deployment, redeploy, and Zenko install so far. I'll be sure to test again when 0.2-rc1 is built but just wanted to give some preliminary feedback. Good job guys!

**Comment by NicolasT** [comment]
Busy :bee: :smile:  Thanks for the feedback! Once #159 and #153 are in, we should be golden :raised_hands:

**Comment by NicolasT** [comment]
Test results in `heads/development/0.2-0-gcacb0287e` (i.e. pre-LVM-changes):

:heavy_check_mark: From-scratch deployment succeeds

:heavy_check_mark: Check etcd Grafana dashboard is deployed and working (#150)

`DB Size` panel not working, which is known (never worked, yet)

:heavy_check_mark: Check Elasticsearch Grafana dashboard is deployed and working (#150)

Except known-broken panels

:heavy_check_mark: Check node-exporter-full Grafana dashboard is deployed and working (#150)

Except known-broken panels

:heavy_check_mark: Check Prometheus Grafana dashboard is deployed and working (#150)

Ran `kubectl run kibana-test --restart=OnFailure --image=busybox -- echo "Hello, Kibana!"` and validated "Helllo, Kibana!" showed up in Kibana

:heavy_check_mark: The MetalK8s Elasticsearch cluster is pre-configured in Cerebro (#145)

**Comment by NicolasT** [comment]
I installed 0.2.0-rc1 on my 10-node cluster (3 etcd, 2 master, 5 nodes). Implicitly, `deploy.yml` was tested as well. All expected Pods were running.

**Comment by ssalaues** [comment]
Ran a from scratch deployment and ran `reclaim-storage.yml` successfully after deleting PVCs. Will test out a Zenko install next.

**Comment by ssalaues** [comment]
Successfully installed Zenko, manually tested basic functionality, and ran Cosbench for some stress.

**Comment by NicolasT** [comment]
Just ran the `'Old-style' storage configuration in the inventory is detected and causes an error` scenario.

Note: this assert could be put in `preflight-checks` to short-circuit playbook execution from the very start instead of after running various steps (including `ansible-hardening`). This is a nice-to-have for 1.0, no blocker for 0.2.0.

**Comment by NicolasT** [comment]
LGTM
