### ISSUE TITLE
v1beta1.metrics.k8s.io not working

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#1624]
The `v1beta1.metrics.k8s.io` *APIService* is not working:

```
[root@bootstrap ~]# kubectl describe apiservice v1beta1.metrics.k8s.io
Name:         v1beta1.metrics.k8s.io
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  apiregistration.k8s.io/v1
Kind:         APIService
Metadata:
  Creation Timestamp:  2019-09-05T09:32:38Z
  Resource Version:    923
  Self Link:           /apis/apiregistration.k8s.io/v1/apiservices/v1beta1.metrics.k8s.io
  UID:                 19da6c42-cfc0-11e9-a93b-08002791ec69
Spec:
  Group:                   metrics.k8s.io
  Group Priority Minimum:  100
  Service:
    Name:            prometheus-adapter
    Namespace:       metalk8s-monitoring
  Version:           v1beta1
  Version Priority:  100
Status:
  Conditions:
    Last Transition Time:  2019-09-05T09:32:38Z
    Message:               no response from https://10.96.10.86:443: Get https://10.96.10.86:443: dial tcp 10.96.10.86:443: connect: connection refused
    Reason:                FailedDiscoveryCheck
    Status:                False
    Type:                  Available
Events:                    <none>
```

This causes namespace deletion to fail (the `kubernetes` finalizer isn't removed because the controller is unable to validate all known object types are deleted from the *Namespace*, since listing all known object types fails: more background in https://github.com/kubernetes/kubernetes/issues/66735).

**Comment by NicolasT** [comment]
The issue is 'fixed' (manually) when
- editing the `prometheus-adapter` *Service* to set a proper `targetPort` (named or numbered)
- editing the `v1beta1.metrics.k8s.io` *APIService* to set `insecureSkipTLSVerify: true` properly in its `spec`

Given these seem to be set correctly in the manifest we apply, this is likely a bug in the `metalk8s_kubernetes` Salt *renderer*.

**Comment by Lincoln-dac** [comment]
i have no prometheus-adapter but how fix

**Comment by NicolasT** [comment]
> i have no prometheus-adapter but how fix

In MetalK8s? This is fixed in https://github.com/scality/metalk8s/pull/1630 so if you're running a sufficiently recent build, this should not be an issue.
