### ISSUE TITLE
shell linting ignores some errors

### ISSUE THREAD

**Issue by jbertran** [scality/metalk8s#1637]
**Component**: linting

**What happened**:

Calling `shellcheck` on the glob for shell files outputs less errors than calling a specific file (see the output below for an example)

```
 ✔  jbertran  ~/git/work/review  improvement/1616-download-debian-packages-from-official-repo  tox -e lint-shell                       
lint-shell run-test-pre: PYTHONHASHSEED='596139702'
lint-shell run-test: commands[0] | shellcheck doit.sh
lint-shell run-test: commands[1] | bash -c 'shellcheck **/*.sh'
lint-shell run-test: commands[2] | bash -c 'shellcheck **/*.sh.in'
________________________________________________________________________ summary _________________________________________________________________________
  lint-shell: commands succeeded
  congratulations :)
 ✔  jbertran  ~/git/work/review  improvement/1616-download-debian-packages-from-official-repo  shellcheck packages/debian/entrypoint.sh

In packages/debian/entrypoint.sh line 39:
download_packages() {
^-- SC1009: The mentioned syntax error was in this function.
                    ^-- SC1073: Couldn't parse this brace group. Fix to allow more checks.


In packages/debian/entrypoint.sh line 41:
    local -a list_pkg("$@")
                     ^-- SC1036: '(' is invalid here. Did you forget to escape it?
                     ^-- SC1056: Expected a '}'. If you have one, try a ; or \n in front of it.
                     ^-- SC1072: Missing '}'. Fix any mentioned problems and try again.

For more information:
  https://www.shellcheck.net/wiki/SC1056 -- Expected a '}'. If you have one, ...
  https://www.shellcheck.net/wiki/SC1036 -- '(' is invalid here. Did you forg...
  https://www.shellcheck.net/wiki/SC1072 -- Missing '}'. Fix any mentioned pr...
```

**What was expected**:

The `tox -e lint-shell` step should output as many errors as an individual `shellcheck` call on each shell script file.

**Steps to reproduce**

Inject a shellcheck error into a shell file (something like a missing `=` in a `local` declaration), run `tox -e lint-shell` and compare with a straight `shellcheck` call on the edited file.

**Resolution proposal** (optional):

Cause unknown.

**Comment by slaperche-scality** [comment]
It's not a matter of `shellcheck` ignoring errors: `tox` doesn't even run the linter on some files actually.

We are using the following command: `bash -c "shellcheck **/*.sh"`
Two problems here:
- `**` glob pattern is not recursive in Bash (it is in zsh)
- even if it was recursive, this would match files that we don't want to lint (shell scripts under `ui/node_modules` for example)

I will make a small PR for that.
