### ISSUE TITLE
Prune shipped images

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#1678]
Given #1672 some images (at least `addon-resizer-amd64`) are no longer used. However, we still include it in the built ISO.

Should perform a bootstrap install, check which images are pulles (`crictl images`), then remove any unused (and unwanted) ones from the buildchain (but not, e.g. `metalk8s-utils`, of course).

**Comment by slaperche-scality** [comment]
Seems like only `addon-resizer-amd64` and `kube-rbac-proxy` are unused.
