### ISSUE TITLE
Use fake endpoint for container image registry

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#1684]
**Component**:

'salt', 'containers'

**Why this is needed**:

For futur  HA bootstrap and being able to change registry without re-configuring/creating all pods

**What should be done**:

Use `metalk8s-registry-from-config.invalid` as registry and redirect this to the right IP in containerd config

**Comment by gdemonet** [comment]
See the [relevant `containerd` documentation](https://github.com/containerd/cri/blob/master/docs/registry.md#configure-registry-endpoint).

Would it be useful to also add a catch-all mirror: `[plugins.cri.registry.mirrors."*"]`?

**Comment by TeddyAndrieux** [comment]
> See the [relevant `containerd` documentation](https://github.com/containerd/cri/blob/master/docs/registry.md#configure-registry-endpoint).
> 
> Would it be useful to also add a catch-all mirror: `[plugins.cri.registry.mirrors."*"]`?

For me we shouldn't

**Comment by NicolasT** [comment]
No we shouldn't. We *know* that what we deploy is in the local repo. Any MetalK8s user can also deploy things with containers from other repos (heck, Zenko today needs online repos). Having such catchall would basically make it impossible to install anything not part of what's in the offline repos... Not cool.
