### ISSUE TITLE
Refactor versions

### ISSUE THREAD

**Issue by ycointe** [scality/metalk8s#1693]
**Component**: build 

**Why this is needed**: We need it to have a code more readable and to have a better Debian integration

**What should be done**: refactor version.py in the buildchain

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by jbertran** [comment]
Questions remaining after reviewing downloaded packages:

* I can't tell what `container-selinux` does beside providing selinux rules. Am I correct in thinking it's only a necessity on CentOS?
* Why do we download `python-kubernetes`? AFAIK we only need it on salt-master, and it's included in the CentOS image we ship for it
* Do we want to pin releases for kubelet/kubectl versions?
* Why do we download `skopeo`?

**Comment by TeddyAndrieux** [comment]
> Questions remaining after reviewing downloaded packages:
> 
> * I can't tell what `container-selinux` does beside providing selinux rules. Am I correct in thinking it's only a necessity on CentOS?

Container-selinux is a dependency of runc as the current upstream version on centos base repos is good enough we should just remove this one and let the package manager automagically get the right version.

> * Why do we download `python-kubernetes`? AFAIK we only need it on salt-master, and it's included in the CentOS image we ship for it

No longer needed IMO we can remove it

> * Do we want to pin releases for kubelet/kubectl versions?

IMO, we don't care about the release

> * Why do we download `skopeo`?

I don't know
