### ISSUE TITLE
Include documentation PDFs on ISO

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#1695]
Somewhat related to #1595: having the docs HTML included in the UI would be great at some point. Next to this (and somewhat as an intermediate step as well, maybe?), having a rendered PDF of the docs included on the ISO would be pretty useful as well.

**Comment by slaperche-scality** [comment]
A few questions:
- where do we put the PDF? At the root of the ISO? Or in a `docs` sub-directory?
- currently the generated file is named `MetalK8s.pdf`, do we want to rename it (like `MetalK8s-2.0.pdf` or `MetalK8s-2.0.0-dev.pdf`)?

**Comment by NicolasT** [comment]
I'd put it in a `docs` (or `doc`? @lucieleonard ) subdirectory so we can add additional material in there over time, if applicable.

I think it's fairly obvious this doc is about MetalK8s if it's found on its ISO, so maybe a completely different name, like `user-guide.pdf` or something alike could make more sense?

**Comment by gdemonet** [comment]
Since that issue implies adding the docs build to the main buildchain, I guess the CI step used to build docs will become irrelevant.

Also, related to naming, I agree with Nicolas, let's give the intent (not just `MetalK8s.pdf`), and ignore the version.

**Comment by slaperche-scality** [comment]
Out of scope of this issue I think, but we should probably only include relevant doc in the PDF (i.e remove developers doc at least)

**Comment by NicolasT** [comment]
I think we should keep the CI step building the docs. `doit` tends to hide the output of stuff it runs, and when doc building fails, we want to get clear output about the *why*.

**Comment by NicolasT** [comment]
> Out of scope of this issue I think, but we should probably only include relevant doc in the PDF (i.e remove developers doc at least)

Yes, will be the same for the HTML docs we ship as part of #1595. Guess we'll need to use Sphinx tags and such at some point.

However, as you said, shipping everything, including less relevant things, is better than shipping nothing.

**Comment by slaperche-scality** [comment]
Targeting 2.4 is enough I guess?

**Comment by NicolasT** [comment]
Think so, yes.

**Comment by slaperche-scality** [comment]
> doit` tends to hide the output of stuff it runs, and when doc building fails, we want to get clear output about the _why_.

By default (can be modified by setting `verbosity` for the task or globally), `doit` always shows `stderr` and capture `stdout`.
If the task fails, then `stdout` is displayed.

So I guess it should be fine.

```
% ./doit.sh
.  hello
STDERR
% ./doit.sh
.  hello
STDERR
TaskError - taskid:hello
PythonAction Error
Traceback (most recent call last):
  File "/home/sylvain/do/.venv/lib/python3.7/site-packages/doit/action.py", line 424, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/sylvain/do/dodo.py", line 11, in python_hello
    raise Exception('BOOM')
Exception: blyat

########################################
hello <stdout>:
STDOUT
```
