### ISSUE TITLE
Track Kubespray master node replacement certificate issues

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#17]
https://github.com/kubernetes-incubator/kubespray/issues/2448
https://github.com/kubernetes-incubator/kubespray/pull/2496

**Comment by NicolasT** [comment]
Also: https://github.com/kubernetes-incubator/kubespray/pull/2544

**Comment by thomasdanan** [comment]
kubespray not part anymore of metal2.X ... closing the issue as we won't do it.
