### ISSUE TITLE
Bootstrap still need to use hostname as node_name

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#1706]
**Component**:

'salt', 'kubernetes'

**What happened**:

We use `hostname` to mark the control plane node so the node_name need to be the hostname

**What was expected**:

Do not need to use hostname as node_name and minion_id

**Steps to reproduce**

Run a bootstrap with minion_id different not equal to hostname

**Resolution proposal** (optional):

Use node name instead of hostname in `salt/metalk8s/kubernetes/mark-control-plane/deployed.sls.in`

**Comment by NicolasT** [comment]
Ref #1700
