### ISSUE TITLE
Add a CI step to filter and retrieve an integration branch

### ISSUE THREAD

**Issue by Ebaneck** [scality/metalk8s#1707]
**Component**:

'upgrade', 'downgrade', 'test'

**Why this is needed**:

To test Metalk8s upgrade/downgrade, we need to build two ISO images with minor versions N and N-1.

We need to be able to find/obtain the integration branch of the (N-1) branch because it contains the new feature which will be added to the N branch.

The suppose integration branch is created by `eve` and we should find a way to retrieve it.

**What should be done**:

To be discussed.

**Implementation proposal** (strongly recommended):

To be discussed.

**Test plan**:

To be discussed.

**Comment by TeddyAndrieux** [comment]
No integration branch concept in MetalK8s (and upgrade/downgrade is already handled in the CI nowadays)
