### ISSUE TITLE
Remove `container-selinux` manual installation

### ISSUE THREAD

**Issue by jbertran** [scality/metalk8s#1710]
**Component**: packages, salt

**What happened**: While attempting to get rid of our "manual" download of `container-selinux` despite it being a dependency for `runc` (as a consequence, it should be pulled by our package download regardless), the package installation macro crashed because we install `container-selinux` manually in salt, only to install `runc` immediately after.

IIRC we worked around an issue this way, but AFAIK this is no longer required.

**What was expected**: No need to specify `container-selinux` as a downloaded package.

**Steps to reproduce**: remove `container-selinux` declaration in builchain `versions.py`, attempt to build and bootstrap.

**Resolution proposal** (optional): Remove the manual installation of the package. If this is the route taken, the package should also be removed from the listing in `versions.py`.

**Comment by gdemonet** [comment]
Done since the refactoring of package versions management in buildchain.
