### ISSUE TITLE
docs: fix version

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#1725]
Currently, the Sphinx project's version is hard-coded in the project configuration file. This should, however, be retrieved from the `VERSION` file (or `product.txt`, depending on the build context?).

**Comment by slaperche-scality** [comment]
Related to https://github.com/scality/metalk8s/issues/1703 no?

Maybe `version.py` could be used as input, since @gdemonet designed it to be buildchain-independant (so that it can be used outside) with the intention to use it as a unique source of truth for the versions.

**Comment by NicolasT** [comment]
It's related but not entirely the same.

I thought #1703 is about the *text* in the docs which uses 'incorrect' version numbers, and should use a replacement/I-forgot-how-it's-called-in-ReST, based on (indeed) the version from the conf.

Also, the *doc* version is the *product/project* version, so not sure how `version.py` is involved here?

**Comment by NicolasT** [comment]
Related: we currently set `release` to `2.4.0-dev` (for example) in case of non-tagged 'releases'. However, we'll want to use a more elaborate format here, similar to what we have in `product.txt`, including `git describe` output (i.e. the `GIT` field).

**Comment by slaperche-scality** [comment]
> Also, the doc version is the product/project version, so not sure how version.py is involved here?

`version.py` loads the content of `VERSION`

**Comment by NicolasT** [comment]
Ah, I thought you were referring to `versions.json`, which doesn't necessarily exist (or is not necessarily up to date) when docs are built.

**Comment by NicolasT** [comment]
My bad, indeed duplicate of #1703.
