### ISSUE TITLE
repositories pod crash when upgrading/downgrading between 2.3 and 2.4

### ISSUE THREAD

**Issue by sayf-eddine-scality** [scality/metalk8s#1739]
**Component**:
repositories, ubuntu

**What happened**:
`hostPath type check failed: /srv/scality/metalk8s-2.3.0-dev/packages/redhat is not a directory`

**What was expected**:
repositories pod to be up and running

**Steps to reproduce**
try to upgrade/downgrade between 2.3 and 2.4

**Resolution proposal** (optional):
the path change should be taken into consideration in the state `metalk8s.repo.installed`

**Comment by TeddyAndrieux** [comment]
I suggest to backport the change from #1484 in 2.0
