### ISSUE TITLE
monitoring: etcd and kube-proxy monitoring fails

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#1766]
When looking at the Prometheus 'targets' in its UI, `metalk8s-monitoring/prometheus-operator-kube-etcd/0` and `metalk8s-monitoring/prometheus-operator-kube-proxy/0` are unavailable: the `etcd` one appears to be a HTTPS answer to an HTTP request, the `kube-proxy` one due to `connection refused`.

This needs to be fixed, and could benefit from an automated test which validates all Prometheus targets are 'up' after a successful *bootstrap*.

**Comment by NicolasT** [comment]
For `etcd`, we need to set the `scheme` to `https`, and create a *Secret* that contains an `etcd` client certificate, which should then be exposed to Prometheus using the `secret` field of the *Prometheus* object.

Some more intel: https://github.com/coreos/prometheus-operator/issues/2207

**Comment by NicolasT** [comment]
Given different target versions, there are 2 PRs required to fix this issue (at least for `development/2.3` and up). Hence, neither of them has a `Fixes: #1766` tag, so this will need to be closed manually once both PRs are merged.

**Comment by slaperche-scality** [comment]
Both PR are merged.
