### ISSUE TITLE
containers' file limitation is too low

### ISSUE THREAD

**Issue by fferrandis** [scality/metalk8s#1785]
**containers**:

**What happened**:
When we deploy HD thru our k8s controller, we have a very small limitation of max open files allowed to the process run in the container.
The current limitation allowed is only 1014, which is way too low for processed implied in HDs 

It seems that containerd does not allow to change ulimit values
```
ulimit -n 819200
bash: ulimit: open files: cannot modify limit: Operation not permitted
```

Also, trying to use the operator-sdk API to add additionnal parameters to pod deployment doesn't work because they are _unsafe_

```
diff --git a/pkg/controller/hdservice/hdcontroller/hdcontroller.go b/pkg/controller/hdservice/hdcontroller/hdcontroller.go
index 77adc07..3475843 100644
--- a/pkg/controller/hdservice/hdcontroller/hdcontroller.go
+++ b/pkg/controller/hdservice/hdcontroller/hdcontroller.go
@@ -240,6 +240,9 @@ func NewDeployment(cr *v1alpha1.HdService, ID, cMapName, cType, relName string)
                                                },
                                        },
                                        Volumes: volumes,
+                                       SecurityContext: &corev1.PodSecurityContext{
+                                               Sysctls: []corev1.Sysctl{corev1.Sysctl{Name: "fs.file-max", Value: "100000"}},
+                                       },
                                },
                        },
                },

```
```
kubectl get pod
NAME                                      READY   STATUS             RESTARTS   AGE
default-http-backend-5d5ff5d4f5-8j7v7     1/1     Running            28         8d
....
my-hdservice-monitor-1-7b8968497b-l8dsf   0/1     **SysctlForbidden**    0          1s

```

**What was expected**:

To have a way to change this value, either globally, or directly in the HD operator

**Comment by NicolasT** [comment]
Given this would be a system-global change when the `containerd` service configuration would be updated, which value do you think would be reasonable? I'd rather not set it to `unlimited`...

**Comment by NicolasT** [comment]
Oh, I see you use `100000` in the patch, so that'd be something sensible?

**Comment by NicolasT** [comment]
Ref. https://github.com/containerd/containerd/pull/3202

**Comment by fferrandis** [comment]
> Oh, I see you use `100000` in the patch, so that'd be something sensible?

No, it was just for testing purpose :)

**Comment by fferrandis** [comment]
> Given this would be a system-global change when the `containerd` service configuration would be updated, which value do you think would be reasonable? I'd rather not set it to `unlimited`...

Don't have a value based on real study .... Let's start with a big value (65500) for now, and will refine it if you are not comfortable with

**Comment by NicolasT** [comment]
I'll use the value that'll be used in `containerd` 1.3.0, cfr. the issue I linked above.

**Comment by NicolasT** [comment]
@fferrandis See the 'manual test' in the description of https://github.com/scality/metalk8s/pull/1787. That's what you expect, right?
