### ISSUE TITLE
Create an Ingress object for Grafana

### ISSUE THREAD

**Issue by charlesprost** [scality/metalk8s#1798]
Blocked by #1796 

**Component**:

'kubernetes', 'ingress'

**Why this is needed**:

Because we want to expose Grafana using an Ingress, so it could be available on something like: <some_workload_plane_network_ip_address>(:80)/grafana

**What should be done**:

Create such an object and make sure it targets the proper Ingress class for the workload plane network.

**Implementation proposal** (strongly recommended):

Probably some stuff to solve to make it work on the /grafana route. To be done also in the UI to make sure it works if we have a link to Grafana. Not sure about this.
Should we keep the nodePort service? I don't know.

**Test plan**:

- Grafana should be available on <some_workload_plane_network_ip_address>(:80)/grafana
- Everything should work as before

**Comment by NicolasT** [comment]
FWIW, Grafana should go on control-plane, not workload-plane, I'd argue.
