### ISSUE TITLE
Track Kubespray long-polling proxy timeout issues

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#18]
One one side there's https://github.com/kubernetes-incubator/kubespray/issues/2150 and https://github.com/kubernetes-incubator/kubespray/pull/2151

Given history, there's https://github.com/kubernetes-incubator/kubespray/issues/655 and https://github.com/kubernetes-incubator/kubespray/pull/656

May need to work with @xaf-scality to figure out how to tackle this correctly.

**Comment by thomasdanan** [comment]
kubespray not part anymore of metal2.X ... closing the issue as we won't do it.
