### ISSUE TITLE
Support configuration of `nginx-ingress` TCP/UDP proxying from inventory

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#180]
To expose the NFS service to the outside world, Zenko requires an Ingress Controller which supports proxying of TCP streams and UDP packets to a Service. This is supported by `nginx-ingress` which we use, but can't be configured using a plain `Ingress` object (this may need some further investigation, though).

The `nginx-ingress` chart which we use to deploy the service allows to (statically) configure such proxies (https://github.com/helm/charts/blob/9f78ebf325952ffc2da03cf863c6da2fd871b366/stable/nginx-ingress/values.yaml#L364), but currently there's no way to alter the `values.yaml` we use to configure the deployment from inside an inventory. We should either

- support setting these specific values for this specific chart through the inventory

or

- support setting arbitrary chart values for any chart through the inventory

Changes to the inventory configuration would, of course, require to re-run the `services.yml` playbook (or part of it using tags).

Cfr. ZENKO-669

**Comment by NicolasT** [comment]
Also see #238 which lays the foundation.

**Comment by NicolasT** [comment]
This is closed by #291 right, @Zempashi ?

**Comment by Zempashi** [comment]
Hmm did not test, but should be. We should add some documentation

**Comment by thomasdanan** [comment]
won't do in metal1.1 and working in metal2.X
