### ISSUE TITLE
Missing tests for `rawBlockDevice`

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#1804]
We have tests in place for the `sparseLoopDevice` feature of the `storage-operator`, however, none are in place for `rawBlockDevice`.

Writing these may seem difficult since we don't know which block devices are available on the system. However, we *can* write such tests, by using a little trick: sparse-file backed loop devices that we provision *as part of the test* (`setUp`, so you want), and then use as the device to be consumed by a `rawBlockDevice` *Volume*. After running the test(s), the loop device and sparse file can be cleaned up again on the host.

**Comment by TeddyAndrieux** [comment]
The same applies to `lvmLogicalVolume` (may need another ticket)
