### ISSUE TITLE
Retrieve the backup/restore archive from a bootstrap node

### ISSUE THREAD

**Issue by Ebaneck** [scality/metalk8s#1805]
**Component**:

'tests', 'backup', 'restore' 'ci'

**Why this is needed**:

Currently, at the end of each bootstrap process, a backup archive is automatically generated.
We need to be able to check/verify that a bootstrap node restore is possible using the backup archive or using a newly generated backup archive.

**What should be done**:

Add a CI step to connect to the bootstrap node and retrieve the backup archive. The backup file is located in the following directory `/var/lib/metalk8s/`

Take note that all ISOs referenced in the bootstrap configuration file (located at /etc/metalk8s/bootstrap.yaml) must be present for a successful restore.
For the CI, we would most likely make reference to just one ISO file which is the built ISO.

**Implementation proposal** (strongly recommended):

We should keep the backup file in one of the following two places:

- As an artifact URL or
- Copy it to the bastion host(SCP)

The suppose CI step most be added to the multi-node build stage for the following reasons. The restore script would only work in a High Availability API-server setup.
see : https://metal-k8s.readthedocs.io/en/latest/operation/bootstrap_backup_restore.html?highlight=backup

**Test plan**:

**Comment by alexandre-allard** [comment]
Closing this issue as it has already been done in #2061 (#1687)
