### ISSUE TITLE
Destroy the bootstrap node in an attempt to test backup and restoration.

### ISSUE THREAD

**Issue by Ebaneck** [scality/metalk8s#1806]
**Component**:

'tests', 'backup', 'restore' 'ci'

**Why this is needed**:

While performing a bootstrap node recovery, we do not have any real need for the old bootstrap node and as such we should destroy it completely.

**What should be done**:

Add a CI step to destroy the old bootstrap node.

**Implementation proposal** (strongly recommended):

Seems to me that there is no real need to destroy the entire open stack multi-node infrastructure. We could destroy the bootstrap node with a  `kubectl delete node bootstrap`

It looks like some extra cleanup is needed such as 
- Maybe cleaning up Persistent Data if any exist on the host (prometheus data for example)
- For any hosts that had ran an etcd service, there could be  a couple of items that may need to be cleaned up (e.g Remove the etcd backups by running rm -r /var/lib/etcd/member/*.)

**Test plan**:

**Comment by alexandre-allard** [comment]
Closing this issue as it has already been done in #2061 (#1687)
