### ISSUE TITLE
Spawn a new bootstrap node using the backup archive 

### ISSUE THREAD

**Issue by Ebaneck** [scality/metalk8s#1807]
**Component**:

'tests', 'backup', 'restore' 'ci'

**Why this is needed**:

We need to spawn a new bootstrap node using the backup archives and the necessary ISO files to validate that bootstrap node recovery is possible.

**What should be done**:

Add a CI step that does the following:
- mount the ISO 
- run the restore script.

**Implementation proposal** (strongly recommended):

The CI step should execute the following command `/srv/scality/metalk8s-X.X.X/restore.sh --backup-file <backup_archive>` once the ISO file has been mounted

**Test plan**:

A new bootstrap node should be created successfully.

**Comment by alexandre-allard** [comment]
Closing this issue as it has already been done in #2061 (#1687)
