### ISSUE TITLE
Grafana Dashboards Link from the UI(s)

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#1817]
**Component**:

metalk8s-ui (or more)

**Why this is needed**:

Once logged in metalk8s UI (or any other solution admin UI actually), I would like to quickly access grafana dashboard in case I need to do deeper investigation.

**What should be done**:

As a first step, from the UI, a button or menu should be available to open the grafana home page in a new browser tab. Ideally, since we are already logged in the UI, we don't want to ask the user to log again in Grafana.
I think we want this functionality for all UIs (metalk8s and sol admin uis) ... don't know how it impacts implementation (should it be in core ui ?)

In future steps we may want more contextual links to directly jump into specific dashboards depending on where we are in the UI but this will be tracked through other issues.

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by NicolasT** [comment]
This requires #1802, otherwise Grafana is not exposed (without running a `kubectl port-forward` or so).

**Comment by gdemonet** [comment]
Such links in the example Solution UI will require #1859 and #1860.

**Comment by carlito-scality** [comment]
Link is available in Metalk8s UI: See https://github.com/scality/metalk8s/issues/1901

**Comment by thomasdanan** [comment]
This one has been implemented as part of the rework on MetalK8s UI
