### ISSUE TITLE
Build may fail due to Docker registry being unavailable

### ISSUE THREAD

**Issue by charlesprost** [scality/metalk8s#1844]
**Component**:

'ci', 'build'

**What happened**:

When building the ISO in this build https://eve.devsca.com/github/scality/metalk8s/#/builders/1/builds/12383, we faced the following issue:
```
.  PULL IMG     kube-controller-manager:v1.14.6
.  PULL IMG     kube-proxy:v1.14.6
.  PULL IMG     kube-scheduler:v1.14.6
.  PULL IMG     nginx-ingress-defaultbackend-amd64:1.5
.  PULL IMG     grafana:6.3.5
.  PULL IMG     nginx-ingress-controller:0.25.0
.  PULL IMG     calico-node:v3.8.2
time="2019-10-04T07:29:50Z" level=fatal msg="Error initializing source docker://grafana/grafana:6.3.5: Get https://registry-1.docker.io/v2/grafana/grafana/manifests/6.3.5: EOF" 
TaskFailed - taskid:_image_pull:grafana
Command failed: '['skopeo', '--override-os', 'linux', '--insecure-policy', 'copy', '--format', 'v2s2', 'docker://docker.io/grafana/grafana:6.3.5', 'dir:/home/eve/workspace/kube_pod-prod-metalk8s-backend-0/build/_build/root/images/grafana/6.3.5']' returned 1
```

**What was expected**:

We expect the Docker registry to be available and the ISO being built as expected.

**Steps to reproduce**

Not sure since it's flaky.

**Resolution proposal** (optional):

As discussed with @bertranddemiddelaer we could use the proxy cache from the pod worker by running something like this from the worker to setup the vars and certs for the proxy cache:
```
curl -s http://proxy-cache/setup.sh | sudo sh && . /usr/local/bin/use_scality_proxy_cache
```

**Comment by slaperche-scality** [comment]
#1874 is merged.
