### ISSUE TITLE
Add E2E testing of Solutions CLI integration

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#1850]
**Component**: tests, solutions

**Why this is needed**: Prepare future integration to CI (in post-merge test suite), validate first iteration

**What should be done**: Implement a simple test of build and deployment for the `examples/metalk8s-solution-example` embedded in the repo

**Implementation proposal**:

- [ ] In some Eve step (not triggered by pre-merge)
  - [x] Build Solution ISO (`cd examples/metalk8s-solution-example && make iso`)
  - [x] Add archive with `solutions-manager.sh`
  - [x] Deploy Solution Operator in some Namespace (no `Environment` involved there)
  - [x] Add CRs and check the exposed HTTP endpoints

**Comment by alexandre-allard** [comment]
Done in #2321
