### ISSUE TITLE
Rewrite Solutions manager script (in Python and Go)

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#1854]
**Component**: scripts

**Why this is needed**: Logic is getting too complex for Bash

**What should be done**:

- Rewrite the Bootstrap-local parts in Python (import/unimport, maybe activate/deactivate)
- Rewrite the other parts in a `kubectl` plugin

**Test plan**: Update tests introduced by #1850 and #1852 

---
Epic: #2163

**Comment by NicolasT** [comment]
This is in the same realm as #1588.

**Comment by TeddyAndrieux** [comment]
Close this issue as it will be done in different tickets

- import #2455 
- unimport #2456 

- activate #2468 
- deactivate #2469 

- create-env #2472 
- delete-env #2473 
- add-solution #2476 
- delete-solution #2477
