### ISSUE TITLE
Reduce Prometheus unavailability warning in UI when storage is not yet provisioned

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#1890]
As reported by @xaf-scality:

After bootstrap, but before (manually) provisioning the storage volumes required by Prometheus and AlertManager to operate, Prometheus can't start (by design). At this point, when accessing the UI, one gets strong warnings about Prometheus not being accessible.

While in general this is OK, we should tone this down a bit when this situation (i.e., the Prometheus Pod is Pending because its PVC can't be bound) by detecting it (we have access to the Kubernetes API). In this case, we should have some kind of 'orange' state, referring to the documentation (ideally linking to it, #1595) explaining how to resolve the situation.

**Comment by gdemonet** [comment]
So, unfortunately, there is no `status` in `Prometheus` or `AlertManager` CRs (yet, see coreos/prometheus-operator/issues/887).
In the meantime, we can look at the `Pod`s themselves.

To get a Prometheus Pod, use the label selector `app=prometheus` (`app=alertmanager` for AlertManager Pod), and list Pods in the `metalk8s-monitoring` namespace.

Once you have the Pods, you can look at either:
- their `status.conditions` array, which should contain a single object with `type: PodScheduled`, `status: False`, and a `message` value saying something like `0/1 nodes are available: 1 node(s) didn't find available persistent volumes to bind.`
- their `volumes` array, looking for any of them having `type: PersistentVolumeClaim`, and then query the related PVC using the `name` you found, checking that it is in state `Pending`

I'm not entirely sure which approach should be used (cc @NicolasT).

In any case, this check should only be performed if Prometheus/AlertManager are not available as we would expect them.
