### ISSUE TITLE
UI: Provision volumes with labels (in the PV template)

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#1891]
After bootstrap, a user must create *Volume*s to provide storage for Prometheus and AlertManager. We deploy a *StorageClass* for this, but the *PersistentVolumeClaim*s for these services also use a `labelSelector` to pick the 'right' *PersistentVolume*.

It's currently not possible to specify these when creating a *Volume* through the UI. As such, one can't complete the installation using the UI only, and needs to resort to using `kubectl` (e.g. by editing and applying the example manifest shipped on the ISO), which is sub-optimal.

**Comment by gdemonet** [comment]
Labels provisioning was not done in the PV template, as requested by this issue. Re-opening.
