### ISSUE TITLE
Implement a (new) 'helm' Ansible module

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#190]
- Allow to set `values` in task
- Allow to keep `values` in `files` and injected (can use Ansible for this)
- Allow to set `values` in inventory, and apply using proper `-f ...` sequence
- Set repository, name, version,...

I think it'd make sense to first implement this inside MetalK8s, then later we may want to extract in a separate project/repository.

When the above functionality is implemented, #180 becomes possible as a side-effect.

**Comment by NicolasT** [comment]
@Zempashi Since you put this in 1.1.0 (which I was about to do now ;)), are you working on this? If so, please self-assign.

**Comment by Zempashi** [comment]
Yes, I do. We can move this for later release, I wasn't aware we had enough feature to release 1.1.0, it was just show that's something we want to work on "soonish". (And this will help #230)

**Comment by NicolasT** [comment]
Oh no, no 1.1.0 release planned soon, so this can definitely go in, and is indeed a good step to handle #230, #180 and others!
