### ISSUE TITLE
Add verbose argument to upgrade and downgrade script in the CI

### ISSUE THREAD

**Issue by Ebaneck** [scality/metalk8s#1914]
**Component**:

'upgrade', 'downgrade'

**Why this is needed**:

Just like the bootstrap script in the CI, we should run the upgrade and downgrade script in verbose mode.

This provides an enormous sos report we can leverage on for debugging purposes.

**What should be done**:

- Add the verbose(-v) argument to both upgrade and downgrade script

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by gdemonet** [comment]
Done by #1946
