### ISSUE TITLE
Solution UI: Improve environment "prepare" URL management

### ISSUE THREAD

**Issue by carlito-scality** [scality/metalk8s#1917]
**Component**:Solution UI

**Why this is needed**:
- We currently have a route `/environments/:name/version/:version/prepare` to allow to prepare an environment with a `desired version`. It would be better to store the desired version in the `Environment` object itself. The `current version` of the environment is the operator's one. We will create a new route (`/environments/:name/prepare`) to allow to prepare/upgrade the environment from `current version` to the  `desired version`

**What should be done**:

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by gdemonet** [comment]
Let's not implement this as part of the first iteration of Solutions Lifecycle. We need to clarify responsibilities of a Solution Admin UI, and what service(s) it can access (Salt? MetalK8s-specific CRDs?)

**Comment by gdemonet** [comment]
Obsolete (see #2246)
