### ISSUE TITLE
Salt Master readiness probe may timeout

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#1918]
**Component**: salt, kubernetes

**What happened**:

On real hardware, with a cluster size of roughly 10 nodes, Bootstrap node being still tainted, the `salt-master` container in the `salt-master-<node_name>` Pod was never ready, due to its `readinessProbe` timing out.

Consequence was that the `salt-master` Service never allocated an Endpoint, hence having most Salt operations broken (pillar `metalk8s:endpoints:salt-master` contains `_errors`).

**What was expected**: The readiness probe should not timeout if the `salt-master` is actually ready (not just slow, which it was in this case)

**Steps to reproduce**: ?

**Resolution proposal** (optional): Increase timeout to 5s, or allocate more resources

**Comment by slaperche-scality** [comment]
I think we already bumped a timeout like that before, see b1553dbac02a605417da8ecc9f753585f4098834.
Maybe this is another one, but that would mean that we may want to do a global review of our timeout values (to spotany suspectingly low value) to avoid future issue like that.

**Comment by gdemonet** [comment]
Indeed, this commit fixes the exact issue described here. It may not have been included in the affected version though, will confirm this tomorrow.
For other readiness/liveness probes, agreed, but that would be a much larger scope, so I'll open a dedicated issue.

**Comment by TeddyAndrieux** [comment]
This need to be backported in 2.0 (that will fix many flakiness issue)
