### ISSUE TITLE
Pre Check required pkgs for K8S cluster node installation are available

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#1938]
**Component**:

Metalk8s precheck/deployment

**Why this is needed**:

Installation of bootstrap and any node of the cluster rely on certain pkgs being available through centos / rhel base and extra repos. We anticipate that in some situations, those repos may not be available. As such, we would like to warn the one deploying the product required pkgs are available before trying to deploy anything on the servers.

**What should be done**:

If required pkgs from base/extra repos are not available, warn the user and point him to the right documentation page explaining how to make those pkgs available.

**Implementation proposal** (strongly recommended):

The idea would be to check, using yum info, that few required pkgs are available from base and extra repos. If those pkgs are available, we will assume all other ones (coming from the same repos) are also available and deployment should continue. If one pkgs is not available, installation should be aborted and a clear warning message should explain why and ideally display a doc URL or a reference to the page that will explain how to make those pkgs available fro all nodes of the cluster

**Test plan**:

**Comment by slaperche-scality** [comment]
> using yum info

If it's through Salt, good.

But if it's gonna be another script, it would be better to use the Python API of Yum (which is easy, `yum` being written in Python itself) since our trend is to move away from shell to Python.

**Comment by gdemonet** [comment]
To answer your valid concerns @slaperche-scality, this pre-check will need to happen on any new node installation (before installing `salt-minion`).

So, it needs to occur once during bootstrap (which can't be from Salt, but will be done in the bootstrap script, which we'll rewrite in Python at some point), and when/before applying `metalk8s.roles.minion` on a new Node (which can be done from Salt indeed).

Both occasions would benefit from the Python API for Yum, IMHO, but it may wait for a rewrite of the bootstrap script. For now, I think this issue is going to be tackled in #1928 (see a8a7549), since the PR is actually the one creating a need for such a check in the first place. If that's not acceptable, I think @alexandre-allard-scality will need to know about it, sooner rather than later.

**Comment by slaperche-scality** [comment]
Ho ok, if it's part of the bootstrap script I guess it's fine to do it in Bash now, and migrate everything to Python at once.
I guess we could write this part in Python and call it from the bootstrap script but not sure if it's worth the effort.

**Comment by alexandre-allard** [comment]
I've done it in both bash (in `scripts/bootstrap.sh.in`) with yum CLI & python (in `salt/_modules/metalk8s_package_manager_yum.py`) based on yum module.
So I think we can take the code in the Salt module when we'll want to pythonize bootstrap script.
The logic in both scripts is based on the exact same mechanisms.

**Comment by slaperche-scality** [comment]
The only thing that's bothering me is that, IIRC, Yum is Python-2 only that may not be future proof…

**Comment by gdemonet** [comment]
Would make sense to check what Salt does, since it's supposed to work on RedHat-based systems with Python 3.

**Comment by slaperche-scality** [comment]
Maybe Salt just shell out to `yum` or its replacement (`bnf`? `dnf`? don't remember the name).
But yeah it's worth a look.

Edit: Looking at `modules/yumpkg.py`, It does support both `yum` and `dnf`.

```
.. note::
    DNF is fully supported as of version 2015.5.10 and 2015.8.4 (partial
    support for DNF was initially added in 2015.8.0), and DNF is used
    automatically in place of YUM in Fedora 22 and newer.
```

IIUC, They call the binaries directly (for both `yum` and `dnf`), the only moment they use `yum` as Python package is to parse the configuration.

Also, `dnf` will be the default package manager on RedHat starting from RHEL 8.

**Comment by gdemonet** [comment]
Maybe it makes sense to rely on those Salt modules as much as possible when using Salt, not sure if we want to go down the road of having this multi-OS/multi-version support in custom modules, just to check if we can install some packages...

**Comment by alexandre-allard** [comment]
done in #1928
