### ISSUE TITLE
Document how to make base / extra repos available on K8S cluster nodes

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#1939]
**Component**:

documentation

**Why this is needed**:

as explained in #1938, we may try to deploy in an environment where all required packages are not available. In such a situation, we should explain the one deploying the product on how to make those pkgs available.

**What should be done**:

If the base and extra pkgs are not available, we should explain from where to fetch official RHEL / centos iso and make the required repos available on all nodes. Ideally (if possible but more a nice to have), we also have a little script that will do it automatically for all nodes of the cluster.

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by TeddyAndrieux** [comment]
By default CentOS ISOs (like http://centos.mirror.ate.info/7/isos/x86_64/) only contains "base" package but not all the "extras" and "updates" packages we need. So we can't use (only) this ISO.

And btw I didn't found any ISO containing all the "extras" and "updates" packages.

So either:
1- we build ourself ISO(s) containing all the repos "base" "extras" and "updates" (that need to be rebuild often)
2- we just ask in the doc to have the "base" "extras" and "updates" repos contain available on each and every machine with Local copy, http server, official repos, whatever

Personnally prefer/suggest 2- but 1- is doable and not really really expensive (but how/where do we serve them ?)

(cc @NicolasT @alexandre-allard-scality @gdemonet )

**Comment by TeddyAndrieux** [comment]
As discussed offline we will for the moment do only "2-" and maybe build our own ISO(s) later.

2 sections: 
- how to enable repos CentOS and RedHat (RHSM)
- how to setup mirrors repos
