### ISSUE TITLE
Explain how to change passwd to access K8S, Salt APIs and Grafana

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#1940]
**Component**:

documentation

**Why this is needed**:

Currently, we pre-provision user admin with password admin with all privileges !!! As a consequence, anyone could access the UI (or APIs) and trigger dangerous MetalK8s operations. This behaviour is not secure enough and it is very likely that the customer will ask for defining his own admin password for both APIs and Grafana

**What should be done**:

We should document in official MatelK8s documentation how to change the password for APIs and Grafana

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by gdemonet** [comment]
Needs rewording, see comments in #1944
