### ISSUE TITLE
Document how to enable IP-in-IP encapsulation for virtual networks

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#1949]
**Component**: networking, calico

**Why this is needed**:

For installations of MetalK8s on virtual hardware/networks (e.g. public clouds such as AWS EC2), we cannot rely on Calico's `CrossSubnet` encapsulation strategy, because packets will be dropped due to unknown destination addresses (`ClusterIP`s).

**What should be done**:

Provide in documentation (in a subsection of the Quickstart guide for now) a procedure to enable IP-in-IP encapsulation even within a subnet (Calico's `Always` strategy).

**Implementation proposal** (strongly recommended):

Use the `kubectl patch` from `eve/workers/openstack-multiple-nodes/terraform/scripts/enable-ipip.sh`

**Test plan**: not applicable

**Comment by TeddyAndrieux** [comment]
For me should be part of operation guide not quickstart guide as it's something we do after a MetalK8s deployment

**Comment by NicolasT** [comment]
I'd at least then put a 'note' in the install/quickstart guide with a link to the relevant section in the operation guide, because this is a 'strange situation' one can easily run into during installation.

**Comment by TeddyAndrieux** [comment]
Yes but we can't enable IpIp during installation (for the moment). Ok lets put doc in operation and ref in quickstart

**Comment by NicolasT** [comment]
https://github.com/scality/metalk8s/issues/1234
