### ISSUE TITLE
UIs: Replace injectIntl HOC by intl Hooks

### ISSUE THREAD

**Issue by carlito-scality** [scality/metalk8s#1950]
**Component**:UIs

**Why this is needed**:
- As we begin to use React Hooks, It would be nice to use react-intl's Hooks as well to be consistent.

**What should be done**:
- We need to update the version of react-intl to `3.4.0`. Be careful, there will be breaking changes to remove `addLocaleData` (See: https://github.com/formatjs/react-intl/blob/35a3708179b8522646d1db0dcf729aacd5bc3835/docs/Upgrade-Guide.md#breaking-api-changes)
- Then replace injectIntl HOC by intl Hooks in all components

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by ChengYanJin** [comment]
Duplicated with #2836
