### ISSUE TITLE
Elasticsearch Curator not using custom config

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#196]
Instead of cleaning up indices after 3 days, the `elasticsearch-curator` configuration is set to 7 days, which is the chart default, despite our override in `values.yml`.

Turns out there's a mistake in `values.yml`: the key in `configMaps` is `action_file.yml`, and the chart uses `configMaps.action_file_yml` :thinking:

**Comment by NicolasT** [comment]
Confirmed to be fixed, leaving only 3 days of logs. Hopefully once and for all...

**Comment by dcvtruong** [comment]
What is the correct configMaps.action_file_yml syntax use for overriding? the docs reference "See values.yaml" but don't know where to start.
