### ISSUE TITLE
UI: Error when refreshing Volume Information page

### ISSUE THREAD

**Issue by carlito-scality** [scality/metalk8s#1977]
**Component**:UI

**What happened**:
- When we go to the volume information page and refresh this page, we got this error: 

![image](https://user-images.githubusercontent.com/47394132/67941639-61915b80-fbd6-11e9-9540-b695b54b3bc1.png)

**What was expected**:
- Make sur we have requested volume information before loading this page.

**Steps to reproduce**

**Resolution proposal** (optional):

**Comment by gdemonet** [comment]
From the screenshot, maybe using `volume?.metadata?.name` could be sufficient?

**Comment by carlito-scality** [comment]
> volume?.metadata?.name

Yes.It is enough
