### ISSUE TITLE
Solution Lifecycle: tooling and solution example

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#1993]
Framework and tools to deploy solutions on top of MetalK8s cluster:

- Import solution
- Deploy Operator and UI
- UI to create Environment (i.e. namespace)
- Fined grain salt tooling
- Upgrade / Downgrade Operator and UI
- Solution Example

**Comment by gdemonet** [comment]
This iteration is now complete. Next steps are all consigned in the [Solutions Lifecycle project](https://github.com/scality/metalk8s/projects/18).
