### ISSUE TITLE
Backup management

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#2]
(What's below is copied and slightly edited from an earlier e-mail thread)

For on-prem K8s deployments, we should think about 'backup': which cluster information should be backed up? How do we achieve this?...

AFAIK all that's needed is to back-up the content of the etcd cluster used as a datastore for master nodes, not necessarily etcd-events, and the etcd data stored for the CNI system (Calico in our case, likely). If I'm not mistaken this is stored in the very same etcd cluster as used by kubeapi/master nodes.

**Comment by NicolasT** [comment]
Feedback by @Zempashi:

> There is little information about backup: https://kubernetes.io/docs/getting-started-guides/ubuntu/backups/
> There is no need to backup everything (ip allocated to a pod is so ephemeral that it is useless to backup, and could be harmful if migrating to a new infrastructure with different network layout).
>
> But as the documentation suggests (?) a kubernetes cluster can live with  all it state restored.
>
> The use of etcd operator that handles Snapshot and restore feature of etcd could be great but requires a kubernetes up and running... which could be problemactic is case of a restore
>
> There is an export command for kubectl that strip server side information (creation date, etc...). But I don't think we can make use of it.
>
> For me the complicated part is to backup our own application data, and be able to restore them on an empty Zenko system (yet deployed)
>
> Last point to be backed up is monitoring...

**Comment by NicolasT** [comment]
Some useful intel: https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

**Comment by liqweed** [comment]
Have you considered backing up data volumes using [AppsCode Stash](https://github.com/appscode/stash) or [Heptio Ark](https://github.com/heptio/ark) for that? Both under Apache 2.0.

**Comment by NicolasT** [comment]
@liqweed We'll need to investigate the available options, currently nothing has been decided, so thanks a lot for those pointers!

On first sight, Stash seems to be primarily used to backup actual volumes provided by a K8s cluster. In our case, `etcd` is not running as part of the cluster, so its storage volumes are not managed by it. We're currently not looking for backup of 'workload' volumes: our applications take care of replication/HA themselves, and backup of (node-local) volumes can, if desired, be managed using other tools (however, one may always use Stash inside a MetalK8s cluster, of course).

Ark may be more related to what we're trying to achieve here, i.e. disaster-recovery of the K8s cluster and its resources, not the workloads running on top.

I'll need to dig deeper in those tools, so I may be missing something obvious in the above ^^ please correct me if that's the case!

**Comment by NicolasT** [comment]
Since we now have a `backup` script, should we set up some schedule to run this at regular times?

**Comment by thomasdanan** [comment]
@gdemonet @NicolasT AFAIK we have a solution for this in MetalK8s 2.X, I suggest we close this one and maybe open a new one to have a periodic backup?

**Comment by gdemonet** [comment]
Or keep this one. I have no opinion.

**Comment by thomasdanan** [comment]
#2735 created, closing this one
