### ISSUE TITLE
Add steps to upgrade between patch versions

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#2009]
**Component**: upgrade, downgrade, tests, ci

**Why this is needed**:
Test that upgrade/downgrade between patch versions is working fine

**What should be done**:
We should do what's already done for minor version upgrade/downgrade.
Add two steps in the CI (1 for upgrade and 1 for downgrade)

**Implementation proposal** (strongly recommended):
Upgrade:
- Get version X.Y.(Z - 1) ISO
- Install version X.Y.(Z - 1)
- Launch tests
- Get version X.Y.Z ISO
- Upgrade to version X.Y.Z
- Launch tests

Downgrade:
- Get version X.Y.Z ISO
- Install version X.Y.Z
- Launch tests
- Get version X.Y.(Z - 1) ISO
- Downgrade to version X.Y.(Z - 1)
- Launch tests

**Test plan**: N/A

**Comment by gdemonet** [comment]
Implementation may differ from the proposal. IMHO, we should only do such test **if** there was a released GA version with the same `X.Y`.

**Comment by TeddyAndrieux** [comment]
> Implementation may differ from the proposal. IMHO, we should only do such test **if** there was a released GA version with the same `X.Y`.

Its basically just checking that `Z > 0`
