### ISSUE TITLE
Configure the UI to require authentication through Dex

### ISSUE THREAD

**Issue by Ebaneck** [scality/metalk8s#2015]
**Component**: 

'ui', 'kubernetes', 'authentication'

**Why this is needed**:

Basic authentication for MetalK8s UI access will become depreciated after Dex deployment

**What should be done**:

The MetalK8s UI should directly use dex to authenticate a user using OAuth2 flow.
- User visits MetalK8s UI.
- The MetalK8s UI redirects the user to dex with an OAuth2 request.
- Dex determines the user's identity.
- Dex redirects the user to Metalk8s UI with a code.
- MetalK8s UI exchanges code with dex for an id_token......

**Implementation proposal** (strongly recommended):
TBD

**Test plan**:
TBD

---

Epic iteration: #1988

**Comment by gdemonet** [comment]
Closed by #2042
