### ISSUE TITLE
Add backup for ingress controller ca certificate

### ISSUE THREAD

**Issue by Ebaneck** [scality/metalk8s#2031]
**Component**:

'authentication', 'kubernetes'

**Why this is needed**:

For MetalK8s cluster recovery purposes.

**What should be done**:

In the backup and restore script, make sure to back-up/restore the following dex certificates and keys.
- Dex server certificate & key
- Dex root ca & key

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by TeddyAndrieux** [comment]
Do we really want to backup server cert as a new one can be generated using the CA ?
IMO no ~~, but maybe we want that user do not need to accept the cert again as this cert is user facing so ... TBD~~

Edit: After reflection we cannot backup/restore this server cert as this need to contains some IPs that may change after a restore
