### ISSUE TITLE
Dark/Light Mode switch from UI

### ISSUE THREAD

**Issue by carlito-scality** [scality/metalk8s#2034]
following: #2121 

**Component**:UI

**Why this is needed**:
- The UI currently is in Dark Mode by default. It should be able to switch between Dark Mode and Light Mode.

**What should be done**:
-  As we want to add one more action(switch theme) in the navbar, the navbar will become heavier. So we want to wrap the edit language and switch dark/light mode in the `settings`

<img width="721" alt="METALK8S PLATFORM" src="https://user-images.githubusercontent.com/18453133/70395700-b019ed00-1a01-11ea-9278-40f97d82bd2e.png">

- Update the theme.js configMap to add 2 modes:

```
{
  "theme":{
    "light":{
      "brand":{      
        "base": "#F7F6F9",
        "baseContrast1": "#ECF4FF",
        "primary": "#313B44",
        "secondary": "#e99121",
        "success": "#23AD56",
        "info": "#00B2A9",
        "warning": "#F1B434",
        "danger": "#EF3340",
        "background": "#ffffff",
        "backgroundContrast1": "#F7F6F9",
        "backgroundContrast2": "#FAF9FB",
        "text":"#000000",
        "border":"#000000"
      },
      "logo_path":"/brand/assets/branding-light.svg"
    },
    "dark":{
      "brand":{
        "base": "#121214",
        "baseContrast1": "#192A41",
        "primary": "#A7B6C3",
        "secondary": "#2979ff",
        "success": "#23AD56",
        "info": "#00B2A9",
        "warning": "#F1B434",
        "danger": "#EF3340",
        "background": "#0D0D0D",
        "backgroundContrast1": "#1D1D21",
        "backgroundContrast2": "#171717",
        "text": "#ffffff",
        "border": "#ffffff"
      },
      "logo_path":"/brand/assets/branding-dark.svg"
    },
    "custom":{}
  },
  "default": "light"
}


```
- The current mode will be stored in the browser `localstorage`
- The default theme we should get from configMap and store it in config saga

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by thomasdanan** [comment]
closing this one as it will be tackled by https://github.com/scality/metalk8s/issues/2545
