### ISSUE TITLE
Deploy Promtail

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#2054]
**Component**:

'salt', 'kubernetes'

**Why this is needed**:

Loki allow to have a log aggregation but need some logs. Promtail allow to send logs to Loki

**What should be done**:

Deploy Promtail to every nodes to send all logs to Loki (need #2053)

**Comment by gdemonet** [comment]
DaemonSet or static Pods?

**Comment by NicolasT** [comment]
> DaemonSet or static Pods?

`DaemonSet`.

**Comment by NicolasT** [comment]
So, while `promtail` should get *Pod* logs into *Loki*, it doesn't take care of any other kind of logs (system logs, basically).

What do we envision for those? Can `promtail` take care of those as well? If not, we'd need something like `fluent-bit` and/or `fluentd`, at which point we may question the use of `promtail`?

**Comment by TeddyAndrieux** [comment]
Hmm ok I thought that we could basically just add a volume and edit the config file to add systems logs, not tested for the moment just creating ticket but if `promtail` can't, I will go for `fluent-bit`

**Comment by TeddyAndrieux** [comment]
After some design we decided to use fluent-bit #2701
