### ISSUE TITLE
Bind DEX static user to a Role or a ClusterRole

### ISSUE THREAD

**Issue by Ebaneck** [scality/metalk8s#2055]
**Component**:

'authentication', 'salt', 'kubernetes'

**Why this is needed**:

A newly created **DEX** static user has no access to any resources in a Metalk8s cluster as there is no Role or ClusterRole bound to it.

This superuser needs to be bound to a cluster-wide role in other to be able to create and manipulate Metalk8s cluster resources.

**What should be done**:

- Create a cluster role that gives full admin access to the entire Metalk8s cluster
- Bind the Clusterrole using appropriate cluster role bindings

**Implementation proposal** (strongly recommended):

**Test plan**:

- Kubectl get clusterrole <clusterrole_name>and validate that it exists.
- Kubectl get clusterrolebinding <clusterrolebinding> and validate that it exists.

**Comment by NicolasT** [comment]
Such ClusterRole already exists (with a corresponding ClusterRole finding
for entities in the `system:masters` group), so all you'll need is a
ClusterRoleBinding, or add the user to a group if Dex would support that
nowadays.

**Comment by Ebaneck** [comment]
Went down the road of  adding our static user to `cluster-admin` clusterrole using a clusterrolebinding since dex does not support groups for it's static users as stated here : https://github.com/dexidp/dex/issues/1080
