### ISSUE TITLE
Use a YAML Renderer to create ConfigMap SLS

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2070]
Both of `salt_embed_text` and  `salt_embed_bytes` could rely on `yaml.dump` (see https://github.com/scality/metalk8s/pull/2042/commits/1ada06c5769e987afc7473cb58250419e413b5bd for an example of how to customize representers). 

_Originally posted by @gdemonet in https://github.com/scality/metalk8s/pull/2062_

**Comment by slaperche-scality** [comment]
Solved with https://github.com/scality/metalk8s/pull/2120
