### ISSUE TITLE
Label and organize Grafana dashboards

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#208]
We currently deploy all dashboards at the 'root'. Adding labels, and putting them in folders, would be good.

**Comment by NicolasT** [comment]
Suggested grouping:
![screenshot from 2018-07-30 13-03-19](https://user-images.githubusercontent.com/102605/43393887-fa40f170-93f8-11e8-9eb9-4e18aceb4ace.png)

**Comment by alxf** [comment]
The `folder` creation and management is only available through the http api, we can't manipulate them from the json we are importing.

**Comment by NicolasT** [comment]
Thanks for reporting back, @alxf. Let's stick with adding labels to the various dashboards for now, then. I'd prefer to stay away from the complexity of interacting with APIs of deployed services as much as possible. If something can't be configured statically, we may want to avoid doing it at all :)
