### ISSUE TITLE
Downgrade are failing because of python2-kubernetes version change

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#2081]
**Component**: salt

**What happened**: `python2-kubernetes` has been bump recently in `epel` repository, this version drops support of some apiVersion like `V1beta1Ingress` which we use, so we've replaced it with the new one `ExtensionsV1beta1Ingress`.
Problem is when we downgrade, we try to do some stuff using the downgraded salt-master container, with the current modules which contain the fix and it breaks.

```
[ERROR   ] Failed to import utils kubernetes_utils, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1534, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/var/cache/salt/master/extmods/utils/kubernetes_utils.py", line 286, in <module>
    model=k8s_client.ExtensionsV1beta1Ingress,
AttributeError: 'module' object has no attribute 'ExtensionsV1beta1Ingress'
```

**What was expected**: Downgrade are working fine.

**Steps to reproduce**: Build an iso from the latest development/2.5, install it and try to downgrade to a 2.4.x released version.

**Resolution proposal** (optional):

**Comment by TeddyAndrieux** [comment]
Fixed by #2101
