### ISSUE TITLE
UI: update core-ui

### ISSUE THREAD

**Issue by carlito-scality** [scality/metalk8s#2085]
**Component**:UI

**Why this is needed**:
- As we added new features above all the improvements of navbar to be aligned with Use Design design and they introduced breaking changes, we need to address them as soon as possible.

**What should be done**:
`ToggleVisible, languages, applications, help, user` should be removed

**Implementation proposal** (strongly recommended):

**Test plan**:
- No regressions

**Comment by ChengYanJin** [comment]
already merged by PR #2086
