### ISSUE TITLE
Admin K8S and Grafana password must remain unchanged after an upgrade

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#2109]
**Component**:

'upgrade'

**What happened**:

When upgrading to a new version, admin password customisation is overridden with factory settings

**What was expected**:

During an upgrade, customised password for K8S API and Grafana should not change 

**Steps to reproduce**

Deploy MetalK8s 2.4.1
configure admin password (for k8s api and grafana) according to documentation 
Upgrade to MetalK8s 2.4.2
Make sure you can still use customised password

**Resolution proposal** (optional):

**Comment by Ebaneck** [comment]
As discussed, we will not be able to persist the customized Grafana password at this moment in time. A design session will be planned to discuss this.

The necessary heads-up documentation will be added to make users aware.
