### ISSUE TITLE
Expansion doc enhancement

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#2116]
**Component**:

'documentation'

**Why this is needed**:

https://metal-k8s.readthedocs.io/en/latest/quickstart/expansion.html
We need to give better guideline on how to use the UI or the CLI to expand the cluster

**What should be done**:

- Review CLI expansion content and better explanation on how to set roles / taints
- Explain the mapping between UI high level checkbox and roles / taints

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by ChengYanJin** [comment]
1.  Delete the Defining an architecture section 

2.  How to achieve three examples: "control-plane", "infra", "workload+infra" 
    a. Select `Control Plane` box: Master and etcd services run on this node.
    b. Select `Infra` box: Infra services run on this node.
   c.  Select `Work Plane` and `Infra` box: Infra services and workload applications run on this node.

- Roles/Workload Plane: if you select this box, you will remove all the taints and enable the `node` role if Infra Box isn't selected.
- Roles/Control Plane: if you select this box, you enable both role and taint for `master` and `etcd`.
- Roles/Infra: if you select this box, you enable both role and taint for infra. ( If Control Plane box is also selected, you will remove the taints for `master` and `etcd`)

3.  Introduce what's roles and taint ( And give the link to the introduction)
[Roles ](https://metal-k8s.readthedocs.io/en/latest/installation/introduction.html#node-roles)determine a Node responsibilities.
[Taints ](https://metal-k8s.readthedocs.io/en/latest/installation/introduction.html#node-taints) are comliementary to roles.

- A node exclusively in the control-plane with etcd storage will have:
Roles and taints both are set to master and etcd. Same as the checkbox of `control plane` in MetalK8s GUI

- A node dedicated to infra services (see Introduction) will use:
Roles and taints both are set to infra. Same as the checkbox of `infra` in MetalK8s GUI

- A simple worker still accepting infra services would use the same role label without the taint:
Roles are set to node and infra. Same as the checkbox of `workload` and `infra` in MetalK8s GUI.

**Comment by gdemonet** [comment]
Just discussed with @thomasdanan, and here's what we think should be done (feel free to suggest changes) from the current Cluster expansion page:
- remove section Defining an architecture (it will be done in #2112)
- in the UI section, when choosing the role checkboxes to tick, show how to achieve the three examples ("control-plane", "infra", "workload+infra") and what it means (which services will run on such nodes)
- in the CLI section, first introduce roles / taints (as you mentioned already), and show how to achieve the same three examples
- add a small warning in CLI section saying it is more advanced (help on formulation @lucieleonard ?)
- maybe add an example of what can be done in CLI that can't in the UI (e.g. a Node dedicated to `etcd`)
