### ISSUE TITLE
Add label in every k8s metalk8s object deployed 

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#2132]
**Component**:

'salt', 'kubernetes'

**Why this is needed**:

Currently we cannot know, for each and every object we deploy in metalk8s, the metalk8s version deployed. This version could really help to do proper upgrade and downgrade.

**What should be done**:

When deploying an object in metalk8s, add a label about the metalk8s version used to deploy this object `metalk8s.scality.com/version`

**Implementation proposal** (strongly recommended):

TBD:
- Adding autmoatically in our custom module/state/utils
- Added manually in each and every object

**Comment by gdemonet** [comment]
:+1: for the automatic annotation added by Salt. Maybe use something like `metalk8s.scality.com/deployed-with-version`, or `.../saltenv`, to be super explicit.
