### ISSUE TITLE
Dex logout doesn't work when the language is set to French

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2148]
**Component**: ui, authentication

**What happened**: When the French language is set, the logout function doesn't work.

**What was expected**: Redirect to the dex login page

**Steps to reproduce** Login the Metalk8s => change the language to french  => LOGOUT

**Resolution proposal** (optional):

The way we do logout maybe is not enough
```
export function* logout() {
  const userManager = yield select(state => state.config.userManager);
  if (userManager) {
    userManager.removeUser(); // removes the user data from sessionStorage
  }
}
```
Maybe we can get some inspiration from the `USER_SIGNED_OUT` action
https://github.com/maxmantz/redux-oidc/blob/master/docs/Actions.md

**Comment by gdemonet** [comment]
Closed by #2153
