### ISSUE TITLE
Unclear error reported from bootstrap.sh in case of missing BootstrapConfig

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#2150]
**Component**: salt

**What happened**:

Run `bootstrap.sh` without having a BootstrapConfiguration at `/etc/metalk8s/bootstrap.yaml`:

```
Failure while running step 'Calculating Salt grains in local mode'
Command: salt-call --local --state-output=mixed --retcode-passthrough state.sls metalk8s.node.grains saltenv=metalk8s-2.4.1 pillarenv=metalk8s-2.4.1
[CRITICAL] Pillar render error: Failed to load ext_pillar metalk8s: 'NoneType' object has no attribute 'get'
[ERROR   ] Execption caught loading ext_pillar 'metalk8s':
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 956, in ext_pillar
    key)
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 895, in _external_pillar_data
    val)
  File "/var/cache/salt/minion/extmods/pillar/metalk8s.py", line 125, in ext_pillar
    config = _load_config(bootstrap_config)
  File "/var/cache/salt/minion/extmods/pillar/metalk8s.py", line 27, in _load_config
    __utils__['pillar_utils.assert_equals'](config, expected) +
  File "/var/cache/salt/minion/extmods/utils/pillar_utils.py", line 26, in assert_equals
    if source_dict.get(key) != value
[CRITICAL] Pillar render error: Failed to load ext_pillar metalk8s: 'NoneType' object has no attribute 'get'
local:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Failed to load ext_pillar metalk8s: 'NoneType' object has no attribute 'get'
<< END >>
This script will now exit
```

**What was expected**: A clear error message stating that this file is mandatory.

**Resolution proposal** (optional):

- Fix the `_load_config` function so that it doesn't raise an `AttributeError` when calling `__utils__['pillar_utils.assert_equals'](config, expected)` but returns pillar errors as expected
- Maybe pre-check the file existence in `bootstrap.sh` before running anything

**Comment by Ebaneck** [comment]
I think we had a similar unclear error reported with @anurag4DSB when we actually had a `/etc/metalk8s/bootstrap.yaml` file missing a few fields(e.g no apiVersion).

The reported error was something in the line ...```Failed to load ext_pillar```

So => | Maybe pre-check the file existence in bootstrap.sh before running anything| is not enough
