### ISSUE TITLE
The theme of Dex login page should be the same as the MetalK8S theme

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2158]
**Component**: ui, authentication

**Why this is needed**: As a user, I want to have the same experience with Dex login and MetalK8S.

**What should be done**:
- The default theme should be the same as the default theme of MetalK8S ui-branding configMap (light mode)
- When the user set their preference, ideally, the theme of Dex theme should be updated.
- The dex theme configMap should be rename to `dex-scality-light-theme` and `dex-scality-dark-theme`

**Implementation proposal** (strongly recommended):
TBD

**Test plan**:
TED

**Comment by Ebaneck** [comment]
Please add the new UI image of the login page to the docs here: https://metal-k8s.readthedocs.io/en/development-2.6/installation/services.html#metalk8s-gui
