### ISSUE TITLE
Timeout when injecting pause image

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#2170]
**Component**: salt

**What happened**: when downgrading salt fails to inject pause image because containerd is not restarted yet

**What was expected**: containerd is started and the pause image is injected

**Steps to reproduce**: install MetalK8s, change the containerd configuration file (the systemd unit for example), then apply the `metalk8s.container-engine.containerd` state.

**Resolution proposal** (optional): add a delay at containerd service (using `init_delay`) start to ensure it's ready.

**Comment by gdemonet** [comment]
Done with #2171
