### ISSUE TITLE
CPU usage graph is broken due to "outdated" query

### ISSUE THREAD

**Issue by tcarmet** [scality/metalk8s#2172]
**Component**: Grafana dashboard / Prometheus operator

**What happened**: The graph of CPU usage in Grafana is not showing anything.

![Screenshot](https://user-images.githubusercontent.com/8408330/71715549-07995600-2e12-11ea-8a8a-e1bd7fd3dfcd.png)

Note that this is not the only dashboard having this symptom, everything that uses the same query is broken, therefore, every dashboard under `Kubernetes / Compute Resources /`

**What was expected**: I was expecting to see a graph showing the CPU usage of each resources. But I have empty graph even though there's resources running in my cluster.

**Steps to reproduce**: install metalk8s 2.4.1

**Resolution proposal** : I might be wrong here, so don't follow this blindly, but I think that the following query is outdated
```
sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster="$cluster"}) by (namespace)
```
And should be replaced by:
```
sum(namespace:container_cpu_usage_seconds_total:sum_rate{cluster="$cluster"}) by (namespace)
```

**Comment by Ebaneck** [comment]
@tcarmet  after taking a closer look at the Grafana query, I think we are using an inappropriate rule name in our Prometheus rules.
It is strange how this bug came into play.. I suspect this happened when we updated the charts.

I am going to make a quick fix for this...
