### ISSUE TITLE
Missing grafana-piechart-panel plugin after updating prometheus-operator to 8.1.2

### ISSUE THREAD

**Issue by Ebaneck** [scality/metalk8s#2175]
**Component**:

'charts'

**What happened**:

No dashboard graph for kubernetes-networking-workload

**What was expected**:

All dashboards should have stats information

**Steps to reproduce**

- Deploy MetalK8s after updating prometheus operator to 8.1.2
- Check the kubernetes-networking-workload dashboard

![missing_pie_plugin](https://user-images.githubusercontent.com/10956602/71826566-8276a100-309e-11ea-9cad-eda8f99d869d.png)

**Resolution proposal** (optional):

- Issue exists upstream https://github.com/helm/charts/issues/19825
- Update Grafana to 6.4.4-1??

**Comment by NicolasT** [comment]
This is odd. Are we using the right version of Grafana and such, synced with what the chart expects?

**Comment by Ebaneck** [comment]
> This is odd. Are we using the right version of Grafana and such, synced with what the chart expects?

I think yes, we are using the right version of Grafana as from the Charts.
The Grafana version currently stands at `6.4.2`  as specified in the New Charts(prometheus-operator 8.1.2) and in the buildchain

**Comment by NicolasT** [comment]
I'm a bit surprised... That'd mean there's a bug in the upstream chart as well?

**Comment by Ebaneck** [comment]
> I'm a bit surprised... That'd mean there's a bug in the upstream chart as well?

Looks like so, the above issue has a link to a recently opened issue upstream

**Comment by NicolasT** [comment]
Hah, totally missed that, my bad :blush:

**Comment by s2504s** [comment]
Hi all!
We faced this issue too
Somebody know/have some work around for this issue?

**Comment by NicolasT** [comment]
@s2504s One approach as implemented in https://github.com/scality/metalk8s/pull/2177 is to build a Grafana container image which does have the required plugin pre-installed.

We're also investigating using a newer version of Grafana (overriding this version in the Helm `values` we use) instead. If this works, then we'll revert the changes of #2177 and deploy a newer version of Grafana.

We'll upstream this Grafana version change to the Charts repository if things work out.
