### ISSUE TITLE
Ability to spawn openstack env and automate MetalK8s deployment on top of it

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#2196]
**Component**:

'test', 'salt'

**Why this is needed**:

Many users of MetalK8s don't really care of doing fine-tuned deployment of the cluster but rather looking for a simple solution to have deployed cluster on OpenStack environment so that they can demo it or use it to develop their own solutions. This could also be used in the context of automated tests.

**What should be done**:

We should put in place a simple way to describe and spawn open stack infra in order to host MetalK8s.
Using Openstack HEAT or another tooling we would then need to automate MetalK8S deployment on the top of it (including volume provisioning and other mandatory post-install configurations)

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by NicolasT** [comment]
This is basically #2124 and https://github.com/scality/metalk8s/pull/2130, right?

**Comment by thomasdanan** [comment]
closing this EPIC as it is duplicated with #2280
