### ISSUE TITLE
Ubuntu Support

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#2204]
**Component**:

'salt', 'build'

**Why this is needed**:

We may have users (to be confirmed) whishing to deploy MetalK8s on their Ubuntu environment.

**What should be done**:

Support the latest Ubuntu LTS version not more 6 months (TBC) after it was released.
This type of deployment should be tested in the CI
All binaries and pkgs should be included in the unique MetalK8s archive (next to centos pkgs)

**Implementation proposal** (strongly recommended):

**Test plan**:

**Estimation**: 2W

**Comment by NicolasT** [comment]
Is this something we intend to do in 2021? Otherwise I believe we should close this one and remove the (unmaintained, untested,...) Ubuntu support from the project.

**Comment by gdemonet** [comment]
@thomasdanan to decide, I guess
