### ISSUE TITLE
Dex authentications tests fail with ConnectionRefused error

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#2229]
**Component**: tests/authentication

**What happened**:

Flakiness in CI execution of the `tests/post/steps/test_authentication.py` suite. Observed failing tests:

- `test_reach_openid_config`
- `test_access_https_service`
- `test_failed_login`

Example error log:

```
    def _dex_auth_request(control_plane_ip, username, password):
        try:
            response = requests.post(
                'https://{}:{}/oidc/auth?'.format(control_plane_ip, INGRESS_PORT),
                data={
                    'response_type': 'id_token',
                    'client_id': 'metalk8s-ui',
                    'scope': 'openid audience:server:client_id:oidc-auth-client',
                    'redirect_uri': 'https://{}:{}/oauth2/callback'.format(
                        control_plane_ip, INGRESS_PORT
                    ),
                    'nonce': 'nonce'
                },
                verify=False,
            )
        except requests.exceptions.ConnectionError as exc:
            pytest.fail("Dex authentication request failed with error: {}".format(
>               exc
                )
            )
E           Failed: Dex authentication request failed with error: HTTPSConnectionPool(host='<control_plane_ip>', port=8443): Max retries exceeded with url: /oidc/auth (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe61ecece10>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**What was expected**:

We would now expect no failure, and sufficient resilience to inaccessible services.

**Steps to reproduce**: _N/A - flaky_

**Resolution proposal** (optional):

Finer pre-checks were added to these tests to reduce the risk of such errors in #2213. It is now
required to provide resilience to such errors in case they would appear.

Since such situations will probably occur with other services across our test suites, especially when the tested infrastructure is under high load (which _may_ be the case for CI runs), it could be reasonable to provide a `retry` logic at the `requests` library level. For instance, see [this blog post](https://www.peterbe.com/plog/best-practice-with-retries-with-requests).

We should also wrap such calls in the `utils.retry` method, as we already do across the test suite.

**Comment by Ebaneck** [comment]
I fully accept with you that it is now evident that we should provide a `retry` logic at the `requests` library level.

I will like to propose the use of the  `backoff` library I earlier found resourceful which can be looked upon as a slightly cleaner approach. You can find it here: https://github.com/litl/backoff/

I also did a test run of the library available here: https://github.com/scality/metalk8s/compare/development/2.5...improvement/proposal-to-fix-MaxRetryError

Positives
- Got successive green builds :)
- Retries as exponential
- Adding retries is super clean using decorators
- We can actually define the types of Requests errors to retry

**Comment by gdemonet** [comment]
Retrying is easy in Python:

```python
while not condition:
    try:
        do_request()
    except ExpectedException:
        pass
    condition = eval_condition()
```

`litl/backoff` seems to provide more flexibility in those retries - but our issue at hand is not that simple linear retries are not sufficient, it's that we don't retry at all.

Also, as suggested in the "implementation proposal", we can already allow retries with `requests`, and underlying `urllib3.util.retry.Retry` is quite powerful, also enabling some form of backoff.

---

However, retrying here shouldn't be necessary, especially since we've been checking that Pods are Running. If we do it, we must make sure to not allow too many retries (that would let a really unstable / broken cluster pass these tests, which is not desirable).
