### ISSUE TITLE
Tooling should abort upgrade if some nodes are not in ready state

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#2237]
**Component**:

'salt', 'upgrade'

**What happened**:

When trying to upgrade a cluster when some nodes were not in ready state, it failed with the following error:

```
[WARNING ] org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[ERROR   ] The object is still present after 10 check attempts
bootstrap.novalocal_master:
----------
          ID: Delete old nginx ingress daemon set
    Function: metalk8s_kubernetes.object_absent
        Name: nginx-ingress-controller
      Result: False
     Comment: The object is still present after 10 check attempts
     Started: 18:02:42.207255
    Duration: 100887.686 ms
     Changes:
----------
```

**What was expected**:

The upgrade script should have warn the user, during the dryrun that the upgrade would fail because of some nodes in the cluster are not ready. I think this should also appear in the doc, as a pre requisite for Upgrade (i.e. making sure all nodes are in Ready state)

**Steps to reproduce**

DO: Spawn a cluster with several nodes
DO: shutdown one or few nodes
DO: Launch upgrade script in dryrun mode
OBSERVE: everything is successful and administrator think he can launch upgrade
EXPECT: a clear message should say that upgrade will fail because some nodes are not in ready state
DO: launch the upgrade
OBSERVE: upgrade is failing when trying to `Delete old nginx ingress daemon set`
EXPECT: upgrade should fail earlier saying some nodes are not in ready state

**Resolution proposal** (optional):

**Comment by gdemonet** [comment]
Fixed by #2903 (0ced4dd)
