### ISSUE TITLE
No seccomp support

### ISSUE THREAD

**Issue by samcv** [scality/metalk8s#2259]
**Component**:

**What happened**:
When attempting to use Kubernetes dashboard, I get the error: `feb 26 08:08:21 worker-3 kubelet[1500]: E0226 08:08:21.242021    1500 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to generate seccomp spec opts: seccomp is not supported` which shows up in my journal

**What was expected**:
For the pod to start.
**Steps to reproduce**
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-rc5/aio/deploy/recommended.yaml
**Resolution proposal** (optional):
Support seccomp. I am not sure but I think containerd needs to be compiled with seccomp support (just guessing)

**Comment by NicolasT** [comment]
Indeed, the `containerd` package as distributed in EPEL (which is the one we install) is not compiled with `seccomp` support. Adding this would require us to ship our own build of `containerd`, which would require quite a bit of work.

Meanwhile, you could remove the `seccomp`-related annotation from the dashboard *Deployment* *PodSpec* and get it to run.

**Comment by samcv** [comment]
Would it be appropriate to get them to include it? Or is there a reason 
you think it is not included?

**Comment by NicolasT** [comment]
> Would it be appropriate to get them to include it? Or is there a reason you think it is not included?

I never tried, to be honest. One reason why it's not included could be if the version of `libseccomp` that ships with RHEL7 is too old.

Anyway, the version of `containerd` as shipped in EPEL is somewhat old as well, so building our own could make sense. We'll need to look into it: given the age of RHEL7, packaging Go applications is... _not trivial_.

**Comment by NicolasT** [comment]
I built a `containerd` 1.2.13 RPM with `seccomp` enabled, and after deploying it (manually) to one node in my test-cluster, I can deploy the upstream dashboard manifest (slightly changing the manifest to ensure the `dashboard-metrics-server` gets scheduled on this one node) and everything seems to work.

I'll spend some time to integrate this in the project.
