### ISSUE TITLE
Add salt module unit test

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#2266]
**Component**:

'tests', 'salt'

**Why this is needed**:

Currently we didn't do any test for salt custom module and states

**What should be done**:

Add unit test for salt module (when it's possible).
This test should run in pre-merge like all other unit tests

**Implementation proposal** (strongly recommended):

https://docs.saltstack.com/en/master/topics/development/tests/unit.html

**Comment by alexandre-allard** [comment]
Closing this one as we now have 100% coverage on Salt execution modules.
