### ISSUE TITLE
Provide a UI interface for configuring the Dex backend connector integration.

### ISSUE THREAD

**Issue by Ebaneck** [scality/metalk8s#2269]
**Component**:

'ui'

**Why this is needed**:

To ease usability, from the MetalK8s UI, admin users should be able to configure at any time their OIDC connector of choice.

**What should be done**:

Provide a UI interface for configuring the Dex-LDAP connector integration.
We should ideally support LDAP, Active Directory and debatably the Dex static user store.

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by thomasdanan** [comment]
We don't need it for now and we will probably don't need it in the future
