### ISSUE TITLE
Provide documentation on how to configure Dex connectors from the MetalK8s UI

### ISSUE THREAD

**Issue by Ebaneck** [scality/metalk8s#2270]
**Component**:

'ui'

**Why this is needed**:

Cluster admins need to have validated and working document that explains how to configure any given Dex connector(LDAP, AD, ...) .

**What should be done**:

In the Operational Guide, document the sequence of steps with UI images on how to perform these operations

**Implementation proposal** (strongly recommended):

**Test plan**:

Epic #1996

**Comment by thomasdanan** [comment]
We don't need it for now and we will probably don't need it in the future
