### ISSUE TITLE
Provide documentation on how to configure Alertmanager notification from the MetalK8s UI

### ISSUE THREAD

**Issue by Ebaneck** [scality/metalk8s#2272]
**Component**:

'ui'

**Why this is needed**:

Admins need to have validated and working documentation that explains how to configure Alertmanger notifications.

**What should be done**:

Provide working documentation that explains how to perform this operation from the MetalK8s UI

**Implementation proposal** (strongly recommended):

**Test plan**:

Epic #1996

**Comment by thomasdanan** [comment]
closing this one as it should be included in https://github.com/scality/metalk8s/issues/2271
