### ISSUE TITLE
Rewrite Solutions Management (Salt + CLI)

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#2277]
**Component**: salt, scripts

**Why this is needed**:
To implement various changes on how we handle Solutions such as:
  - Remove Environment CRD and replace it by Namespace label (`solutions.metalk8s.scality.com/environment=<environment_name>`)
  - Rework configuration of Operators (need to have some config file, not just env var)
  - Rework configuration of Admin UI (similar to operator, to know which repositories exist for a Solution)
  - Expose available versions to Admin UIs through ConfigMap

**What should be done**:
The previous approach relied on some custom state management, where Salt uses a ConfigMap to store a list of available Solution versions, to compare with the desired state configured in /etc/metalk8s/solutions.yaml.

- Rework configuration file format to let users declare which Solution versions are active (meaning, their Admin UIs / CRDs should be deployed)
- Rework ext_pillar metalk8s:solutions to list available Solutions in the cluster, based on simple observations (active mounts, existing UI Service objects in metalk8s-solutions Namespace...) of the actual state, instead of the ConfigMap used before
- Use a single formula (metalk8s.solutions.available) to (un)mount archives and (un)configure the cluster OCI registry
- Use a single orchestrate (metalk8s.orchestrate.solutions.deploy-components) to (un)deploy Solution components (Admin UI, CRDs)

**Implementation proposal** (strongly recommended):
We need to follow what's inside the Solutions architecture document  https://metal-k8s.readthedocs.io/en/latest/developer/architecture/solutions.html (not yet merged, but can be found as a PR at https://github.com/scality/metalk8s/pull/2246)

**Test plan**:
Manual for now, through the CLI (import and deploy the solution example, create env then populate the env), but we need to add post-merge tests very soon.

**Comment by gdemonet** [comment]
Closed by #2279
