### ISSUE TITLE
Implement high-performance mail server like mailgun or sendgrid as part of setup

### ISSUE THREAD

**Issue by virtuman** [scality/metalk8s#229]
Generally, most of the components need to send out emails. I would highly recommend an opensource version of services like SendGrid or MailGun to be optionally installable along with metal-k8s. I really like this version of it:
https://github.com/atech/postal

**Comment by NicolasT** [comment]
@virtuman Which components are you referring to? The only one I can think of is AlertManager, for which we first need to figure out a story w.r.t. how to configure it. The rate of e-mails AlertManager sends is, however, supposed to be rather low.

When referring to other applications, I'd say it's up to the application deployment to set up such service when needed, instead of providing it as a cluster service?

**Comment by virtuman** [comment]
I would highly encourage to look at any of the systems like sendgrid and mailgun. It really is a completely different level of email-server. The open source project mentioned in the ticket is pretty much a clone. It is basically a combo of SMTP / API endpoints for sending mail out, but it comes with an insanely useful UI and DNS instructions. I'd say it's an infrastructure solution that should be used by anything that is installed on any type of deployment (ie. bare metal, kubernetes, etc) and it gives visibility into what was sent out, delivered, received, opened, with settings that help you avoid spam filters, rate limiting, production vs development environments. it also supports return mail. 

Basically any deployment needs to send out emails nowadays. With the concept of 1 service per container in mind - it is not recommended to include mail server inside of your container. This system is like a ferrari of mail systems that is open-sourced. Through the UI you would configure access for each consumer/project/deployment/environment individually, within a super helpful UI. Granted that there're other cloud based paid services that someone would rather use, although - i really don't see why and this solution is by far easier and better and guides you through all the intricacies of setting up SPF, DKIM, etc. - stuff that most people don't have a clue about how to set this up correctly.

I'd say it should be available at least as the Optional install. It saves me so much headache on a daily basis in our deployments that I think everyone should use it. We also use it to troubleshoot customer service issues and email-related activity (ie. customer says he hasn't received the email, i can quickly check it from the UI and re-send if necessary)

**Comment by NicolasT** [comment]
This indeed looks like an interesting project, however this is too high-level and workload/application-specific to include in MetalK8s as-is.

If there would exist a Helm chart for `postal`, it'd be trivial to deploy it on any Kubernetes cluster (including MetalK8s), or even depend on it from other charts.

Similar to how we won't integrate `postal` (~ SES) in MetalK8s, we're not deploying Zenko (~ S3), Kafka (~ SQS), MongoDB (~ DynamoDB), OpenFAAS/Fission/... (~ Lambda) as part of the stack either: this is the responsibility of higher-level, application-specific installation mechanisms/procedures.
