### ISSUE TITLE
Add tests to ensure that update operations on service configs are propagated to the underlying service

### ISSUE THREAD

**Issue by Ebaneck** [scality/metalk8s#2292]
**Component**:

'tests', 'kubernetes'

**Why this is needed**:

We need to be able to assert that any configuration changes on a Cluster and Service configuration is picked-up by the underline service

**What should be done**:

- Edit a ConfigMap containing service configurations e.g metalk8s-dex-config
- Bump the replica count to say (3) replicas
- Run the salt state to apply the changes to the deployment and maybe restart the deployment
- Check and verify that 3 replicas of the Dex pod exist within your cluster

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by gdemonet** [comment]
> Run the salt state to apply the changes to the deployment and maybe restart the deployment

We should not need to restart anything, that's the responsibility of Salt.

> Check and verify that 3 replicas of the Dex pod exist within your cluster

No, don't look at the Pod, look at the actual object that will be updated: the Deployment `dex` in `metalk8s-auth` namespace.
