### ISSUE TITLE
Example of resource customization for elasticsearch deployment?

### ISSUE THREAD

**Issue by virtuman** [scality/metalk8s#230]
Is there a way to customize elasticsearch resource assignment such as disk space, ram, cpu, heapsize ? or is it expected to be manually updated after the metal-k8s install script is done running?

I guess I just can't figure out if there's a way to override /files/*.yml files

Thank you.

**Comment by Zempashi** [comment]
We plan to provide customization of helm charts (like providing a value file that override defaults of the chart it-self and default of MetalK8s). But sadly, right now, you need to edit `roles/cluster_logging/files/elasticsearch/value.yml`. Yet, we plan for starting soon this feature.

**Comment by NicolasT** [comment]
'Custom' Helm values support was added for `nginx-ingress` and documented at https://metal-k8s.readthedocs.io/en/latest/usage/advanced_configuration.html (see #291). The related change for Elasticsearch and some other charts we deploy are pending (see e.g. #340, #346).

**Comment by NicolasT** [comment]
The ES changes landed. However, please be aware we may slightly change the 'var' naming before 1.1 is released.

Does this suit your need, @virtuman?

**Comment by thomasdanan** [comment]
won't do, since we are not shipping Elasticsearch anymore in metal2.X
