### ISSUE TITLE
Enhance Solutions documentation

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#2309]
**Component**: documentation

**Why this is needed**:
Some changes have been done in Solutions Management, we need to reflect theses changes in the documentation.

**What should be done**:
* Update the user documentation to explain step by step how to fully deploy a Solution
* Update the developer documentation (StorageClasses, upgrade/downgrade, ...)

**Implementation proposal** (strongly recommended): n/a

**Test plan**: n/a

**Comment by gdemonet** [comment]
> step by step how to fully deploy a Solution

Let's keep it simple for now, we are not 100% sure the current method will stay the same over time. Let's focus on straightforward, add-only (import, deploy, upgrade) tasks, nothing destructive (remove from Env, unmount/remove ISO).

**Comment by alexandre-allard** [comment]
closed by #2317
