### ISSUE TITLE
cluster expansion is falling if yum-utils is not installed

### ISSUE THREAD

**Issue by xaf-scality** [scality/metalk8s#2334]
**Component**:
salt

**What happened**:
adding a new node to a cluster is failling, because repoquery tools is needed on the target node

**What was expected**:
not failling

**Steps to reproduce**
expand a cluster with a node not having repoquery (yum-utils rpm)

**Resolution proposal** (optional):
provide yum-utils in the iso or check it and install it if needed

**Comment by alexandre-allard** [comment]
closed by #2343
