### ISSUE TITLE
Upgrade the deployed solutions from UI

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2337]
**Component**: ui, solutions

**Why this is needed**:

Currently, in order to upgrade the deployed solutions the only way we have is to click on the `add` button and fill in the form with the new version, which is counter-intuitive.

**What should be done**:
We should be able to upgrade the solutions by a dedicate button `edit` or `upgrade` button ( in the future we may need a button to redirect to the solution UI)

**Implementation proposal** (strongly recommended):

There are two probable proposals:
**1) Expandable row table**

![image](https://user-images.githubusercontent.com/18453133/77959287-9f55f580-72d6-11ea-9e32-ec1664fd71c8.png)

- Pros: Centralized the information for Environment.

- Cons: We need to include the development cost for the Table component. Currently, we don't support the expandable row table, so we need first implement it in core-ui. 
Implement detail of the table: We should be able to dynamically change the rowHeight of the table
（https://github.com/bvaughn/react-virtualized/blob/master/docs/CellMeasurer.md）

**2) Redirect to the environment detail page by clicking on the specific environment in the Environment List**

![image](https://user-images.githubusercontent.com/18453133/78009338-2d66c600-7341-11ea-957b-40196619826b.png)

- Pros: Easier to implement and have more space to display more environment detail( e.g. a link redirect to the solution UI...)
- Cons: A new page without enough information, I mean, the content is very few.

Requirements:
1. Be able to click on the row when there is a deployed version.
2. `Upgrade` & `Downgrade` button should appear only if there are some available versions to upgrade / downgrade.

**Test plan**:
TBD

**Comment by thomasdanan** [comment]
@ChengYanJin I vote for option2.
prefer `upgrade` than `upgrade the solution`
What about downgrade action? how to achieve it?
Also those actions should appear only if there are some available versions to upgrade / downgrade to

**Comment by ChengYanJin** [comment]
Hello @thomasdanan,
For downgrade, I would like to do the same way as `upgrade`.  When I click on the button, it will pop up a modal includes a dropdown with all the available upgrade or downgrade versions.

I would like to raise another question. 
The current URL for solution page is `http://localhost:3000/solutions`
Does it make sense to change to `http://localhost:3000/environments`?
So when we go to a specific environment, the URL would be `http://localhost:3000/environments/dev`

Same as the breadcrumb does it make sense as shown in the screenshot?
