### ISSUE TITLE
Base on UI service to check if the solution is deployed

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2338]
**Component**: ui, solutions 

**Why this is needed**:
We should check if we have the UI and solution service deployed instead of checking the deployment

**What should be done**:
```
export async function getUIServices(namespace) {
  try {
    return await coreV1.listNamespacedService(
      namespace,
      null, // pretty
      null, // allowWatchBookmarks
      null, // _continue
      null, // fieldSelector
      `${LABEL_K8S_COMPONENT}=ui`, // labelSelector
    );
  } catch (error) {
    return { error };
  }
}
```

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by ChengYanJin** [comment]
Not sure if it's still a valid issue anymore...

**Comment by thomasdanan** [comment]
UI is not deployed anymore by solution framework. losing the issue
