### ISSUE TITLE
Alerting screen is displayed before Login page

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#2353]
**Component**:

'ui'

**What happened**:

Actually, when you launch the MetalK8s UI you are landing on the Alerting page and after few seconds you are redirected to the login page

**What was expected**:

I would think you should see nothing until you are properly logged in

**Comment by gdemonet** [comment]
It's a saga ordering issue. Not a single external call should be made until we retrieve a token from local storage (cc @ChengYanJin).

**Comment by ChengYanJin** [comment]
Hello @gdemonet,
You are right! I guess the order of saga is one problem, we could simply 
```
export default function* rootSaga() {
  yield all(
    [fork(authenticateSaga), fork(configSaga)],
    yield all([
      fork(layoutSaga),
      fork(monitoringSaga),
      fork(nodesSaga),
      fork(podsSaga),
      fork(saltSaga),
      fork(solutionsSaga),
      fork(volumesSaga),
    ]),
  );
}
```
IMO, there is another issue, even though we'll change the order of saga to make sure others sagas will be called after the `authenticateSaga` and `configSaga` are done, when we launch the app without login, we could still see the UI framework (with the sidebar) 

I would expect that I can't see anything else only the Scality logo on the navbar?
