### ISSUE TITLE
Allow Solution Operator to provide a role manifest

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#2389]
**Component**: solutions, salt

**Why this is needed**:
We can't guess what roles a Solution operator will need, so we need to add a mechanism for it to provide them.

**What should be done**:
Deploy role manifest if there is any under `operator/role.yaml` in a Solution archive, when we add the Solution into an Environment. If there is no role.yaml, we must fallback on default roles (as it's done now).
We also need to remove the `customApiGroups` entry from the `config.yaml`, as this functionnality is no longer needed with this change.

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by alexandre-allard-scality** [comment]
Done in #2576

**Comment by alexandre-allard** [comment]
Done in #2576
