### ISSUE TITLE
Extend the ESLint config for React App

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2400]
**Component**: UI

**Why this is needed**:
Currently, we only have the `react` ESLintConfig extend, which is not enough.

```
  "eslintConfig": {
    "extends": "react-app"
  },
```

For ESLint, No rules are enabled by default. We should at least enable the  "extends": "eslint:recommended" property in a configuration file enables rules that report common problems.
(https://eslint.org/docs/rules/)

Otherwise, for the following code, we won't display any error: `Arrow function should not return assignment  no-return-assign`
```
    const availableDeployingSolution = availableSolutions?.find(
      (avaSol) => avaSol.name === solName,
    );
```

**What should be done**:
Enable the  "extends": "eslint:recommended" property in a configuration file.

**Implementation proposal** (strongly recommended):
TBD
**Test plan**:
TED

**Comment by slaperche-scality** [comment]
> Otherwise, for the following code, we won't display any error: Arrow function should not return assignment no-return-assign

Note that `no-return-assign` is not enabled by `"extends": "eslint:recommended"`

But yeah, `"extends": "eslint:recommended"` is a good start, and then we can able a few more (like `no-return-assign` which has proven useful).

**Comment by MonPote** [comment]
Good suggestion, I think we should combine the rules.
You can enable several extensions with an array.
You can also add rules like bellow.
```
"extends": ["react-app", "eslint:recommended"],
"rules": {
"no-return-assign": "except-parens"
}
```
