### ISSUE TITLE
Upgrade nginx-ingress-controller to 0.27.0+

### ISSUE THREAD

**Issue by marcboivin** [scality/metalk8s#2423]
**Component**:

nginx-ingress

**What happened**:
On older hardware sse42 is not available. Up until nginx-ingress 0.26.* this was an issue that made it impossible to boot nginx-ingress-controller. It will dump and fail. 

Here is a link to the relevant issue https://github.com/kubernetes/ingress-nginx/issues/4311

**What was expected**:

It shouldn't dump and fail

**Steps to reproduce**

Install Metalk8s on processor that doesn't support sse4.2

**Resolution proposal** (optional):

Upgrade nginx-ingress to at least 0.27.0 or more

**Comment by gdemonet** [comment]
Thanks @marcboivin for notifying us of this! We will make sure to update this in `2.5.1` and higher.

**Comment by gdemonet** [comment]
Fixed by #2446 (will be included in [2.5.1](https://github.com/scality/metalk8s/milestone/24) release)
