### ISSUE TITLE
Monitoring Table can't display all the Alerts

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2495]
**Component**: ui 

**What happened**:
When the number of alerts is more than the capacity of the table, we can't scroll down to check the last few alerts.
![image](https://user-images.githubusercontent.com/18453133/80455522-33de6280-892c-11ea-9a3b-54be00fc2720.png)

**What was expected**:
We can scroll down until the end of the table.

**Steps to reproduce**
I was trying with dev/2.6, but we have the same issue in 2.5 branch
There are many ways to create many alerts. What I did is to create many new Nodes but without deploying them and wait 15mins. 

**Resolution proposal** (optional):
The height problem of the table.

**Comment by gdemonet** [comment]
@ChengYanJin this can be closed I guess?

**Comment by ChengYanJin** [comment]
Merged in PR #2503
