### ISSUE TITLE
Volume page - Performance charts

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2507]
**Component**:
ui

**Why this is needed**:
These charts provide us an intuitive way to check the performance of a specific volume.

**What should be done**:
We should get the data through Prometheus API and display it in the sparkline chart.

**Implementation proposal** (strongly recommended):
@thomasdanan will provide a more precise graph from Grafana. 

![image](https://user-images.githubusercontent.com/18453133/80733814-7f506680-8b0e-11ea-95aa-b7062012edd9.png)

Got inspiration from the Grafana dashboard. 
![Untitled](https://user-images.githubusercontent.com/18453133/84632942-f770c100-aeef-11ea-9cf4-40c1336c2368.png)

The difficulties facing in these performance charts:
- [vega-lite] How to add the label with the conversion from bytes to the units
- [prometheus] Need to figure out which metric we could use for the KPI`IOPS`.

We should properly handle the **downtime** of the machine
when there is no data we shouldn't display anything
![image](https://user-images.githubusercontent.com/18453133/86479045-aebc6300-bd4b-11ea-87f8-d4782c5aa7e3.png)

**Test plan**:
TBD

**Comment by leeoniya** [comment]
may be of interest: https://github.com/leeoniya/uPlot

**Comment by gdemonet** [comment]
Thanks for sharing your project @leeoniya :) Unfortunately, we're already building a simplified components library on top of Vega(Lite) - see [scality/core-ui](https://github.com/scality/core-ui) - and focus more on having a clear interoperable language for defining graphs than on performance (for this, we use Grafana :wink:, maybe they should use uPlot?).

**Comment by leeoniya** [comment]
i'm told it's in the works ;)

https://github.com/grafana/grafana/pull/21835
https://news.ycombinator.com/item?id=23228327
