### ISSUE TITLE
MetalK8s UI access token should be refreshed automatically

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2527]
**Component**:
ui, authentication 

**What happened**:
Given I already login to MetalK8s, serval seconds/mins after I am redirected to the Dex login page again.

**What was expected**:
The access token should be renewed automatically.

**Steps to reproduce**
We need further investigation when the automatic logout would happen. It's not super clear what's the root issue.

**Resolution proposal** (optional):
Should worth to investigate if the `silent renewal` works correctly in `redex-oidc`

**Comment by gdemonet** [comment]
@ChengYanJin do we have more info on this topic?

**Comment by JBWatenbergScality** [comment]
Closed by #3110
