### ISSUE TITLE
Add python and yaml linter step into the ci

### ISSUE THREAD

**Issue by alxf** [scality/metalk8s#258]
We should have a step to lint our python and yaml files in the ci.

**Comment by thomasdanan** [comment]
AFAIK it is implemented in metalk8s 2.X: https://github.com/scality/metalk8s/blob/development/2.6/buildchain/buildchain/lint.py
closing the issue

**Comment by slaperche-scality** [comment]
yes and no.
We do lint all our YAML files I think.
But for Python, only the buildchain code is linted, not the Salt code.

**Comment by gdemonet** [comment]
Let's say this ticket is done (we run a linting stage in CI), but we still need #2649 as @slaperche-scality pointed out.
