### ISSUE TITLE
Change current post-merge behavior

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#2624]
**Component**:

'ci'

**Why this is needed**:

Right now, in post-merge, if for whatever reason build of example solution or build of previous metalk8s version fail we do not run any other tests

**What should be done**:

We should change the post-merge to split in logical stages so that we launch in parallel the step that can be parallelized (e.g.: To test bootstrap-restore we do not need to have example solution or previous branch version build)

**Implementation proposal** (strongly recommended):

So right now we can split like this

In parallel:
- Solution tests (that will first build example solution and then launch solution tests)
- Previous development tests (that will first build prev and then launch upgrade/downgrade tests)
- single-node-upgrade-patch-centos
- single-node-downgrade-patch-centos
- bootstrap-restore

**Comment by gdemonet** [comment]
@alexandre-allard-scality can we close this?

**Comment by alexandre-allard** [comment]
Oh yes, didn't know there was a ticket to track this... so I didn't put the reference in the PR and the commits related to this.

**Comment by alexandre-allard** [comment]
Done in #2627
