### ISSUE TITLE
Configure the node-exporter to get the metrics for partitioned disk

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2631]
**Component**:

**Why this is needed**:
I would like to get the `IOPS/Throughput/Latency` for a specific `Volume`. But the metrics expose by Prometheus are the whole disk(device) before the partition.

After the job done by #2615 I could be able to get the device name from `Volume status.`

**What should be done**:
Configure the node-exporter to expose the metric for the partitioned disk.

**Implementation proposal** (strongly recommended):

A workaround could be:
1. `kubectl get -n metalk8s-monitoring daemonset`
2. Edit `kubectl edit -n metalk8s-monitoring daemonset prometheus-operator-prometheus-node-exporter`
3. ` --collector.diskstats.ignored-devices="^(ram|fd|(h|s|v|xv)d[a-z]|nvme\\d+n\\d+p)$":`

Update the regexp:
 ` --collector.diskstats.ignored-devices="^(ram|fd)\d+$"`

**Test plan**:
TBD

**Comment by slaperche-scality** [comment]
We may also want to export loop device (for `SparseLoopDevice`, even though we're not supposed to use them in prod)

**Comment by gdemonet** [comment]
Currently, `node-exporter` uses its default value for selection of devices to gather diskstats from. The default regexp for ignored devices is the following (as found [here](https://github.com/prometheus/node_exporter/blob/master/collector/diskstats_linux.go#L39)):

```
^(ram|loop|fd|(h|s|v|xv)d[a-z]|nvme\\d+n\\d+p)\\d+$
```

A solution could be to use `--collector.diskstats.ignored-devices="^(ram|fd|nvme\\d+n\\d+p)\\d+$"` as a command-line flag passed to `node-exporter` (in its DaemonSet PodTemplate).

One would need to make sure extending the set of collected devices will not break / make unreadable the Grafana charts that use this metric.

**Comment by gdemonet** [comment]
So, I'm not sure how `node-exporter` works, but even after changing the regexp to `^(ram|fd)\\d+$` I have no stat for `loopX` devices :/
It seems there is no metric at all in `/proc/diskstats` about loop devices.

_Edit: actually, there are some stats, but all set to 0, and apparently filtered out from Grafana dashboards_

**Comment by deeruattavar** [comment]
Above changes not working -   ^(ram|fd)\\d+$

Still I am unable to loop all partitions .. even I can see see some replication values for all disk partitions.

Can anybody suggest me the better approaches o view all disk partitions utilization with in cluster...

**Comment by NicolasT** [comment]
> Above changes not working - ^(ram|fd)\d+$
> 
> Still I am unable to loop all partitions .. even I can see see some replication values for all disk partitions.
> 
> Can anybody suggest me the better approaches o view all disk partitions utilization with in cluster...

Given the comment in https://github.com/scality/metalk8s/issues/2631#issuecomment-670373449, it appears not every block device shows up in `/proc/diskstats` (or there are 0-valued stats). Since this is where `node-exporter` gets its data, there's not much it can do.

**Comment by deeruattavar** [comment]
@NicolasT Thanks a lot for your immediate response.

I have following partitions in my cluster :
df -kh
/dev/mapper/centos-root   50G   38G   13G  76% /
/dev/sda1               1014M  266M  749M  27% /boot1
/dev/sda2               100G     10G     90G    10% /boot2
**/dev/mapper/centos-home  839G  150G  690G  18% /home**

In that I can get disk utilization value  for highlighted partitions.. Rest of the partitions value is remine same as highlighted partitions.

I have done following configuration for **node-exporter** images 
containers:
        - name: node-exporter
          image:  node-exporter:latest
          securityContext:
            privileged: true
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.diskstats.ignored-devices=^(ram|fd)\\d+$
            - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)
            - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
            - --collector.netclass.ignored-devices=^(veth.*)$

 can you help me to resolve this issue? Any Alternative solution ? @gdemone

**Comment by NicolasT** [comment]
@deeruattavar Is this an issue you're facing within a MetalK8s cluster, or an issue with `node-exporter`? If the latter, you better ask for help in the Prometheus/`node-exporter` community...

If it's within a MetalK8s cluster, we'll need some more details: how do you check whether you can get disk utilization of those other partitions? What are the exact metrics Prometheus exposes w.r.t. disk consumption?...
