### ISSUE TITLE
Storage Operator can use SaltAPI without RBAC in 2.5

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#2634]
**Component**: salt

**What happened**:

When implementing #2625, we found that forgetting the permission for a newly added Salt execution function (namely, `metalk8s_volumes.device_name`) didn't prevent `storage-operator` from using it, which is a serious security hole.
This appeared in 2.5.1-dev, whereas the RBAC was properly enforced in 2.6.0-dev.

**What was expected**:

Without the relevant permissions, one shouldn't be able to use SaltAPI freely.
If there is a hole in our setup in 2.5 around RBAC with Salt(API), we need it fixed ASAP.

**Steps to reproduce**: TBD

**Resolution proposal** (optional): TBD (we need a reproducing example, and tests to ensure this behaviour is fixed)

**Comment by gdemonet** [comment]
First observation: in `salt/_auth/kubernetes_rbac.py`, the `auth` method is not checking that the username provided matches the ServiceAccount for which the token was issued. That in itself is a security hole (cc @NicolasT)

**Comment by NicolasT** [comment]
There's no difference in the eauth code between 2.5 and 2.6, so it's odd as to why it worked in 2.5 and not 2.6.

**Comment by NicolasT** [comment]
Actually not sure there's something wrong here. When looking at `storage-operator/deploy/role.yaml`, the `storage-operator` `ClusterRole` allows create/delete/get/list/patch/update/watch on `node` objects. As such, it's deemed to be part of the Salt `node-admins` group (which requires `*` on `nodes` in K8s, see the eauth code).

This `node-admins`  group can un `.*` on `*` (see `salt/metalk8s/salt/master/files/master-99-metallk8s.conf.j2`).

So everything works as designed (except that maybe the `storage-operator` should *not* have `*` rights on `node` objects, of course!)

**Comment by NicolasT** [comment]
> First observation: in `salt/_auth/kubernetes_rbac.py`, the `auth` method is not checking that the username provided matches the ServiceAccount for which the token was issued. That in itself is a security hole (cc @NicolasT)

This is indeed a bug and needs to be fixed.

**Comment by NicolasT** [comment]
Seems introduced in 56eda6d12c02082a14a864b97266ec9623011d6c @slaperche-scality. Giving the `storage-operator` role access to `nodes` gives it `node-admins` permissions in Salt.

**Comment by NicolasT** [comment]
Actually, in 2.6 the `*` verbs on `nodes` was turned into CRUDLPW, hence the `storage-operator` account getting `node-admins` in Salt in 2.5 but no longer in 2.6.

Now, `storage-operator` shouldnt have CRUDLPW on Node (I think) in the first place (plus a whole bunch of other rights in the `ClusterRole` for it it doesn't really need).

**Comment by slaperche-scality** [comment]
> Now, `storage-operator` shouldnt have CRUDLPW on Node (I think) in the first place (plus a whole bunch of other rights in the `ClusterRole` for it it doesn't really need).

Yup, see https://github.com/scality/metalk8s/issues/2084

**Comment by slaperche-scality** [comment]
> Giving the `storage-operator` role access to `nodes` gives it `node-admins` permissions in Salt.

That's really a weird side-effect, I've totally missed it :/

**Comment by gdemonet** [comment]
> That's really a weird side-effect

I can't agree more. Could we imagine building another RBAC model for Salt in K8s? I'm thinking, just as an example, we could create dummy objects (empty ConfigMaps) in some `metalk8s-salt` namespace, and use the SubjectAccessReviews to control which "groups" (in Salt world) a user belongs to.

An example `Role` could then be:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: metalk8s-salt
  name: salt-admin
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - salt-rbac-admin
  verbs:
  - get
```

If we really wanted to (not sure though), we could even use the contents of these ConfigMaps as a source for templating the RBAC rules in the Salt master configuration.

**Comment by gdemonet** [comment]
> Could we imagine building another RBAC model for Salt in K8s?

Another idea: when using the `TokenReview` API (which only supports Bearer tokens, not Basic), we can get all the groups this user is in (under `status.user.groups`). Not entirely sure how, but we could try to use those.

**Comment by NicolasT** [comment]
> > Could we imagine building another RBAC model for Salt in K8s?
> 
> Another idea: when using the `TokenReview` API (which only supports Bearer tokens, not Basic), we can get all the groups this user is in (under `status.user.groups`). Not entirely sure how, but we could try to use those.

We can't, I believe, and shouldn't:

- A `ServiceAccount` token will likely not have any groups defined here.
- This would require to configure *Salt* with intel about the *groups* a *human user* may be part of in the directory service of the *customer*, which is 'meh'. Also, would depend on Dex groups support (which, granted, we may have).

**Comment by gdemonet** [comment]
Mmh right, ServiceAccounts only have `system:` groups, like `system:serviceaccounts:<namespace>` or `system:authenticated`. Good point. So WDYT about synthetic objects we could use to perform SubjectAccessReviews?
