### ISSUE TITLE
Missing field for Volume page

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2641]
**Component**: ui, volumes

**Why this is needed**:
What we are missing for volume page

The `storageClass` field which is interesting to be used to filter the volume list. 

**What should be done**:
Add a new column in the volume table

**Implementation proposal** (strongly recommended):

**Test plan**:
TBD

**Comment by thomasdanan** [comment]
@ChengYanJin after discussing with @xaf-scality, we think it is not crucial to have this column and ability to sort/filter per storage class. Closing the issue for now.
