### ISSUE TITLE
Replace various metalk8s-* storageclass by a single metalk8s one

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#2742]
**Component**: salt, addons, docs

**Why this is needed**:
Today we have 1 metalk8s-prometheus (prometheus & alertmanager) and 1 metalk8s-loki (loki & fluent-bit) storageclass, but it does not make sense as the storageclass name must not be used to define the purpose of it.
Moreover, these class are exactly the same, so there is no point of keeping both.

**What should be done**:
Replace `metalk8s-prometheus` and `metalk8s-loki` storageclass everywhere by a `metalk8s` one.

**Implementation proposal** (strongly recommended):
Should be updated in examples, docs and salt

**Test plan**:
Tests should still work.

**Comment by TeddyAndrieux** [comment]
NOTE: Right now in Loki chart you cannot provide any selector for volume so for the moment we consider all volume with storage class `metalk8s-loki` as Loki volume check this commit message https://github.com/scality/metalk8s/commit/97cd2fffce4a10c5019fa60b9e77eba93e6f6f51
