### ISSUE TITLE
LVM deployment failure

### ISSUE THREAD

**Issue by tmacro** [scality/metalk8s#275]
When deploying a 5 node cluster on openstack, the following error occurs.

```
TASK [kube_lvm_storageclass : Setup MetalK8s StorageClass: Create StorageClass manifests] *********************************************************
fatal: [node-01]: FAILED! => {"msg": "'ansible.vars.hostvars.HostVarsVars object' has no attribute 'metalk8s_lvm_all_vgs'"}
fatal: [node-02]: FAILED! => {"msg": "'ansible.vars.hostvars.HostVarsVars object' has no attribute 'metalk8s_lvm_all_vgs'"}
```

this is the kube-node.yml for the deployment

```
metalk8s_lvm_default_vg: False
metalk8s_lvm_vgs: ['kubevg']
metalk8s_lvm_drives_kubevg: ['/dev/vdb']
metalk8s_lvm_lvs_kubevg:
  lv01:
    size: 52G
  lv02:
    size: 52G
  lv03:
    size: 52G
  lv04:
    size: 11G
  lv05:
    size: 11G
  lv06:
    size: 11G
  lv07:
    size: 5G
  lv08:
    size: 5G
```

These are fresh VMs and fresh attached volumes of 200GB per vm

**Comment by Zempashi** [comment]
Normally, `metalk8s_lvm_all_vgs` is computed here:

https://github.com/scality/metalk8s/blob/3e44dd986d82d0704877f5607c54fad16e4ee99d/roles/setup_lvm_vg/tasks/main.yml#L20,L35

and setup_lvm_vg is run on every nodes:
https://github.com/scality/metalk8s/blob/3e44dd986d82d0704877f5607c54fad16e4ee99d/playbooks/storage-pre.yml


Can you tell me if you see in the output logs the tasks "LVM Setup: Compute list of all vgs".

If you add '-e debug=True', you should also be able to see the value
https://github.com/scality/metalk8s/blob/3e44dd986d82d0704877f5607c54fad16e4ee99d/roles/setup_lvm_vg/tasks/main.yml#L37,L39
Can you attach here a sample of output to see the values ?

**Comment by NicolasT** [comment]
@tmacro Is this still an issue?

**Comment by tmacro** [comment]
I haven't seen it happen again

**Comment by Zempashi** [comment]
I though having the issue once: was a server that was failing before registering the variable
