### ISSUE TITLE
Figure out the Prometheus queries for Node Page

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2765]
**Component**:
ui, monitoring

**Why this is needed**:
We want to figure out the prometheus query for node page before implementing the code

**What should be done**:
The workflow of the graphs:

1. High-level spec & Design UI/UX are done
2. Find the equivalent graph in Grafana 
3. Ask the graph validation from PO
4. Get the queries used by Grafana
5. Adapt the queries to our use case
6. Try the queries to get data
7. Ask the queries validation from backend

Finally READY to implement the graph!!!

![image](https://user-images.githubusercontent.com/18453133/91564937-ae060e80-e941-11ea-80fa-640486112203.png)

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by slaperche-scality** [comment]
For what is worth, here are the queries I've used during the recent benchmarks for node's metrics:

Network:
- Transmitted: `sum(irate(node_network_transmit_bytes_total[5m])) by (instance)`
- Received: `sum(irate(node_network_receive_bytes_total[5m])) by (instance)`

Memory:
- Total: `sum(node_memory_MemTotal_bytes) by (instance)`
- Used: `sum(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes) by (instance)`
- Free: `sum(node_memory_MemFree_bytes) by (instance)`
- Shared: `sum(node_memory_Shmem_bytes) by (instance)`
- Cache+Buffer: `sum(node_memory_Cached_bytes + node_memory_Buffers_bytes) by (instance)`
- Available: `sum(node_memory_MemAvailable_bytes) by (instance)`
- Swap: `sum(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) by (instance)`

CPU:
- system: `sum (irate(node_cpu_seconds_total{mode="system"}[5m])) by (instance) * 100`
- user: `sum (irate(node_cpu_seconds_total{mode="user"}[5m])) by (instance) * 100`
- total: `sum (irate(node_cpu_seconds_total{mode=~"(user|system)"}[5m])) by (instance) * 100`
- iowait `sum (irate(node_cpu_seconds_total{mode="iowait"}[5m])) by (instance) * 100`
- IRQ: `sum (irate(node_cpu_seconds_total{mode=~".*irq"}[5m])) by (instance) * 100`
- others: `sum (irate(node_cpu_seconds_total{mode!~"(idle|user|system|iowait|.*irq)"}[5m])) by (instance) * 100`
- idle: `sum (irate(node_cpu_seconds_total{mode="idle"}[5m])) by (instance) * 100`

I/O:
- Read  IOPS: `sum(irate(node_disk_reads_completed_total{device=~".*nvme.*"}[5m])) by (instance, device)`
- Write IOPS: `sum(irate(node_disk_writes_completed_total{device=~".*nvme.*"}[5m])) by (instance, device)`
- Read bandwidth: `sum(irate(node_disk_read_bytes_total{device=~".*nvme.*"}[5m])) by (instance, device)`
- Write bandwidth: `sum(irate(node_disk_written_bytes_total{device=~".*nvme.*"}[5m])) by (instance, device)`

Some of them may be useless, some of them may be useful with a bit of tailoring.
But it can give you a starting point at least.

**Comment by ChengYanJin** [comment]
Thanks to the early investigation from @gdemonet, I got the graphs of metrics needed for **Node Page** from **Grafana** dashboard.

Please review if they are really what we want and provide advice for what we are missing today mainly for **IOPS**.

Thank you!

**CPU Usage**:
![image](https://user-images.githubusercontent.com/18453133/92152188-925ba600-ee22-11ea-832c-20111f2b1a96.png)

![image](https://user-images.githubusercontent.com/18453133/92152167-896ad480-ee22-11ea-9631-7d565b48f980.png)

Query Example from Grafana:
```
(((count(count(node_cpu_seconds_total{instance=~"192.168.1.18:9100",job=~"node-exporter"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~"192.168.1.18:9100",job=~"node-exporter"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~"192.168.1.18:9100",job=~"node-exporter"}) by (cpu))
```
The query we should use:
```
(((count(count(node_cpu_seconds_total{instance=~$"{instance}"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~"${instance}"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~"${instance}"}) by (cpu))
```

**System load**:
![image](https://user-images.githubusercontent.com/18453133/91709314-dd578e00-eb82-11ea-8b8e-420b79c4879b.png)
The average of 1 min (query example from Grafana)
```
node_load1{instance=~"192.168.1.18:9100",job=~"node-exporter"}
```

Average of 5 mins
```
node_load5{instance=~"192.168.1.18:9100",job=~"node-exporter"}
```

The query for **System load** should be:
```
node_load5{instance=~"${instance}"}
```

**Memory**: 
![image](https://user-images.githubusercontent.com/18453133/91709921-bcdc0380-eb83-11ea-8a34-0657016e581f.png)
In our node page, it will be a line chart instead of a Gauge.

![image](https://user-images.githubusercontent.com/18453133/92095944-9cf04e00-edd6-11ea-8189-8434a60ee453.png)

```
100 - ((node_memory_MemAvailable_bytes{instance=~"192.168.1.18:9100",job=~"node-exporter"} * 100) / node_memory_MemTotal_bytes{instance=~"192.168.1.18:9100",job=~"node-exporter"})
```
 
The query of **Memory** should be:
```
100 - ((node_memory_MemAvailable_bytes{instance=~"${instance}"} * 100) / node_memory_MemTotal_bytes{instance=~"${instance}"})
```


**IOPS**:
![image](https://user-images.githubusercontent.com/18453133/91710312-586d7400-eb84-11ea-84a2-011f41e14bb4.png)
> this graph is showing one line per disk, where we want to aggregate at the full Node-level, so may need to tweak the query a bit
```
irate(node_disk_reads_completed_total{instance=~"192.168.1.18:9100",job=~"node-exporter"}[5m])
```
```
irate(node_disk_writes_completed_total{instance=~"192.168.1.18:9100",job=~"node-exporter"}[5m])
```
solution: change the query to aggregate by instance

The queries for IOPS should be:
```
sum(irate(node_disk_reads_completed_total{instance=~"${instance}"}[5m])) by (instance)
```
```
sum(irate(node_disk_writes_completed_total{instance=~"${instance}"}[5m])) by (instance)
```

**Network Bandwidth**:
![image](https://user-images.githubusercontent.com/18453133/91711012-7687a400-eb85-11ea-8eec-fa126418a1ff.png)

The queries from Grafana.
```
irate(node_network_receive_bytes_total{instance=~"192.168.1.18:9100",job=~"node-exporter"}[5m])
```
```
irate(node_network_transmit_bytes_total{instance=~"192.168.1.18:9100",job=~"node-exporter"}[5m])
```


> We'll need to find a way to map "control plane"/"workload plane" to the right interface (likely eth1 or eth2 in scality cloud, but may be completely different in prod), today I don't know how we'll get it from the UI.

Issue solved: 
```
  saltApiClient.post('/', {
    client: 'local',
    tgt: '*',
    fun: 'grains.item',
    arg: ['metalk8s:control_plane_ip', 'metalk8s:workload_plane_ip', 'ip_interfaces'],
  })
```
```
{
  "return": [
    {
      "bootstrap": {
        "metalk8s:control_plane_ip": "192.168.1.18",
        "metalk8s:workload_plane_ip": "192.168.2.13",
        "ip_interfaces": {
          "cali52c723292f9": [
            "fe80::ecee:eeff:feee:eeee"
          ],
          "lo": [
            "127.0.0.1",
            "::1"
          ],
          "calif6639db6311": [
            "fe80::ecee:eeff:feee:eeee"
          ],
          "tunl0": [
            "10.233.132.64"
          ],
          "cali9e1eeb77dd1": [
            "fe80::ecee:eeff:feee:eeee"
          ],
          "cali926fdb019f0": [
            "fe80::ecee:eeff:feee:eeee"
          ],
          "eth2": [
            "192.168.2.13",
            "fe80::f816:3eff:fe38:39c"
          ],
          "eth1": [
            "192.168.1.18",
            "fe80::f816:3eff:fea0:64e5"
          ],
          "eth0": [
            "10.200.4.254",
            "fe80::f816:3eff:fe3e:d430"
          ]
        }
      },
    },
    ... ( with more Nodes in the array)
  ]
}
```

From Salt result above we can map the control plane/workload plane IP address to the right interface.

the result of the query is:
```
[
{
  "metric": {
    "device": "cali3969cf90816",
    "endpoint": "metrics",
    "instance": "192.168.1.18:9100",
    "job": "node-exporter",
    "namespace": "metalk8s-monitoring",
    "pod": "prometheus-operator-prometheus-node-exporter-tp5q6",
    "service": "prometheus-operator-prometheus-node-exporter"
  },
  "values": [
    [
      1599112772,
      "690.2"
    ],
  ...
  ]
},
... with more devices ( calif6639db6311, eth0, eth1, eth2, lo, tunl0) in the array
]
```

 Let's take Node **bootstrap** as an example:
According to the result of the Salt, we can find the Interface of `Control Plane` is `eth1`, the Interface of `Workload Plane` is `eth2`

So the queries for **Network Bandwidth** should be:
IN
```
irate(node_network_receive_bytes_total{instance=~"${instance}"}[5m])
```
OUT
```
irate(node_network_transmit_bytes_total{instance=~"instance"}[5m])
```


Addition to these,
we should have another tab that displays the metrics for **system devices** ( which are not used by Metalk8s Volume)


```
[centos@zenkotda-master-0 ~]$ lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vda    253:0    0   40G  0 disk 
`-vda1 253:1    0   40G  0 part /
vdb    253:16   0   10G  0 disk /var/lib/etcd
vdc    253:32   0  200G  0 disk /var/lib/metalk8s/storage/sparse
vdd    253:48   0   20G  0 disk /var/lib/kubelet/pods/226f9078-5d8e-43fe-be9d-9d039e30e729/volumes/kubernetes.io~local-volume/prom-m0-reldev
loop0    7:0    0   10G  0 loop /var/lib/kubelet/pods/b5e1a99c-9b77-4522-9a74-93de84af5d0d/volumes/kubernetes.io~local-volume/loki-vol
loop1    7:1    0    5G  0 loop /var/lib/kubelet/pods/ca3ef82b-3bc8-4575-b7a4-90df0e5d358a/volumes/kubernetes.io~local-volume/master-0-alertmanager
```

**Comment by thomasdanan** [comment]
> Thanks to the early investigation from @gdemonet, I got the graphs of metrics needed for **Node Page** from **Grafana** dashboard.
> 
> Please review if they are really what we want and provide advice for what we are missing today mainly for **IOPS**.
> 
> Thank you!
> 
> **CPU Usage**:
> ![image](https://user-images.githubusercontent.com/18453133/91709373-f3fde500-eb82-11ea-93b5-ceb241659a6e.png)
> Query Example from Grafana:
> 
> ```
> (
>   (1 - rate(node_cpu_seconds_total{job="node-exporter", mode="idle", instance="192.168.1.36:9100"}[$__interval]))
> / ignoring(cpu) group_left
>   count without (cpu)( node_cpu_seconds_total{job="node-exporter", mode="idle", instance="192.168.1.36:9100"})
> )
> ```
> 

I suggest we display CPU Busy instead (an example is available in Node Detailed Dashboard). If the admin wants to know more, he can consult the Node Dashboard in which he will see CPU Usage per core.

> **System load**:
> ![image](https://user-images.githubusercontent.com/18453133/91709314-dd578e00-eb82-11ea-8b8e-420b79c4879b.png)
> The average of 1 min (query example from Grafana)
> `node_load1{instance=~"192.168.1.18:9100",job=~"node-exporter"}`
> Average of 5 mins
> `node_load5{instance=~"192.168.1.18:9100",job=~"node-exporter"}`
> 

please use the node_load5

> **Memory**:
> ![image](https://user-images.githubusercontent.com/18453133/91709921-bcdc0380-eb83-11ea-8a34-0657016e581f.png)
> In our node page, it will be a line chart instead of a Gauge.
> 
> ![image](https://user-images.githubusercontent.com/18453133/92095944-9cf04e00-edd6-11ea-8189-8434a60ee453.png)
> 
> `((node_memory_MemTotal_bytes{instance=~"192.168.1.18:9100",job=~"node-exporter"} - node_memory_MemFree_bytes{instance=~"192.168.1.18:9100",job=~"node-exporter"}) / (node_memory_MemTotal_bytes{instance=~"192.168.1.18:9100",job=~"node-exporter"} )) * 100`
> 
> `100 - ((node_memory_MemAvailable_bytes{instance=~"192.168.1.18:9100",job=~"node-exporter"} * 100) / node_memory_MemTotal_bytes{instance=~"192.168.1.18:9100",job=~"node-exporter"})`
> 
> **IOPS**:
> ![image](https://user-images.githubusercontent.com/18453133/91710312-586d7400-eb84-11ea-84a2-011f41e14bb4.png)
> 
> > this graph is showing one line per disk, where we want to aggregate at the full Node-level, so may need to tweak the query a bit
> 
> ```
> irate(node_disk_reads_completed_total{instance=~"192.168.1.18:9100",job=~"node-exporter"}[5m])
> ```
> 
> ```
> irate(node_disk_writes_completed_total{instance=~"192.168.1.18:9100",job=~"node-exporter"}[5m])
> ```
> 
> solution: change the query to aggregate by instance

So yes, we should display the aggregation of all devices available on the node and we should have one line for read and one line for write

> 
> **IO Bandwidth**:
> ![image](https://user-images.githubusercontent.com/18453133/91711012-7687a400-eb85-11ea-8eec-fa126418a1ff.png)
> 
> The queries from Grafana.
> 
> ```
> irate(node_network_receive_bytes_total{instance=~"192.168.1.18:9100",job=~"node-exporter"}[5m])
> ```
> 
> ```
> irate(node_network_transmit_bytes_total{instance=~"192.168.1.18:9100",job=~"node-exporter"}[5m])
> ```
> 
> > We'll need to find a way to map "control plane"/"workload plane" to the right interface (likely eth1 or eth2 in scality cloud, but may be completely different in prod), today I don't know how we'll get it from the UI.
> 
> Issue solved:
> 
> ```
>   saltApiClient.post('/', {
>     client: 'local',
>     tgt: '*',
>     fun: 'grains.item',
>     arg: ['metalk8s:control_plane_ip', 'metalk8s:workload_plane_ip', 'ip_interfaces'],
>   })
> ```
> 
> From Salt result above we can map the control plane/workload plane IP address to the right interface.

first, we should rename this one: Bandwidth or Network Bandwidth but not IO Bandwidth.
I suggest we have one chart for WP bandwidth and another one for CP bandwidth. The reason is the traffic may be totally different so it does not make a lot of sense to put them in the same chart.
Finally we should have one line for IN and another one for OUT bandwidth in each chart.

Last but not least, we don't have information about system devices (that are not used by any metalk8s Volumes). We would need to design a new tab for this

**Comment by ChengYanJin** [comment]
Done with the investigation.
No PR needs to be merge.
