### ISSUE TITLE
[UI New Node Page] Layout of New Node page 

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2771]
**Component**: ui

**Why this is needed**:

**What should be done**:
What is the temporary URL to access this new node page?  `/newNodes/`
The layout of empty node page, breadcrumb with empty node table only with Header (Health/Name/Role/Status), no node selected on the right side panel.

**Implementation proposal** (strongly recommended):
After implementing this issue, we should have the UI look like this but for Node page:
![image](https://user-images.githubusercontent.com/18453133/92225693-dc38a080-eea3-11ea-8b3f-01a5fb383d52.png)

**Test plan**:

**Comment by gdemonet** [comment]
The recommended URL `/newNodes/` looks strange to me: why not keep it under the `/nodes` _collection_ URL? What is the meaning of `new` here? What difference is there between an empty list of `/nodes` and this page?

**Comment by ChengYanJin** [comment]
> The recommended URL `/newNodes/` looks strange to me: why not keep it under the `/nodes` _collection_ URL? What is the meaning of `new` here? What difference is there between an empty list of `/nodes` and this page?

Note that this URL `/newNodes/`  is only a temporary solution to access the WIP New Node Page, whereas we can still access the Old Node Page before all the development are done for New Node Page
