### ISSUE TITLE
[UI New Node Page] Add the node selection in Node Table & empty tabs on the right side panel

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2773]
**Component**: ui

**Why this is needed**: 
We want to check the detailed information of each node.

**What should be done**: 
- When I click one node in the node list, this row should be highlighted.
- And url should change to `/nodes/<node-name>`
- And I want to see there are 5 empty tabs on the right side panel (Health/Alerts/Metrcis/Volumes/Pods)
- When I click each tab, I can see the empty content inside the tab
- And the URL should update

**Implementation proposal** (strongly recommended):
The URL proposal:
```
/nodes/
/nodes/<node-name>/health
/nodes/<node-name>/alerts
/nodes/<node-name>/metrics?from=<time>&to=<time>
/nodes/<node-name>/volumes
/nodes/<node-name>/pods
```

**Test plan**:
TBD

**Comment by gdemonet** [comment]
> When I click one node in the node list, this row should be highlighted.
> And url should change to /nodes/<node-name>

Shouldn't we go to one tab in particular? Also, related question, when we switch between nodes, should we keep the same tab open?

**Comment by thomasdanan** [comment]
> Shouldn't we go to one tab in particular? Also, related question, when we switch between nodes, should we keep the same tab open?

Ideally, I think we should go to Alert tab as soon as the Node is not healthy ...
If the Node is Healthy, I suggest we go to Info tab
for simplicity (and for first iteration) I suggest the same apply when we switch from one node to another

@xaf-scality @thirstler @bkettler what do you think?
