### ISSUE TITLE
[UI New Node Page] Add Overview Tab in the New Node Page

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2774]
**Component**: ui, nodes

**Why this is needed**:

**What should be done**:
Following the rework the design of Overview tab.

**Implementation proposal** (strongly recommended):
![Moonshoot - User workflow](https://user-images.githubusercontent.com/18453133/94664576-56294180-030b-11eb-9ed6-e29491c9d475.jpg)

- Remove the [delete] & [drain] button 
- Replace last updated by created
- Remove Region & Zone
- Remove the health status bar
- Add taints
```
[root@zenkotda-bootstrap centos]# kubectl describe node bootstrap | grep -A 2 Taints
Taints:             node-role.kubernetes.io/bootstrap:NoSchedule
                    node-role.kubernetes.io/infra:NoSchedule
                    node.kubernetes.io/unschedulable:NoSchedule
```
- Display separately CP IP and WP IP

**We are waiting for the new design of Overview Tab in Node Page, will resume the work after the design**

**Test plan**:
TBD

**Comment by gdemonet** [comment]
> Replace last updated by created

Why? What's the value of doing this?

> Add taints

Not sure if urgent, TBH. However, it would be ideal to show the Role**s** (not just one), and show them as they are stored in `node-role.kubernetes.io/<role-name>` labels (not through some dance for mapping role labels and taints to our higher-level checkboxes). This will allow to see "other roles" which may be defined by the user manually (and still deserve to be displayed properly).
