### ISSUE TITLE
[UI New Node Page] Add metrics graph in Node Page

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2776]
follows: #2765 

**Component**: ui, nodes

**What should be done**:
- [x] Add the graphs with the dafault timespan of 'Last 24hours'
- [x] the choices of timespan are last 24hours/ last 7 days/ last 1 hour ( by default is last 24 hours)
- [x] Update the URL with the query of current timespan
- [x] the graphs can be auto-refreshed

**Implementation proposal** (strongly recommended):
![image](https://user-images.githubusercontent.com/18453133/92244815-b4593500-eec3-11ea-909c-0453f50f306e.png)
Add one more query param in the URL for the three timespan choices.

Last 7days: &from=now-7d
Last 24hours: &from=now-24h
Last 1 hour: &from=now-1h

**Test plan**:
TBD

**Comment by gdemonet** [comment]
> the graphs can be auto-refreshed

This sentence is unclear to me: does it mean the charts **will** be automatically refreshed? Or does it mean we have some way of toggling the automatic refreshing of charts? In which case, how/where is this feature designed?

**Comment by ChengYanJin** [comment]
> > the graphs can be auto-refreshed
> 
> This sentence is unclear to me: does it mean the charts **will** be automatically refreshed? Or does it mean we have some way of toggling the automatic refreshing of charts? In which case, how/where is this feature designed?

Hello @gdemonet,
Sorry I didn't explain it very well.
What I meant for the "chart auto-refreshing" is to call the **Prometheus API** every certain time to update the data, and the chart should update too.

Does it make sense? 
It's exactly the same thing we did for Volume Page.
