### ISSUE TITLE
bootstrap fails with metalk8s in centos 7

### ISSUE THREAD

**Issue by Baitanik** [scality/metalk8s#2796]
I am facing issue while trying to deply bootstrap iso.. 
[bootstra_.config.log](https://github.com/scality/metalk8s/files/5220322/bootstra_.config.log)
[bootstrap.log](https://github.com/scality/metalk8s/files/5220324/bootstrap.log)
[ifconfig.log](https://github.com/scality/metalk8s/files/5220325/ifconfig.log)

1. I have created the metals k8s iso in centos 7 vm 
2. I copied the iso to another centos 7 vm .
3. Tried to execute the steps mentioned here : https://metal-k8s.readthedocs.io/en/2.5.1/installation/bootstrap.html 
but bootstrapping is failing with errors.

````
Summary for local
-------------
Succeeded: 70 (changed=8)
Failed:    13
````
Some how it is trying to connect to salt-api in 10.105.58.123 .. which is the node ip ... 

Please check the attached file for the console log.
Also please check the bootstrap.config for the bootstrap.yaml .
the machine IP is 10.105.58.123 . 
I have attached the ifconfig o/p also... 

Could you please help .. what is the issue here ?
Do I have run salt separately before running bootstrap ?

**Comment by gdemonet** [comment]
Hello @Baitanik! Thanks for the detailed report, and sorry if the error messages are confusing, we are working on making them easier to interpret.

It appears the first error to occur is a failure to install `runc`. This package should be available in the `extras` repository configured for your OS.

Could you confirm that it is available by running `yum search runc` from your VM? It should print something similar to the following:

```
==================================== N/S matched: runc ====================================
runc.x86_64 : CLI for running Open Containers
```

If not, I see you included proxy information in your BootstrapConfiguration file. If the `base`, `extras` and `updates` repositories need to be accessed through this proxy, can you make sure `yum` is configured accordingly?
This can be done in the global `yum.conf`, or on a per-repository basis, using the following options (excerpt from `man yum.conf`):

> **proxy**  URL  to the proxy server for this repository. Set to '\_none\_' to disable the global proxy setting for this repository. If this is unset it inherits it from the global setting
>
> **proxy_username** username to use for proxy.  If this is unset it inherits it from the global setting
>
> **proxy_password** password for this proxy.  If this is unset it inherits it from the global setting
```

**Comment by Baitanik** [comment]
Hello @gdemonet , 

runc is installed the in node:
```
[root@master0-vmware123 ~]# yum search runc
Loaded plugins: versionlock
======================================================================= N/S matched: runc ========================================================================
runc.x86_64 : CLI for running Open Containers

  Name and summary matches only, use "search all" for everything.
````

yum also has the same proxy set in yum.conf file , with which I can do yum update and install packages..
proxy_username and password is not required .

```

[ERROR   ] check_cmd determined the state failed
[ERROR   ] Command '[u'crictl', u'images', u'-o', u'json']' failed with return code: 1
[ERROR   ] stderr: time="2020-09-15T04:08:23Z" level=fatal msg="listing images failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService"

```
Is there any specific version needed ? 
````
[root@master0-vmware123 ~]# crictl -version
crictl version v1.13.0
````

**Comment by Baitanik** [comment]
If I manually do yum install runc.. i get this error... 
```
[root@master0-vmware123 ~]# yum install runc
Loaded plugins: versionlock
Package runc-1.0.0-67.rc10.el7_8.x86_64 is obsoleted by containerd.io-1.2.13-3.2.el7.x86_64 which is already installed
Nothing to do
[root@master0-vmware123 ~]#
```

**Comment by Baitanik** [comment]
Docker version i have : 
```
docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
Do i need to lower the version in the doc it was mentioned it should be > 17

**Comment by Baitanik** [comment]
Even if I try to uninstall containier.io/docker-ce/cli .. then run yum install runc... it tries to download containerd.io-1.2.13-3.2.el7.x86_64 only..  

So is the metalk8s 2.5.1 not stable ? should have I taken another tag .. where it does not tries to install runc ?

```
 yum list runc --showduplicates | sort -r
runc.x86_64                    1.0.0-67.rc10.el7_8                        extras
runc.x86_64                    1.0.0-65.rc8.el7.centos                    extras
runc.x86_64                    1.0.0-64.rc8.el7.centos                    extras
Loaded plugins: versionlock
Available Packages
[root@master0-vmware123 ~]# yum install runc-1.0.0-64.rc8.el7.centos
Loaded plugins: versionlock
Package runc is obsoleted by containerd.io, trying to install containerd.io-1.2.13-3.2.el7.x86_64 instead
Resolving Dependencies
--> Running transaction check
---> Package containerd.io.x86_64 0:1.2.13-3.2.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===========================================================================================================================================
 Package                            Arch                        Version                               Repository                      Size
===========================================================================================================================================
Installing:
 containerd.io                      x86_64                      1.2.13-3.2.el7                        docker-ce                       25 M

Transaction Summary
===========================================================================================================================================
Install  1 Package


```

**Comment by Baitanik** [comment]
I removed contrainerd.io , docker -ce 19 .. 
installed "runc" manually rpm - ivh ..
https://centos.pkgs.org/7/centos-extras-x86_64/runc-1.0.0-65.rc8.el7.centos.x86_64.rpm.html

then I ran the bootstrap.sh... now that runc error did not came .. another error came like ..

````
<< BEGIN >>
[ERROR   ] Made the following changes:
'runc' changed from '1.0.0-64.rc8.el7.centos' to 'absent'
'containerd.io' changed from 'absent' to '1.2.13-3.2.el7'
````

I guess you have some circular dependency in the bootstrap !!! please check one...  
After running the bootstrap, it automatically again unstalled the runc and installed the contrainerd.io.. 


I am attaching the new log which I got after manually  installing runc...
[bootstrap_new_log.log](https://github.com/scality/metalk8s/files/5222743/bootstrap_new_log.log)

And the salt -api error is still there.

**Comment by gdemonet** [comment]
Thanks for going further with the investigations.

First of all, MetalK8s 2.x does not expect a Docker installation, and this _may_ be causing trouble. Could you try disabling the Docker CE repository before running the bootstrap again? It is possible that our installation process finds the `containerd.io` package from this repository, which obsoletes the `runc` dependency we need, instead of installing it from the offline repository we ship (called `metalk8s-epel`).

I will try reproducing on my side.

For the Salt API error, it is due to `containerd`/`runc` not being installed, hence the Salt master Pod cannot start. It is a bug (bootstrap should bail out earlier), for which we'll open another ticket, while we try to resolve your issue.

**Comment by Baitanik** [comment]
Also the certificate 
```
lt__['x509.create_certificate'](testrun=True, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/x509.py", line 1430, in create_certificate
    kwargs.update(signing_policy)
TypeError: 'NoneType' object is not iterabl
```
i am not sure why this error is coming... 
I have followed the steps mentioned in the readthedoc page... for 

```
[root@master0-vmware123 ~]# ll /etc/metalk8s/pki
total 8
-rw-------. 1 root root 3247 Sep 14 13:10 salt-bootstrap
-rw-r--r--. 1 root root  758 Sep 14 13:10 salt-bootstrap.pub
[root@master0-vmware123 ~]#
```

**Comment by Baitanik** [comment]
@gdemonet Thanks for the suggestion of disabling docker repo.. 
After disabling the docker repo the runc error got passed.. It would be better if in the doc we could mention this .. disable docker repo if exists.. because the prerequisite was docker to be installed.. so it might create confusion ..  

the create_certificate issue is there, for that salt-api is coming
```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1981, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1977, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/x509.py", line 502, in certificate_managed
    new = __salt__['x509.create_certificate'](testrun=True, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/x509.py", line 1430, in create_certificate
    kwargs.update(signing_policy)
TypeError: 'NoneType' object is not iterable

```
I am attaching the log.. 
[bootstrap3.log](https://github.com/scality/metalk8s/files/5223144/bootstrap3.log)


according to the steps mentioned , I had done : 
```
mkdir -p /etc/metalk8s/pki
ssh-keygen -t rsa -b 4096 -N '' -f /etc/metalk8s/pki/salt-bootstrap

[root@master0-vmware123 ~]# ll /etc/metalk8s/pki
total 8
-rw-------. 1 root root 3247 Sep 14 13:10 salt-bootstrap
-rw-r--r--. 1 root root  758 Sep 14 13:10 salt-bootstrap.pub
[root@master0-vmware123 ~]#
```

**Comment by gdemonet** [comment]
> After disabling the docker repo the runc error got passed.. It would be better if in the doc we could mention this .. disable docker repo if exists.. because the prerequisite was docker to be installed.. so it might create confusion ..

OK, that's a relief. Indeed, we should make sure the installation docs are clear about this (and even, we could make sure we can install with this repo being available). The prerequisite for having Docker installed you are referring to comes from the [ISO building docs](https://metal-k8s.readthedocs.io/en/latest/developer/building/requirements.html), right? We may want to add a warning that this procedure should only be used for building, and that installing should be done on another clean machine.

> the create_certificate issue is there

This issue is likely caused by a discrepancy between the value of `/etc/salt/minion_id` and the name you set for `ca.minion` in `/etc/metalk8s/bootstrap.yaml` (they need to be the same - another thing we should improve in our documentation). This can be due to a difference between `hostname` and what Salt retrieves as a hostname. Can you change the value in `/etc/metalk8s/bootstrap.yaml` and try re-running bootstrap?

**Comment by Baitanik** [comment]
Yes the  ISO building docs : https://metal-k8s.readthedocs.io/en/latest/developer/building/requirements.html 
I will check the hostname and minion_id are same or not .. will revert back here.. thanks for all the help

**Comment by Baitanik** [comment]
Hi I am able to now bring up the metalk8s .. Thanks you so much for all the help..
one question now.. 
kubernetes pods i am able to see.. 
but docker images I can not see, because docker is not installed in the system..
and if we try to install docker .. it will probably fail because of runc and container.io clash ..
So is there any way to make docker command available in the node ?

**Comment by gdemonet** [comment]
> Hi I am able to now bring up the metalk8s ..

That's great news!

> but docker images I can not see, because docker is not installed in the system..

Indeed, MetalK8s 2.x is not using Docker at all, it relies only on containerd.

> is there any way to make docker command available in the node ?

The Docker CLI is not available and cannot be used to interact with containerd. Instead, the command-line tool we use internally for this is `crictl`. Its documentation is available here: https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md

Another command-line tool for interacting with containerd directly is `ctr`, for which you may find documentation here: https://github.com/projectatomic/containerd/blob/master/docs/cli.md

Hope this helps!

**Comment by Baitanik** [comment]
Thanks @gdemonet , it helps.. 
and last query I think.. I see tow of the pods are in pending state.. 
```
[root@master0-vmware123-bt kubernetes]# kubectl get pods -A | grep '0/'
metalk8s-monitoring   alertmanager-prometheus-operator-alertmanager-0          0/2     Pending   0          42m
metalk8s-monitoring   prometheus-prometheus-operator-prometheus-0              0/3     Pending   0          42m

```
with 
```
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/1 nodes are available: 1 node(s) didn't find available persistent volumes to bind.
  Warning  FailedScheduling  <unknown>  default-scheduler  0/1 nodes are available: 1 node(s) didn't find available persistent volumes to bind.

```

do we need to create pvc manually or something is missing ?

**Comment by gdemonet** [comment]
You'll find this info in our Post-Installation guide: https://metal-k8s.readthedocs.io/en/2.5.1/installation/post-install.html#provision-storage-for-prometheus-services

**Comment by Baitanik** [comment]
Thanks a lot @gdemonet .. will apply this.. I will close this ticket.. in-case required I will create separate jira.. thanks again..
