### ISSUE TITLE
MetalK8s UI logout doesn't propagate to Dex connectors

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#2831]
**Component**: ui, dex

**What happened**:

When using Dex with a external IdP (through a connector), logging out of MetalK8s UI will not log out the user from said IdP, and the next login attempt will not prompt the user for her credentials (if this IdP has stored a session in the user's browser).

**What was expected**:

In some way, MetalK8s UI would be able to logout a user entirely, to allow switching between users, for instance. This may not be achievable without creating other issues, so we'll need more discussion / investigation.

**Resolution proposal** (optional):

TBD

**Comment by gdemonet** [comment]
This will stay blocked until Dex implements [RP-initiated logout](https://github.com/dexidp/dex/issues/1697), as per [OIDC spec](https://openid.net/specs/openid-connect-rpinitiated-1_0.html). Until then, workarounds for switching users can be:
- using a private browsing session
- manually clearing cookies for the external IdP

**Comment by thomasdanan** [comment]
Actually, we think it is normal behavior.
