### ISSUE TITLE
Upgrade containerd to 1.4.x

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#2855]
**Component**: containerd

**Why this is needed**: containerd 1.2 will be EOL by October 15th

**What should be done**: package containerd 1.4 and install it as part of MetalK8s 2.7 and higher

**Test plan**:

- the usual test suite keeps working
- validate with "real-world" Solutions, such as Zenko

**Comment by NicolasT** [comment]
#2869 was merged in `development/2.7`. However, the suggested test-plan was not fully executed:

> - validate with "real-world" Solutions, such as Zenko

If indeed this is a requirement, IMHO it should be part of the CI tests.

**Comment by NicolasT** [comment]
Done in #2869.
