### ISSUE TITLE
ISSUE: local development in windows with WSL 

### ISSUE THREAD

**Issue by jebinjeb** [scality/metalk8s#2857]
**Component**:

salt-master

**What happened**: salt-master not coming up 

i'm trying to build and run from windows WSL , but deployment failing with below error. reason is salt-master image missing in local registry cache.

Error:
    bootstrap: Command: salt-call --local --state-output=mixed --retcode-passthrough state.sls metalk8s.roles.internal.early-stage-bootstrap saltenv=metalk8s-2.6.0-dev pillarenv=metalk8s-2.6.0-dev pillar={   'repo': {'local_mode': True},   'metalk8s': {     'endpoints': {       'repositories': {          'ip': 172.21.254.7,          'ports': {'http': 8080}       },       'salt-master': {'ip': 172.21.254.7}     }   } }
    bootstrap:
    bootstrap: Output:
    bootstrap:
    bootstrap: << BEGIN >>
    bootstrap: warning: /vagrant/_build/root/packages/redhat/metalk8s-kubernetes-el7/14bfe6e75a9efc8eca3f638eb22c7e2ce759c67f95b43b16fae4ebabde1549f3-cri-tools-1.13.0-0.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 3e1ba8d5: NOKEY
    bootstrap: [ERROR   ] Status 200 was not found.

[failed to "StartContainer" for "salt-master" with ImagePullBackOff: "Back-off pulling image \"metalk8s-registry-from-config.invalid/metalk8s-2.6.0-dev/salt-master:3000.3-1\"", failed to "StartContainer" for "salt-api" with ImagePullBackOff: "Back-off pulling image \"metalk8s-registry-from-config.invalid/metalk8s-2.6.0-dev/salt-master:3000.3-1\""]

[root@localhost salt-master]# crictl images
IMAGE                     TAG                 IMAGE ID            SIZE
docker.io/library/nginx   1.15.8              f09fe80eb0e75       113MB
k8s.gcr.io/pause          3.1                 da86e6ba6ca19       746kB
[root@localhost salt-master]# crictl ps
CONTAINER ID        IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID
87ab0245519b9       f09fe80eb0e75       2 hours ago         Running             repositories        0                   8c64aaf796816
[root@localhost salt-master]#

**What was expected**: salt-master should in running state

**Steps to reproduce**: ./doit.sh vagrant_up from WSL

**Resolution proposal** (optional): need some WA to continue my deployment

**Comment by jebinjeb** [comment]
could you please provide steps to import all docker images ?

Tried something like this but didn't helped
[root@localhost salt-master]# ctr --debug -n k8s.io image import salt-master.tar
ctr: unrecognized image format

**Comment by jebinjeb** [comment]
issue got solved.

**Comment by gdemonet** [comment]
Hi @jebinjeb and thanks for trying out MetalK8s!

Our development team is not working on Windows, so we cannot reproduce your issue. However, we feel the community could benefit from your experience. Would you mind sharing some details about it, especially how you solved it?

Thanks for your help!

**Comment by jebinjeb** [comment]
@gdemonet 

Issue with folder permission, if we use shared folder from windows to linux then not getting proper permission. As a workaround instead using shared folder I copied the folder to guest VM and given proper permission after that registry container started serving the request properly.

**Comment by jebinjeb** [comment]
now i'm facing new issue, will create new ticket
