### ISSUE TITLE
bootstrap install failure

### ISSUE THREAD

**Issue by crg20** [scality/metalk8s#2861]
**Component**:

salt

**What happened**:

I am trying metalk8s install  on Centos 7 vm, and  fails with below error during beginning of install itself. please provide your suggestions to resolve this. From the logs, its not clear what went wrong or additionally need to be added.

SaltRenderError: Jinja variable 'dict object' has no attribute u'metalk8s-2.6.0-dev'
[CRITICAL] Rendering SLS 'metalk8s-2.6.0-dev:metalk8s.repo.redhat' failed: Jinja variable 'dict object' has no attribute u'metalk8s-2.6.0-dev'
[DEBUG   ] LazyLoaded highstate.output
[TRACE   ] data = {u'local': [u"Rendering SLS 'metalk8s-2.6.0-dev:metalk8s.repo.redhat' failed: Jinja variable 'dict object' has no attribute u'metalk8s-2.6.0-dev'"]}
local:

Please find below detailed information of setup and logs :

a. minion info
cat /etc/salt/minion_id
10.0.2.15

b. # cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)

c. Other details like bootstrap.yaml, bootstrap.log, please find attached. [bootstrap.log](https://github.com/crg20/test/blob/main/bootstrap.log), [bootstrap.yaml](https://github.com/crg20/test/blob/main/bootstrap.yaml), [ifconfig](https://github.com/crg20/test/blob/main/ifconfig.txt), 

**What was expected**:
install success.

**Steps to reproduce**
On CentOS Linux release 7.8.2003 (Core), run metalk8s bootstrap.sh following the document.

**Resolution proposal** (optional):

**Comment by gdemonet** [comment]
Hi @crg20, thanks for giving MetalK8s a try!

From your `bootstrap.log` attached, we can see some warnings about the configured `archives` key, like this one:

```
[WARNING ] Skip, invalid archive path /metalk8s.iso, should be an iso or a directory.
```

It is likely a configuration error, could you please check that this path points to the actual ISO you generated and mounted at `/srv/scality/metalk8s-2.6.0-dev`?

In the meantime, we think this should be caught by our formulas and generate an error. I have went ahead and opened an issue for it: #2862

**Comment by crg20** [comment]
Hi @gdemonet, Thanks for your response. I have copied the required folder structure from _build to /srv/scality/metalk8s-2.6.0-dev separately and trying the install instead of iso mount (iso file being large) and triggered bootstrap. Is there any way I can overcome this issue, please do suggest. 

Here I am trying something similar to vagrant based metalk8s install but in a separate vm.

**Comment by gdemonet** [comment]
If I'm not mistaken, mounting an ISO does not take extra space on your filesystem, so that should not be an issue in the general case (here, I understand that's problematic because you built those files from the host where you are installing: may I suggest you read through #2796, as they faced issues related to Docker being installed on the bootstrap node).

To answer your question though, yes, you can also replace this value (`/metalk8s.iso` in your case) with the path to the files themselves (`/srv/scality/metalk8s-2.6.0-dev`), and this should work (that's how we make it work for Vagrant).

**Comment by crg20** [comment]
@gdemonet, Thanks, I chose to copy directories due to copy errors for iso. I will dig further on this.
