### ISSUE TITLE
node connectivity should be checked in Pre-upgrade check

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#2894]
**Component**:

'salt', 'upgrade', 'pre-upgrade checks'

**Why this is needed**:

When performing an upgrade on a platform where all nodes are not in Ready State, the upgrade will fail.
In my specific case, a node with etcd role was created but not deployed.
As a consequence, when doing the upgrade, it failed when upgrading etcd.

```  ----------
                        ID: Sync yanjin-test minion
                  Function: salt.function
                      Name: saltutil.sync_all
                    Result: False
                   Comment:
                   Started: 20:14:28.572874
                  Duration: 57.906 ms
                   Changes:  
              ----------
                        ID: Check pillar on yanjin-test
                  Function: salt.function
                      Name: metalk8s.check_pillar_keys
                    Result: False
                   Comment: One or more requisite failed: metalk8s.orchestrate.etcd.Sync yanjin-test minion
                   Started: 20:14:28.631686
                  Duration: 0.02 ms
                   Changes:  
              ----------
                        ID: Deploy etcd yanjin-test to 2.6.0-dev
                  Function: salt.state
                    Result: False
                   Comment: One or more requisite failed: metalk8s.orchestrate.etcd.Check pillar on yanjin-test
                   Started: 20:14:28.632803
                  Duration: 0.018 ms
                   Changes: 
```

Because of the readability of salt output it is not obvious at all that it was because of this not deployed node. 

**What should be done**:

The pre-upgrade checks should make sure all nodes are reachable and abort if it is not the case.
Also when this check is failing, it should be the last message displayed to the administrator so that he quickly understand what is the problem.

**Implementation proposal** (strongly recommended):

Check to do in the pre-upgrade salt orchestrate:
- `Ready` state of the K8s Node object 
- Node reachable with Salt (`test.ping` basically)

**Test plan**:

**Comment by gdemonet** [comment]
For readability, would help a lot to have a CLI handling parsing of Salt output for our users (see #2497).
Until then, we can add such a check in our `prechecks` formulas, indeed, which will prevent the orchestration from being started (and even fail a dry-run).
