### ISSUE TITLE
vagrant_up has network connection issue

### ISSUE THREAD

**Issue by stalin12** [scality/metalk8s#2901]
**Component**:
Vagrant_up

**What happened**: When i execute command doit vagrant_up it starts to boot the VM and then tries to ssh the VM with username and password. But it never connects to the VM as it times out. Even with increase of times it doesn't solve the problem. Then I commented config.vm.network CONTROL_PLANE_NETWORK and WORKLOAD_PLANE_NETWORK and it started to work. But the problem of this is it in the later stage of build looks for this IP and fails the build.

**What was expected**:
 With network setting it should work.

**Steps to reproduce**
   doit vagrant_up.

**Resolution proposal** (optional):

**Comment by NicolasT** [comment]
Could it be the `CONTROL_PLANE_NETWORK` and `WORKLOAD_PLANE_NETWORK` CIDRs overlap with some 'real' network(s) and/or interfaces in your environment?

**Comment by stalin12** [comment]
Okay, in that case is it possible to change the CONTROL_PLANE_NETWORK and CONTROL_PLANE_NETWORK CIDRs?

**Comment by NicolasT** [comment]
Yeah. Make sure the Vagrant environment is cleaned up (`vagrant destroy`), then change the CIDRs (likely `CONTROL_PLANE_IP` and `WORKLOAD_PLANE_IP` are the values to change) in `Vagrantfile` and `./doit.sh vagrant_up` should work.

You could create a PR to make it possible to override those CIDRs from `vagrant_config.rb` so there's no need to alter a checked-in file.

**Comment by NicolasT** [comment]
Closing for now. If this is still an issue for you, @stalin12, please re-open.
