### ISSUE TITLE
Adding example solution in one environment using UI is failing

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#2945]
**Component**:

'ui', 'salt', 'solution'

**What happened**:

After importing and activating example-solution, and creating an environment (as described in [documentation](https://metal-k8s.readthedocs.io/en/latest/operation/solutions.html), I tried to add the solution in the environment and got the following errors:

<img width="772" alt="Screenshot 2020-11-26 at 11 49 38" src="https://user-images.githubusercontent.com/29035069/100342251-0353c980-2fde-11eb-9bb3-649dd7a610fa.png">

Actually, from the Chrome Developer tools, I am seeing the following:

```POST https://<ip>:8443/api/salt/ 401```
```GET https://<ip>:8443/api/kubernetes/apis/apps/v1/namespaces/production/deployments/example-solution-operator 404```

Also, the example solution operator is never scheduled.

If I do the same using solution.sh tool, I don't have issues

**What was expected**:

The UI environment/solution page should work when adding a solution in one environment

**Steps to reproduce**

see What happened section above.

**Resolution proposal** (optional):

**Comment by gdemonet** [comment]
401 on Salt API means Unauthorized. I see you've been using a custom user (likely from a Dex external provider), not `admin@metalk8s.invalid`. Does your user have the `cluster-admin` *ClusterRole* in K8s?

**Comment by ChengYanJin** [comment]
Hello @thomasdanan,

In theory, if we get 401 Unauthorized on Salt API, we should be automatically logout. 

I login MetalK8s UI through Keycloak with the user has the `cluster-admin` ClusterRole and add the `example-solution` to an environment, did not encounter any error.

Not sure what we can do more without more information actually. Should we close the issue and reopen it when we clear about the issue?

**Comment by ChengYanJin** [comment]
We removed the environment page from the UI.
