### ISSUE TITLE
Ensure bootstrap Node object is created before initial kubelet registration

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#2974]
**Component**: salt, kubernetes

**Why this is needed**:

When we reconfigure kubelet to start talking with kube-apiserver, its corresponding Node object is not yet created. The kubelet self-registration will create one with minimal information.

Later in the bootstrap process (`metalk8s.kubernetes.mark-control-plane`), we update the Node to include custom `node-role.kubernetes.io/<role>` labels and taints.

If then some Pods are scheduled to the Node **before** kubelet had time to sync its own Node with kube-apiserver, it may try, **and fail**, to admit Pods with a `nodeSelector` that does not match its own view of the Node.

**What should be done**:

Before reconfiguring kubelet, we should create the bootstrap Node ourselves with the desired role labels and taints, so that kubelet will have them in-memory immediately from initial registration.

**Test plan**:

In CI, we will add a "smoke" check to ensure we do not see any Pods failed with reason `NodeAffinity` after bootstrap.

**Comment by alexandre-allard** [comment]
Looks like it has been fixed in K8s 1.19.8+ (https://github.com/kubernetes/kubernetes/issues/93338).

**Comment by alexandre-allard** [comment]
Closing this issue as it's already fixed on Kubernetes side on latest versions.
