### ISSUE TITLE
what is proper way to debug if metalk8s installation fails... The logs it print not help full much

### ISSUE THREAD

**Issue by Baitanik** [scality/metalk8s#2989]
[metal.log](https://github.com/scality/metalk8s/files/5710771/metal.log)

I have attached the log.. 
now how to get what is the actual problem it is facing ..
I have executed with --verbose while running bootstrap.sh ... 

Could anyone please help..

**Comment by TeddyAndrieux** [comment]
Hello @Baitanik,

First, thank you for your report.

I think from the output you provided the minion id you put in the bootstrap.yaml file in `ca:minion` does not match the minion id of the minion running on the bootstrap node (you can get this one with `salt-call --local grains.get id`). 
Note that before starting the bootstrap script you can force a specific salt minion id just by setting this one in `/etc/salt/minion_id` file, (for example if you want your bootstrap node to be named "bootstrap" you just have to do a `mkdir /etc/salt/ && echo 'bootstrap' > /etc/salt/minion_id` before starting the bootstrap script and that it)

I know the error is not clear at all and we should really work on that.

Just for your information, we start using GitHub discussions so for that kind of question (or any other question you have) do not hesitate to open one. https://github.com/scality/metalk8s/discussions
