### ISSUE TITLE
Alerts without a "message" annotation don't show meaningful details in MetalK8s UI

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#2994]
> I have installed metalk8s and all seems to work fine, except for Alert UI. I don't see alert message for some of the alert like KubeCPUOvercommit. 
>
> [...]
>
> ```yaml
> - alert: KubeCPUOvercommit
>     annotations:
>       description: Cluster has overcommitted CPU resource requests for Pods and cannot tolerate node failure.
>       runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecpuovercommit
>       summary: Cluster has overcommitted CPU resource requests.
> ```

_Originally posted by @n1603 in https://github.com/scality/metalk8s/discussions/2993_

We should likely handle all known alert annotations to display the most relevant information to our users when an alert fires.

**Comment by n1603** [comment]
@gdemonet, Thanks, this is how I handled this. :  [link](https://github.com/n1603/metalk8s/blob/development/2.7/ui/src/containers/ClusterMonitoring.js#L173), please let me know your feedback. Similar change for VolumeAlertsTab.js and update on [monitoring test](https://github.com/n1603/metalk8s/blob/development/2.7/tests/post/steps/test_monitoring.py#L256).

**Comment by NicolasT** [comment]
@n1603 Could you create a PR to contribute your fixes? @ChengYanJin left some notes on the process at https://github.com/scality/metalk8s/discussions/2993#discussioncomment-267200. Thanks!

**Comment by n1603** [comment]
@NicolasT, thanks. if fix helps, I will create PR after going through the process.

**Comment by n1603** [comment]
some issue with my pr branch squash not working as expected, will re-create.

**Comment by n1603** [comment]
PR : https://github.com/scality/metalk8s/pull/3030

**Comment by NicolasT** [comment]
I believe this is now closed by #3038 (#3030).
