### ISSUE TITLE
Log Dashboard not functioning properly

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#2998]
**Component**:

'grafana', 'loki', 'logs'

**What happened**:
After upgrading from 2.6 to 2.7, the Log Dashboard in Grafana is not working correctly.
Actually, the log Panel is empty and displaying an error each time the dashboard is loaded with either System or Pod log enabled.

<img width="1783" alt="Screenshot 2020-12-23 at 09 21 36" src="https://user-images.githubusercontent.com/29035069/102975402-4da66880-4500-11eb-9c3f-923edcda8666.png">

**What was expected**:
The administrator should be able to switch from Pod to System logs without breaking the dashboard.

**Steps to reproduce**

If System and Pods Logs are enabled when loading the dashboard, it works well
If we disable System or Pod Logs, then the dashboard doesn't display logs anymore
If we try to reactivate System and Pods logs, the dashboard stays broken and the only way to get logs is to reload the dashboard with System and Pod logs enabled

**Resolution proposal** (optional):

**Comment by TeddyAndrieux** [comment]
This error is due to https://github.com/grafana/grafana/issues/28621
