### ISSUE TITLE
TLS Termination

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#3]
(What's below is copied and slightly edited from an earlier e-mail thread)

In the Zenko requirements and delivery roadmap, there's some mention of TLS (among others for the Prometheus/Grafana dashboards).

In Kubernetes, TLS is often terminate by the ingress controller (in our deployments, likely Nginx). One can set annotations on an Ingress object to set up certificates, instruct the use of ECMA/LetsEncrypt,...

At the same time, there are solutions to manage certificates automatically, by declaring them as a resource, after which a controller will make sure keys are creates and signed, certificates are deployed as namespace-local secrets,... using ECMA or some (potentially self-signed) CA.

I think it could be a cool plus for the demo, showing the versatility/flexibility and existing features added to K8s, to also show this off, e.g. using `cert-manager` (which can be deployed using Helm) and a self-signed CA, or ECMA if we can get a floating IP and DNS set up somehow.

**Comment by NicolasT** [comment]
Feedback from @Zempashi:

> +1 cert-manager is sooo cool (with letsencrypt issuer, or bare CA issuer)

**Comment by NicolasT** [comment]
Feedback from @ballot-scality:

> Especially with the overall concern in security that arises with the container era, any bit of security added is a good message sent to users IMO !

**Comment by thomasdanan** [comment]
@alexandre-allard-scality @gdemonet @NicolasT Is this issue related (duplicated) to the salt beacon thing in order to automatically renew certificates? #1887. I yes I suggest we close this issue?

**Comment by gdemonet** [comment]
I think we can consider this to be obsolete given the Metal 2 approach (Salt takes care of the certs of MetalK8s services, and we *may* deploy cert-manager in the future for workloads).
