### ISSUE TITLE
Sosreport does not run option describe without also enabling option all.

### ISSUE THREAD

**Issue by ghost** [scality/metalk8s#3014]
**Component**:

sosreport

**What happened**:
sosreport does not run option describe without option all also being enabled.

**What was expected**:
sosreport should run any option requested without requiring additional options first be enabled.

**Steps to reproduce**
`sosreport -o metalk8s -k metalk8s.describe=on`

**Resolution options**:

* Approve and merge PR #3013 
* Merge from [upstream](https://github.com/sosreport/sos/blob/master/sos/report/plugins/kubernetes.py) of RHEL/CentOS.

**Comment by NicolasT** [comment]
Is this closed now #3013 was merged?

**Comment by gdemonet** [comment]
> Is this closed now #3013 was merged?

Yes I think so. Closing.
