### ISSUE TITLE
Salt-master pod (on bootstrap node) not starting if salt-minion failed to start

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#3022]
**Component**:

'salt', 'bootstrap'

**Why this is needed**:

If for some reason, salt-minion service failed to start on `bootstrap` node, the pod `salt-master` will fail to start with the following error:

`Warning  FailedMount  4s (x12 over 8m18s)  kubelet  MountVolume.SetUp failed for volume "run" : hostPath type check failed: /var/run/salt is not a directory
[root@zenkotda-bootstrap scality]# systemctl restart kubelet`

**What should be done**:

salt-master pod should be able to start even if salt-minion is not running (i.e. `/var/run/salt` is not available)

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by NicolasT** [comment]
#3041

**Comment by NicolasT** [comment]
#3041
