### ISSUE TITLE
Pre-flight check to make sure no firewalld service is enabled

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#3067]
**Component**:

'kubernetes'

**Why this is needed**:

When `firewalld` service is running it may conflict with the routing expected by Kubernetes

**What should be done**:

We should have a preflight check to check the `firewalld` is not running and is not enabled. If it is, the `bootstrap` script should abort during the pre-flight check phase and display the reason

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by NicolasT** [comment]
Note: we should *not* silently *disable* the service. Disabling it should be a conscious decision/action by the operator.
