### ISSUE TITLE
iso-manager script should build and store metalk8s.iso absolute path in bootstrap.yaml file

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#3082]
**Component**:

'iso-manager', 'upgrade'

**Why this is needed**:

When doing an upgrade the first step is to mount the new metalk8s.iso using the iso-manager script using the following command: `/srv/scality/metalk8s-X.X.X/iso-manager.sh -a <path_to_iso>`.
One may use a relative path for the metalk8s.iso, which can lead to a situation where the `boostrap.yaml` file is updated with an invalid archive entry. (cf #3079). The solution script (which is doing something similar when importing a solution) is computing the absolute path from what is provided by the user.

**What should be done**:

As for the solution script, the `iso-manager` script should check and compute the absolute path for the metalk8s.iso arg that is passed by the administrator and store it as an absolute path in the `boostrap.yaml` file

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by alexandre-allard** [comment]
Fixed by #3081
