### ISSUE TITLE
MetalK8s UI Overview Page Metrics Panel

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#3088]
**Component**: ui

**Why this is needed**:

**What should be done**:
![image](https://user-images.githubusercontent.com/18453133/107071761-7d29df80-67e5-11eb-9167-ebd220a4c1e6.png)

Questions to @thomasdanan 
1. We already have the metrics for each of the nodes, what **aggregation** we should do? **Sum** or **average** of all the nodes?
2. Which Grafana dashboard we should be redirected to when clicking on "Advanced Metrics"? To Node Details? 

**Implementation proposal** (strongly recommended):
As discussed with @Cuervino, to achieve better UX, during the loading state, we should display the skeleton of the charts, as least to keep the space for charts to avoid the whole layout changes.

For the read and write, we prefer to separate them into two quadrants
![image](https://user-images.githubusercontent.com/18453133/111762771-adaf6f80-88a1-11eb-8762-cc7beb00fea2.png)

The color guidance of linechart:
![image](https://user-images.githubusercontent.com/18453133/111919688-916f2680-8a8b-11eb-8c91-e5e3b99257f0.png)

1. CPU Usage - one line per node. 
The same promQL with node metric in Node Page.
When the number of nodes bigger than 4, use the variant of each color.

2. System Load -  one line per node.

3. Memory  - one line per node.

4. Replace `IOPS` with `Throughput` 
We will Separate `read` and `write` into two quadrants like the following example from Grafana.
![image](https://user-images.githubusercontent.com/18453133/111919016-15271400-8a88-11eb-8fa2-c68b3ec59885.png)
The PromQL should be the aggregation of Throughput (read&write) on all devices for this node.
 
 We need to do aggregation for all the volumes on this node. 
 ```js
 const nodeThroughputReadQuery = `sum(sum(irate(node_disk_read_bytes_total[1m])) by (instance, device) * 0.000001) by(instance)`;
 const nodeThroughputWriteQuery = `sum(sum(irate(node_disk_written_bytes_total[1m])) by (instance, device) * 0.000001)by(instance)`;
```
 
Note that: 
1. We implemented a feature gate for the overview/dashboard page, you will need to add `flag:["dashboard"]` in the `config.json` to have the access to `/dashboard` 
2. Please use `react-query` to retrieve the metrics.

**Test plan**:
We should test the loading state, error state and success state.

**Comment by Cuervino** [comment]
Here is an example of the loading state.
![05-03-v5-metrics-loading-state-zoom@2x](https://user-images.githubusercontent.com/28654802/107967598-9b45cb80-6fad-11eb-974a-cad7bb010554.png)
(the loader is a mockup of the coreui component)

**Comment by thomasdanan** [comment]
> We already have the metrics for each of the nodes, what aggregation we should do? Sum or average of all the nodes?

CPU usage and Memory: Bottom line the end-user wants to know how much CPU or Memory out of the total available CPU/Memory is consumed/available. So it is not as simple as taking the avg of CPU/Memory usage of each node. It is more something like Sum (used cpu time/memory used)/ Sum (available cpu time/memory)
For System Load, I don't know, @xaf-scality any thoughts on this one?
For IOPS, it should be a simple SUM
For CP and WP Bandwidth, it should be simple SUM

@xaf-scality, @patrickdos  thanks to confirm/comment all of this

> Which Grafana dashboard we should be redirected to when clicking on "Advanced Metrics"? To Node Details?

Yes Node Details Dashboard for now

**Comment by thomasdanan** [comment]
Another option suggested by @gdemonet is to have for CPU/System Load and Memory (at least), 3 metrics in each chart: Max/Min and Avg for all Nodes. This would help a user to identify how nodes vary compare to each other and compare to the avg

**Comment by thomasdanan** [comment]
for CPU/Memory/Load => one line per Node
for IOPS => we replace it per throughput because IOPS vary too much depending on the device. We put read on top and read at the bottom => same for nodes
for CP/WP bandwidth we do aggregation of all interfaces on all nodes

**Comment by Cuervino** [comment]
Latest design
<img width="1440" alt="02-platform-demo-ptf-overview" src="https://user-images.githubusercontent.com/28654802/116268078-45478e00-a77d-11eb-9c19-5757436fccc8.png">

**Comment by Cuervino** [comment]
Latest design
<img width="1440" alt="02-platform-demo-ptf-overview" src="https://user-images.githubusercontent.com/28654802/116268483-a53e3480-a77d-11eb-8173-9c81c0fa9acc.png">
