### ISSUE TITLE
`Prevent swap mount from fstab` state is not idempotent

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#3091]
**Component**: salt

**What happened**:

Running `state.highstate` on a Node with some `swap` mount configured in `/etc/fstab` will always induce changes.

**What was expected**:

Re-running highstate should not induce changes (idempotency).

**Resolution proposal** (optional):

Adjust the regular expression (syntax to be confirmed) to omit already commented out lines:

```diff
 Prevent swap mount from fstab:
   file.comment:
     - name: /etc/fstab
-    - regex: .+\s+.+\s+swap\s+.+
+    - regex: '^[^#].*\s+.+\s+swap\s+.+$'
     - onlyif:
       # Add a condition to avoid the state failure
       # in case we don t have swap in /etc/fstab
       - test -n "$(awk '$3=="swap" {print}' /etc/fstab)"
```

**Comment by alexandre-allard** [comment]
Fixed by #3361
