### ISSUE TITLE
Pre Checks that the port required for MetalK8s deployment or expansion are not in use

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#3092]
**Component**:

'install', 'expansion'

**Why this is needed**:

When deploying MetalK8s or expanding the cluster, we are assuming that all MetalK8s services will be able to listen on a pre-defined port number. Since we are not in control of how the OS is deployed and configured, some services mail fail to start because the port is already in use.

**What should be done**:

When installing the bootstrap node or when adding a new node to the cluster we should first check the following ports are not already used.

Bootstrap node ports:
```
<control plane>:4505: Salt-master publisher
<control plane>:4506: Salt-master request server
<control plane>:4507: Salt API
<control plane>:8080: repository/registry
<control plane>:8443: nginx ingress control plane
```

Master nodes ports:
```
<ALL>:6443: apiserver
127.0.0.1:7080: apiserver proxy health check
127.0.0.1:7443: apiserver proxy
<control plane>:10257: kube-controller-manager secure port
<control plane>:10259: kube-scheduler secure port
```

Etcd nodes ports:
```
<control plane> AND 127.0.0.1:2379: etcd client traffic
<control plane>:2380: etcd peer traffic
<control plane> AND 127.0.0.1:2381: etcd metrics
```

All nodes:
```
127.0.0.1:9099: calico node rediness probe
<ALL>:9100: Node exporter
127.0.0.1:10248: kubelet health check
<ALL>:10249: kube-proxy metrics
<control plane>:10250: kubelet
<ALL>:10256: kube-proxy health check
```

This list should be exhaustive. As part of this ticket, a simple test should be implemented to make sure this list of port is exhaustive (basically checking all listening ports on a MetalK8s node)

This should be in line with the list of ports we need to document: https://github.com/scality/metalk8s/issues/264

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by NicolasT** [comment]
We should check for them to be available, but does it make sense to document sockets bound to `localhost` only?

**Comment by TeddyAndrieux** [comment]
> We should check for them to be available, but does it make sense to document sockets bound to `localhost` only?

To me, we want the full list of ports used so that users can make sure prior to installation that all these ports are free

**Comment by TeddyAndrieux** [comment]
But maybe we'll want something else in the documentation (probably some sort of graph) to represent various communications between nodes for firewalls configurations

**Comment by NicolasT** [comment]
> > We should check for them to be available, but does it make sense to document sockets bound to `localhost` only?
> 
> To me, we want the full list of ports used so that users can make sure prior to installation that all these ports are free

Agree, never mind my previous comment then :smile:
