### ISSUE TITLE
MetalK8s UI Overview page Services Panel 

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#3093]
**Component**: UI, monitoring

**Why this is needed**:
We want to display the health of the grouped services.

**What should be done**:

![image](https://user-images.githubusercontent.com/18453133/113686013-1df22980-96c7-11eb-932c-941a584889a6.png)

~~We would require the final design from @Cuervino @thomasdanan about the interaction, more specifically, when hovering on the status what should we display on the tooltip.~~
~~-  We currently blocked by the group alert feature. (so this ticket is only about UI layout)~~
(Edited: Not anymore blocked)
~~- This component should include a layout property and stay independent to be reused by other applications at runtime.~~
(Edited: We don't require this anymore since we will import the alerthooks from shell UI through the federated hook)

Interaction design:
https://www.figma.com/proto/N2jOAK44dTSiBclDjXzz6a/Next_Gen_Design?node-id=301%3A116&viewport=1035%2C-840%2C0.23489561676979065&scaling=min-zoom&page-id=180%3A3495

**Implementation proposal** (strongly recommended):
We need to restyle the tooltip in core-ui to meet the interaction design. 

**Test plan**:
TBD

**Comment by thomasdanan** [comment]
@ChengYanJin @Cuervino @xaf-scality @brembelguebli. In terms of interaction with any service entity Health icon, I suggest the following. 

First, be consistent with the interaction we have for the Global Health Component of the platform.

As such I suggest that when we mouse over we have a tooltip displaying the following info for the High-Level Service Alert: Severity, Start (i.e. time at which the alert was fired), description.

If the admin wants to understand more about this service health alert, he can click on the health icon and be redirected to the alert page to explore the alert tree belonging to this service Health alert. @Cuervino not entirely sure clicking on the icon is obvious, maybe you have a better proposal here?

**Comment by ChengYanJin** [comment]
Following the new design of the dashboard page:
https://github.com/scality/metalk8s/issues/3088#issuecomment-827698089
![image](https://user-images.githubusercontent.com/18453133/125765072-73b54716-8b81-4ce0-ada2-df69afd3080d.png)

we should enrich selectors in `alertHooks.js` in shell UI and retrieve them MetalK8s UI
```js
export const getVolumesAlertSelectors = (): FilterLabels => {
  return { alertname: ['VolumeAtRisk', 'VolumeDegraded'] };
};
```
You can check all the deployed alert rules: 
https://192.168.1.18:8443/api/prometheus/rules#metalk8s-alert-tree.rules

**Core:**
K8s master: 
alertname: [ "K8sMasterServicesAtRisk", "K8sMasterServicesDegraded"]

Boostrap:  
alertname: ["BootstrapServicesDegraded"]

**Observability:**
Monitoring: 
alertname: ["MonitoringServiceAtRisk", "MonitoringServiceDegraded"]

Alerting:
alertname: ["AlertingServiceAtRisk", "AlertingServiceDegraded"]

Logging:
alertname: ["LoggingServiceAtRisk", "LoggingServiceDegraded"]

Dashboarding:
alertname: ["DashboardingServiceDegraded" ]

**Access:**
Ingress Controller:
alertname: ["IngressControllerDegraded"]

Authentication: 
alertname: ["AuthenticationDegraded"]
