### ISSUE TITLE
Remove the Environment page from the MetalK8s UI

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#3168]
**Component**:

'ui', 'environments'

**Why this is needed**:

All the environment and solution functionalities are not mature enough currently and may need deep brainstorming to better define the set of functionalities we want to provide as part of MetalK8s. As such, even if we keep the solutions tooling available in CLI (for importing images and CRDs as well as deploying the solution operator in a specific namespace), we prefer to remove it from the MetalK8s UI to avoid someone doing wrong actions easily.

**What should be done**:

Remove the Environment page from the MetalK8s UI, its code, and the associated cypress tests.

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by ChengYanJin** [comment]
Merged in https://github.com/scality/metalk8s/pull/3167
