### ISSUE TITLE
Display "Swap Memory" & "Active Memory" in Node/Volume Chart page

### ISSUE THREAD

**Issue by Cuervino** [scality/metalk8s#3192]
**Component**:
GUI - charts

![image](https://user-images.githubusercontent.com/28654802/110796458-43327a00-8278-11eb-8f13-7467c55eeaa1.png)

**Why this is needed**:
During user review, the need of having also the SWAP memory metrics has been raised.

**What should be done**:
Display also the SWAP memory in the charts (Volumes / Nodes screens)

**Implementation proposal** (strongly recommended):
Having 2 lines in the Memory chart, with "Active" as a legend for the first one, and "SWAP" for the second one.

**Test plan**:

**Comment by NicolasT** [comment]
Kubernetes nodes don't have, and shouldn't have, and can't have, swap. We actively disable any configured swap during installation. Hence, there should be nothing to display.
