### ISSUE TITLE
UI: Details tab is not scrollable

### ISSUE THREAD

**Issue by JBWatenbergScality** [scality/metalk8s#3202]
**Component**:

UI

**What happened**:

1. Details Tab of volume page is not scrollable when the resource manifest is too long : 
![image](https://user-images.githubusercontent.com/75977494/111280609-55c3ff00-863c-11eb-8a49-fa026de84e4f.png)

2. the height of the details tab on the node page is not fully used.
![image](https://user-images.githubusercontent.com/18453133/111282221-10a0cc80-863e-11eb-9182-8fff370e70ac.png)

**What was expected**:

1. User should be able to scroll to view the entire manifest.
2. The height should be the same as VolumeTab container

**Resolution proposal** (optional):

Display a scrollbar for long manifests

**Comment by ChengYanJin** [comment]
We will redesign the detail tab in a more readable way.  Let's halt this issue for the moment.

**Comment by ChengYanJin** [comment]
Fixed in https://github.com/scality/metalk8s/pull/3194.
