### ISSUE TITLE
UI: Validate labels names for volumes

### ISSUE THREAD

**Issue by JBWatenbergScality** [scality/metalk8s#3203]
**Component**:

UI

**What happened**:

When creating a volume using specials characters in the UI is authorised for labels but denied when submitting the query to kubernetes API.

Kubernetes API answered with this message : `Volume.storage.metalk8s.scality.com "test" is invalid: metadata.labels: Invalid value: "'world'": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')` but from the UI point of view we just see a generic error :

![image](https://user-images.githubusercontent.com/75977494/111287647-b86cc900-8643-11eb-8d55-784a0c45a0bb.png)

**What was expected**:

Field should be validated when they are being filled in or we should display the error message so that the user can understand that the issue comes from invalid characters.

**Steps to reproduce**

Create a volume and use a `'` as a label name or value.

**Comment by ChengYanJin** [comment]
merged in #3338
