### ISSUE TITLE
Deploy fails at "LVM Setup: Create the LVM Volume Groups"

### ISSUE THREAD

**Issue by atooki** [scality/metalk8s#323]
I created a 3 node test environment.

- Created directory `/inventory/metalk8s/inventory/quickstart-cluster/group_vars`

- My storage is: metalk8s_lvm_drives_vg_metalk8s: ['/dev/sdb']

Error at the LVM setup point is:

Creating physical volume '/dev/sdb' failed.

**Comment by NicolasT** [comment]
@atooki Are there any partitions on `/dev/sdb`?

It could help to run the playbook in verbose mode passing the `-vv` option and provide the relevant log output as well, thanks!

**Comment by atooki** [comment]
Yes there is a partition. The lvm is labelled as DEMO/vdb. I changed the kube-node.yml file to point to that instead and it now says

Creating physical volume '/dev/dm-3' failed.

**Comment by NicolasT** [comment]
Volumes with partitions are currently not supported as LVM PVs: they'll fail on the filters set up system-wide. We have a PR in progress (#232) to detect this early-on and fail with a suitable message.

To get more insight, please run `ansible-playbook` with `-vv`.

**Comment by atooki** [comment]
@NicolasT I deleted the partition and that worked. But it returned another error. I will close this issue and raise a new one. Thanks for your help
