### ISSUE TITLE
Active Alert component in Node or Volume page is not correctly aligned

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#3241]
**Component**:

'ui'

**What happened**:

Probably since the implementation of basic responsiveness in MetalK8s UI 2.8, the alert component in Node and Volume page is now aligned on the extreme right of the page:

<img width="843" alt="Screenshot 2021-03-26 at 09 22 22" src="https://user-images.githubusercontent.com/29035069/112603115-d3de8d80-8e14-11eb-9d7d-6ca2a6447d01.png">

**What was expected**:

In previous releases, the component was better aligned (i.e. not at the extreme right). We should restore this behaviour for a normal screen display.

**Steps to reproduce**

**Resolution proposal** (optional):

**Comment by ChengYanJin** [comment]
Fixed in the rebranding PR.
![image](https://user-images.githubusercontent.com/18453133/116407170-c5c7c680-a831-11eb-98e4-4e369def7aa1.png)
