### ISSUE TITLE
UI: Component sharing framework

### ISSUE THREAD

**Issue by JBWatenbergScality** [scality/metalk8s#3259]
**Component**:

UI

**Why this is needed**:

Some solutions UI would need to be able to reuse components defined in Metalk8s UI.

**What should be done**:

As a start we want to export the following components :
- [x] AlertProvider
- [x] useAlerts
- [x] useNodesAlert
- [x] useVolumesAlert
- [x] useServiceAlert
- [x] useNetworkAlert
- [x] getNodesCountQuery
- [x] getVolumesCountQuery

**Test plan**:

Integration test with a solution UI
Is this chunk available to be imported independently than the UI ?
Does it bundles its required dependencies correctly ?
Is it resilient to peer dependencies upgrades ?

**Comment by ChengYanJin** [comment]
Done in PR #3295
