### ISSUE TITLE
Apply 4XX & 5XX page in MetalK8s UI

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#3266]
**Component**: UI

**Why this is needed**:
Following the implementation of 4XX & 5XX https://github.com/scality/core-ui/issues/245
We should display the correspondent page when it's needed.

**What should be done**:
List the cases/roue that should display the 4XX & 5XX page:

**Implementation proposal** (strongly recommended):
Implement a wrapper to retrieve the current language from the navbar to set the lang prop in 4XX/5XX. This wrapper would potentially be needed for some other components as well.

4XX  Page: The path in the URL does not exist.

**Test plan**:
Add navigation test if 4XX & 5XX page are displayed correctly.

**Comment by JBWatenbergScality** [comment]
Error page would need to be displayed in case the navbar is not loaded correctly (https://github.com/scality/metalk8s/blob/development/2.9/ui/src/components/Navbar.js#L165) and in case of auth failures (https://github.com/scality/metalk8s/blob/development/2.9/ui/src/containers/PrivateRoute.js#L9). It also need to be displayed when we failed to fetch the config (https://github.com/scality/metalk8s/blob/development/2.9/ui/src/index.js#L45)

**Comment by alexis-ld** [comment]
@ChengYanJin @JBWatenbergScality @theocerutti Do we want to display the 5xx error page each time the API returns a 500 on any endpoint or just on the specific cases @JBWatenbergScality mentioned above ?

**Comment by ChengYanJin** [comment]
> @ChengYanJin @JBWatenbergScality @theocerutti Do we want to display the 5xx error page each time the API returns a 500 on any endpoint or just on the specific cases @JBWatenbergScality mentioned above ?

Hello, we should display the 500 error page only on the cases that JB mentioned.

**Comment by JBWatenbergScality** [comment]
A specific case to take care of is when we failed to load the navbar the error page should be displayed in full screen (without any navbar) and default to english language as the language preference could not be retrieved without navbar

**Comment by theocerutti** [comment]
The 'Return Home' button on the error pages should redirect to which route (default: '/') ?
For page 500, should we display the support link? If so, what is the support link, https://www.scality.com/support/ ?

EDIT:

Should we display page 500 in fullscreen when there are auth failures / failed to fetch config or should we display page 500 with the navbar (if the navbar has not failed to load of course)?

**Comment by JBWatenbergScality** [comment]
Return home should redirect to '/'
It should display the support link only if defined in metalk8s-ui config.json file

When we can display the navbar it is better to display it to provide others alternatives to the users, we should carefully test the auth failure case through, maybe try to provide a wrong oidcProvider url in the config to see what happen.
