### ISSUE TITLE
publish a shell-ui docker image in registry.scality.com

### ISSUE THREAD

**Issue by JBWatenbergScality** [scality/metalk8s#3269]
**Component**:

CI

**Why this is needed**:

In order to enable solutions-ui using shell-ui components to be tested independently from metalk8s.

**What should be done**:

We should publish a shell-ui image in namespace metalk8s-dev when merging a branch and tag it to the version number in metalk8s namespace when releasing metalk8s.

**Comment by gdemonet** [comment]
Design Proposal
===============
Tagging Scheme
--------------

- For development versions, publish in the ``metalk8s-dev`` namespace, with the tags:

  - ``v$version-$git_hash`` (e.g. ``v2.10.0-dev+64a73335d``)
  - ``v$version`` (e.g. ``v2.10.0-dev``)
  - ``latest`` (if this branch is the highest active development version)
  
- For released versions, publish in the ``metalk8s`` namespace, with the tags:

  - ``v$version`` (e.g. ``v2.9.2`` or ``v2.9.0-alpha.1``)
  - ``stable`` (if this is the highest released version without a pre-release identifier, such as ``-alpha.1``)

Implementation
--------------
To ensure we only publish validated / tested images, we will:

- run in ``post-merge`` for development versions, and in a ``publish`` stage for tagged releases
- retrieve a built ISO from the corresponding pre-merge artifacts
- mount the ISO, and use:

  ```
  skopeo copy dir:/mounted-iso/images/metalk8s-shell-ui/2.10.0-dev docker://registry.scality.com/metalk8s-dev/metalk8s-shell-ui:2.10.0-dev+64a73335d
  ```

**Comment by alexandre-allard** [comment]
Done in #3406
