### ISSUE TITLE
Bump Dependencies for MetalK8s 2.10

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#3279]
**Component**:

'build'

**Why this is needed**:

We didn't update dependencies such as Prometheus, Grafana, etc ... since branch 2.8. We want to always embed the latest fix, security fixes, or new features and do it before releasing the first patch version of a specific branch.

**What should be done**:

Check and update all dependencies and make sure we don't break anything ...

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by gdemonet** [comment]
Not sure if we'll have time to handle this before 2.9.0. We'll try at least to update K8s to the latest version here, and may postpone upgrading addons to a 2.10.

**Comment by TeddyAndrieux** [comment]
Kubernetes update for MetalK8s 2.9 - K8s 1.20.6 was done in #3311
Removed the milestone for the rest
