### ISSUE TITLE
Remove Volume Creation Contextual Link to Documentation

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#3286]
**Component**:

'ui', 'doc'

**Why this is needed**:

Currently, we have only one contextual link to the MetalK8s documentation. This one should be removed until we have a proper strategy to expose contextual links to documentation

**What should be done**:

Remove the contextual Link to documentation from MetalK8s UI Volume Creation page.

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by ChengYanJin** [comment]
done in PR #3295.
