### ISSUE TITLE
If setup fails after ansible-hardening (STIG) has been run, it cannot be run as root again

### ISSUE THREAD

**Issue by mastachand** [scality/metalk8s#329]
Because the ansible-hardening requirements change some settings in sshd, notably PermitRootLogin to No, it can cause some issues if the install is run with ansible user root.

We should recommend and document how to run the installer with non-root user if we are going to say that running ansible-hardening is the default. Alternatively, we should also document how to run the installer without enabling STIG.

**Comment by NicolasT** [comment]
Agree. We should document this, and add a validation to `preflight-checks` to ensure the user is not using `root` as `ansible_user`.
