### ISSUE TITLE
ui: Volume creation : button add for labels should change from disable to enable status when a label value and key is provided

### ISSUE THREAD

**Issue by JBWatenbergScality** [scality/metalk8s#3303]
**Component**:

UI

**Why this is needed**:

From a ux point of view it is not enough evident that we have to click `add` button when having entered the label, leading to human error creating the volume without the label despite having filled it in.

![image](https://user-images.githubusercontent.com/75977494/115425032-841a9880-a1ff-11eb-829f-35711774778f.png)

**What should be done**:

We should change the status of the button once having provided a label key and value so that the user clearly see the required action.

**Test plan**:

Unit test

**Comment by ChengYanJin** [comment]
merged in #3338
