### ISSUE TITLE
Host Shell-UI Image in a proper place

### ISSUE THREAD

**Issue by tcarmet** [scality/metalk8s#3313]
The shell-ui image has been built and pushed in a playground namespace in our registry. It is currently being shared among our repo as such.

https://github.com/scality/zenko-ui/blob/ecf7779b95afd71840acaf8855a68f63bc6d5317/eve/main.yml#L13
https://github.com/scality/zenko-operator/blob/4bf823c3a8c55ed8bdc5af2a75b032d6dcb603d5/eve/main.yml#L17
https://github.com/scality/Zenko/pull/1195#discussion_r618714974
**Component**:
shell-ui

**Why this is needed**:
Because this image is hosted and shared across our repos in a personal, private namespace where it should rather be hosted in a `metalk8s` namespace which could also be public.

It was probably also built manually where it should be done by our CI

**What should be done**:
Instead of having the image hosted as 
```registry.scality.com/playground/jbwatenberg/shell-ui:2.9-dev```

it should rather be something along those lines
```
registry.scality.com/metalk8s/shell-ui:2.9.0
```
**Test plan**:

```
# with no credentials required
docker pull registry.scality.com/metalk8s/shell-ui:2.9.0 # works
```

[Here are some example](https://github.com/scality/eve-examples/blob/development/1.0/docker-image/main.yml) to help you build and push the image.

Feel free to contact me directly or any member of my team to help you in settting this up.

**Comment by gdemonet** [comment]
Thanks for your concern, we already have a ticket to track this: #3269

Unfortunately, we didn't have time to get to it yet. Feel free to submit a PR if you think it's urgent :wink:

**Comment by gdemonet** [comment]
(removed priority label, as it's not something we want to keep, and is mostly used by our PO @thomasdanan for ordering tasks, and severity label, as this has absolutely no impact on production deployments of MetalK8s)
