### ISSUE TITLE
Bug in display when adding a new disk with long labels

### ISSUE THREAD

**Issue by lavigne958** [scality/metalk8s#3328]
**Component**:

UI

**What happened**:
I clicked on `Volumes` => `+ create volume` => added a label that is longer than expected.
The label key is overlapping on the label value which makes it hard to read.

**What was expected**:
The list of labels is nicely displayed 

**Steps to reproduce**
Add a new volume and add very long label key

**Resolution proposal** (optional):

![image (2)](https://user-images.githubusercontent.com/15084254/116262363-c3556600-a778-11eb-829e-4f0ada404510.png)

**Comment by ChengYanJin** [comment]
merged in #3338
