### ISSUE TITLE
Adding labels and multiple disks in UI does not add the labels

### ISSUE THREAD

**Issue by lavigne958** [scality/metalk8s#3329]
**Component**:

UI

**What happened**:
Clicked on `volumes` => `+ create volume`.

1. Added a label to my volume
2. ticked the box `create multiple volumes`
3. Choose 2 volumes
4. fill device path name
5. validate volume creation

Created volumes don't have the label I set.

**What was expected**:
The newly created volumes have the labels I set in the form.

**Steps to reproduce**
the steps above in "What happened" section

**Resolution proposal** (optional):

**Comment by ChengYanJin** [comment]
Hi @lavigne958 
Thanks for reporting this issue!

Just wanted to check with you, did you click on the `Add` button? We need to manually add the label before actually create the volume. 

I know it's super easy to miss it, we already have a ticket for that(https://github.com/scality/metalk8s/issues/3303). Will address it ASAP.


![image](https://user-images.githubusercontent.com/18453133/116404799-46d18e80-a82f-11eb-82a4-743adafd4eab.png)

**Comment by lavigne958** [comment]
Hi @ChengYanJin , 

Yes I did :slightly_smiling_face: 
I did the following step in that particular order:
1. input the name
2. input the label key
3. input the label value
4. Click on Add
5. Selected storageClass to what suits me
6. Input the devicePath
7. Ticked the box "create multiple volumes"
8. choosed 2
9. input the 2 devicePaths
10. click on create.

Then the 2 created volumes did not have the labels.

**Comment by lavigne958** [comment]
could not reproduce. believe I forgot to click on the `Add` button.

Closing this issue.
