### ISSUE TITLE
Remove Ubuntu support

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#3357]
**Component**: *

**Why this is needed**:
This implementation has never been really finished, is not fully functional and we don't test it, so it's probably broken anyway.
It consumes CI time, increases the probability of flaky builds, increases the size of the ISO and so on, for nothing.

**What should be done**:
Remove everything related to Ubuntu support.

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by gdemonet** [comment]
Tickets to close with this one:
- #1353
- #1390
- #1393
- #1623
- #1682
- #1683
- #1781
- #1941
- #2204
