### ISSUE TITLE
Use systemd cgroupdriver instead of cgroupfs in Kubelet

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#3366]
**Component**:

kubelet

**Why this is needed**:

To match recommendation from Kubernetes (kubeadm)

**What should be done**:

Change kubelet `cgroupDriver` to `systemd` (that, likely, implies some changes in contained, check https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd-systemd)

**Comment by NicolasT** [comment]
We should research and/or test what the impact is of `kubelet`/`containerd` restart when this setting is changed. As in, if `kubelet`/`containerd` is using `cgroupfs` first, some Pods/containers are running, then we restart `kubelet`/`containerd` using the new driver, will they still properly 'find' the running containers, adopt them,...?

**Comment by TeddyAndrieux** [comment]
Sure it needs some more work/investigation/test
