### ISSUE TITLE
Check python Popen.returncode

### ISSUE THREAD

**Issue by Zempashi** [scality/metalk8s#341]
In the test framework wrong shortcut has been done. The Author (me) assumed wrongly that
```
p = subprocess.Popen(...)
p.returncode
```
Ensure automatically a wait for the returncode to be set. And as the docs state: https://docs.python.org/3.6/library/subprocess.html#subprocess.Popen.returncode. This is not true. Add the proper wait() before any Popen.returncode to avoid uneeded flaky tests

**Comment by alexandre-allard** [comment]
Closing this issue as it's already fixed.
