### ISSUE TITLE
Failed at Task Check if etcd cluster is healthy

### ISSUE THREAD

**Issue by atooki** [scality/metalk8s#343]
My build fails at the task to check if the etcd cluster is healthy. 
I ran the command using the ``-vv`` parameter and the task path is
https://github.com/scality/metalk8s/blob/01c29bade4efffbafb2a8d7d3c3e0da459f1fc98/vendor/kubespray/roles/etcd/tasks/configure.yml#L63

It returns a fatal error. <ip address>:2379 "non-zero return code". 

Any help appreciated.

**Comment by Zempashi** [comment]
Could you provide us with more logs ? Ansible should have also displayed stdout and stderr. The all block of error would be much appreciated.

You may also find useful logs, running:
```
docker ps -f name=etcd* -q | xargs docker logs
```
On the corresponding node. 

Also a description of the platform (resources in ram, partition layout, anything about the network connectivity) could give us a hint of what went wrong.

**Comment by atooki** [comment]
The command above did not return any results sadly. Looking further its says my cluster is unhealthy or misconfigured  and mentions ip 127.0.0.1:4001 and http://127.0.0.1:2379. Not sure if this should be defined explicitly.

**Comment by atooki** [comment]
@Zempashi  `stderr etcd cluster is unavailable or misconfigured : error #0: client: endpoint https://10.0.0.1:2379 exceeded header timeout\n\nerror`

Platform details are:
Windows Server 2016 Host running 3 CentOS 7 (1804) VMs on Hyper-V

- 4 processors 
- 2GB RAM
- OS storage is 100Gb
- Second disk is 85GB

Running virtual networks.

**Comment by NicolasT** [comment]
We've seen similar issues with memory pressure. On a 2GB machine, `etcd` containers would only get 512MB of RAM, which is sometimes not sufficient. See #50 and #331.

Looking at `dmesg` could show `etcd` processes being killed because of `cgroup` limits being applied/enforced.

**Comment by atooki** [comment]
I increased the resources to **16GB of RAM** and **8 vCPUs**. Oh and it is running on CentOS Minimal ISO if that helps.
Ran it again with the changes to the etcd limits but still failed. I ran `etcdctl endpoint status` and got `failed to get the status of endpoint 127.0.0.1:2379 (context deadline exceeded)`  .

**Comment by atooki** [comment]
Would it help configuring etcd files? I can only see `/etc/etcd.env` and `/etc/systemd/system/etcd/service`. Would changing the discovery help?

**Comment by NicolasT** [comment]
Please look into (and provide the output of)

- `systemctl status etcd`
- `journalctl -xu etcd | tail -n50`
- Anything useful from `docker logs $CONTAINER_NAME` for the relevant etcd `$CONTAINER_NAME` found in the output of `docker ps -a`

**Comment by atooki** [comment]
Okay. Fixed that error! I ran `journalctl -xu etcd | tail -n50` and `docker logs $CONTAINER_NAME` which said  `no route to host`. I had to add a firewall rule to allow connections on port 2379 and 2380 on each of the 3 nodes. Even though I can connect to via ssh between hosts.

Example command: `sudo iptables -A INPUT -p tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT`

**But** iptables is not the default on CentOS7 so I had to turn off firewallD and install iptables to I can save the rule once it has been applied (it reverts to default when rebooted).
Thanks for your help. I seem to have another issue. So close....

**Comment by SaymonPhoenix** [comment]
I noticed a feature. If you run the playbook from any node of the future cluster, then everything goes without errors.
If you start from the host ansible, then only changing the variable in etcd.yml helps
etcd_peer_client_auth: false
But this is not safe, so I consider the problem relevant.

**Comment by NicolasT** [comment]
@SaymonPhoenix That's very surprising because in MetalK8s 1.x, including its CI, we often use a 'bastion' host from which everything gets deployed, i.e. a host that's *not* part of the future cluster.

I do agree `etcd_peer_client_auth` should not be set to `false`, not sure why you're running into issues though. Could you provide more details about your environment?
