### ISSUE TITLE
Make `make shell` environment redistributable

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#345]
The `make shell` environment is currently generated on a host system. It would be useful to make this redistributable, especially for offline scenarios.

(At least) two options:
- Make the whole `.shell-env` tree redistributable/relocatable
- If relocation is difficult, have a package containing the required sources and let `make shell` use this as a repository.

This may also need to include 'system' (binary) packages required to build certain Python packages.

Focus on Linux x86_64, but over time having this available for OSX and (one day?) Windows could be useful :)

**Comment by Zempashi** [comment]
@NicolasT what about the docker image ? Docker package itself might be a problem...

**Comment by NicolasT** [comment]
Ugh of course, totally forgot about that one... Guess I'll need to write a 'test' for it though, and document its usage.

Good point, nothing to see here (anymore)...
