### ISSUE TITLE
Use Ubuntu-based grafana image instead of the alpine image

### ISSUE THREAD

**Issue by sayf-eddine-scality** [scality/metalk8s#3480]
**Component**:
monitoring,grafana

**What happened**:
Grafna image is based on alpine image, which handles DNS SERVFAIL very poorly and result in non working datasources
**What was expected**:

**Steps to reproduce**
configure a DNS server that returns SERVFAIL in the host machine, grafana wont be able to reach loki
**Resolution proposal** (optional):
Use ubuntu-based image for grafana

**Comment by gdemonet** [comment]
Fixed by #3481
