### ISSUE TITLE
"pause" image might be removed when a node goes in "DiskPressure"

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#3601]
**Component**:

'kubernetes'

**What happened**:

If for whatever reason a node goes in "DiskPressure" kubelet will remove the "pause" image, which means if the node does not have internet access, new containers will not be able to get scheduled on this node

**What was expected**:

Pause image should **NOT** get removed

**Resolution proposal** (optional):

See: https://github.com/kubernetes/kubernetes/issues/81756
We have to set `--pod-infra-container-image` for kubelet

**Comment by NicolasT** [comment]
Whoa, good catch! We inject it at deployment time so things work but that's where things end. Should indeed ensure it gets pulled from the internal repo.

**Comment by TeddyAndrieux** [comment]
NOTE: We may face the exact same issue for the image used by the registry container `image: docker.io/library/nginx:1.19.6-alpine`, we should consider having some logic (likely in salt) so that we make sure that those 2 images are always available
