### ISSUE TITLE
Upgrade kubespray with support of 1.11.*

### ISSUE THREAD

**Issue by virtuman** [scality/metalk8s#364]
Are you planning to upgrade included kubespray to the most recent version, including support of 1.11.* kubernetes?

Thanks

**Comment by NicolasT** [comment]
Yes we do, however we'll only do so after the test-suite to validate upgrades landed (cfr. #344), and updating to K8s 1.11 will not be in the MetalK8s 1.0 release cycle.

See also https://github.com/scality/metalk8s/projects/4

**Comment by NicolasT** [comment]
See #403.
