### ISSUE TITLE
Add tests against Elasticsearch

### ISSUE THREAD

**Issue by alxf** [scality/metalk8s#365]
Add few tests against Elasticsearch services in the post install suite.

**Comment by NicolasT** [comment]
@alxf Is this fixed in #346?

**Comment by alxf** [comment]
@NicolasT unhappily no, we are stuck now because of the liveness probe which is really too short and prevent the cluster to reach the green status (impact only the one node setup). We can't modify this timeout with the external values feature.

**Comment by NicolasT** [comment]
Did you try to lower the allocated memory and CPU resources, for the ES services to be able to start when co-located on a small VM?

**Comment by alxf** [comment]
Solved the VM is in fact ok to run the default setup with the correct antiAffinity settings.

**Comment by thomasdanan** [comment]
won't do
