### ISSUE TITLE
kubectl auto-completion in make shell does not work

### ISSUE THREAD

**Issue by mastachand** [scality/metalk8s#381]
Using metalk8s 1.0.0 on centos 7.4.1708, I simply make shell after downloading and I get an auto-completion error with kubectl everytime i hit tab after kubectl.

```
[root@k8s-zktrainingeu-master metalk8s-1.0.0]# make shell
Launching MetalK8s shell environment. Run 'exit' to quit.
(metal-k8s) [root@k8s-zktrainingeu-master metalk8s-1.0.0]# kubectl bash: _get_comp_words_by_ref: command not found
bash: _get_comp_words_by_ref: command not found
```

This does not happen when i use kubectl outside of the metalk8s shell

```
(metal-k8s) [root@k8s-zktrainingeu-master metalk8s-1.0.0]# exit
[root@k8s-zktrainingeu-master metalk8s-1.0.0]# kubectl
artwork/          Dockerfile        docs/             .gitignore        LICENSE           playbooks/        requirements.txt  .shell-env/       third-party.yaml  vendor/
ChangeLog.rst     .dockerignore     eve/              hack/             Makefile          README.md         roles/            tests/            tox.ini
[root@k8s-zktrainingeu-master metalk8s-1.0.0]# kubectl
```

**Comment by NicolasT** [comment]
Is the `bash-completion` package installed on your system?

When starting `make shell`, we set things up such that `bash-completion` will work with `kubectl` (and `helm`). In the second example you provide, `kubectl` commands get expanded with filenames which is... not very useful.

Installing `bash-completion` and restarting `make shell` should fix this, and give you proper completion of `kubectl` commands.

**Comment by mastachand** [comment]
yep, that worked. I guess i'm surprised that bash-completion is not installed by default on a centos stock image. add it to requirements/basic packages to install maybe? it is annoying to get the error every time we hit tab.

**Comment by NicolasT** [comment]
Now, given this: it could be good to 'fix' `make shell` and *not* set up Bash completions when `bash-completion` is not installed. This will get rid of the `bash: _get_comp_words_by_ref: command not found` warning, but also result in a somewhat harder-to-use shell environment. Maybe display a message saying 'Consider installing bash-completion' instead.
