### ISSUE TITLE
CNI

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#4]
(What's below is copied and slightly edited from an earlier e-mail thread)

The default CNI provider deployed by Kubespray is Calico, out of many possible CNI implementations. To be honest, I'm losing sight a bit across all possible choices, and what the differences/pros/cons between them are.

Does anyone have an opinion on which CNI implementation to use, and why? Should Calico suffice?

Also, do we stick with `iptables` as the routing mechanism for `kube-proxy`, or do we go for IPVS (which is likely what we want to use, but are less familiar with)?

Lots of questions, little answers :) Looking for your experiences and insights!

**Comment by NicolasT** [comment]
Feedback from @shivanipradhan:

> As I started looking, I was curious why not just use Route tables... kubenet -- the network plugin in kubernetes network provider uses route tables. As I researched more, it has many known limitations
>
> 1. Route tables are limited to 50 entries per VPC. (Route tables are    used to configure network traffic between Kubernetes nodes)
> 2. network topology using multiple route tables limits the cluster from being set up in a Private VPC. Other more advanced features, such as BGP, egress control, and mesh networking are only available with different CNI providers.
> 3. when running kubenet, in AWS Cloud, you are limited to 50 EC2 instances. For large enterprises that could matter.
>
> Question 1: CNI -- which one!
> Ease of deployment of CNI: All are the same. All of the CNI providers use a daemonset installation model. A kubectl command is used to install the provider on the master, when the K8s API server is running.
>
> My vote for Calico primarily because I read it is simple, scalable and easy to Debug
> here is some good info I found (see the link below)

![cni](https://user-images.githubusercontent.com/102605/37329752-35ad9ec4-269f-11e8-9667-5396252fa0a2.png)

> Source: http://schd.ws/hosted_files/ossna2017/74/Container_%26_K8s_Networking_101_Arun_Sriraman_OSSNA17.pdf
>
>
> Question 2 -- which routing mechanism for Kube-proxy?
> Between iptables and ipvs (introduced 1.8)
> Based on what I read, iptables proxier cannot automatically retry another pod if the one initially selected doesn't respond, so it depends on having working readiness probes (https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#defining-readiness-probes).
> Proxy-mode: ipvs uses hash table as the underlying data structure and works in the kernel space. That means ipvs redirects traffic much faster, and has much better performance when syncing proxy rules. Furthermore, ipvs provides more options for load balancing algorithm
>
> My thought: iptables could suffice for now and we evolve to ipvs as and when we feel the need.

**Comment by NicolasT** [comment]
Feedback from @Zempashi:
(on using Calico)
> Calico is the most performant network overlay and the most advanced one. But it is advanced and difficult to manage.
> The choice could also be inferred by network needs:
> - calico is pure layer 3 routing, but traffic is unencrypted
> - other like flannel, need encapsulation (like vxlan) and need  configuration of switches (but allow encryption)
> - calico could offer "floating Ip" by computing shortest path via BGP  (need configuration of switches/router as well)
>
> Do we know in which network environment we will live?

(on `iptables` vs. `ipvs`)
> IPVS is still a beta feature, `iptables` could be bad at high scale, but  we don't aim for this at this point.

**Comment by NicolasT** [comment]
Feedback from @ballot-scality:
> I personally saw a lot of traction around Cilium (https://cilium.readthedocs.io/en/v0.8/architecture/)
> 
> As far as I understand it, it doesn't seem to mess with iptables to work.
>
> See https://github.com/cilium/cilium/blob/master/Documentation/kubernetes/intro.rst#service-load-balancing

**Comment by NicolasT** [comment]
An interesting option for on-prem hardware-based deployments could be Multus, when using its SRIOV integration, assuming the NICs on nodes support this: https://github.com/Intel-Corp/multus-cni

**Comment by Zempashi** [comment]
yes Cilium has a better design on the paper, but:

> Linux distros that focus on being a container runtime (e.g., CoreOS, Fedora Atomic) typically already have default kernels that are newer than 4.8, but even recent versions of general purpose operating systems, with the exception of Ubuntu 16.10, are unlikely to have a default kernel that is 4.8+. However, such OSes should support installing and running an alternative kernel that is 4.8+.

**Comment by NicolasT** [comment]
Let's stick with Calico, at least for now...
