### ISSUE TITLE
Ansible Bug

### ISSUE THREAD

**Issue by rhugga** [scality/metalk8s#405]
Using the 1.0 release I ran into this:

```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '~/devel/metalk8s/vendor/kubespray/roles/vault/handlers/main.yml': line 44, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: unseal vault
  ^ here
`

Could not see what the problem was:
`- name: restart vault service
  systemd:
    daemon_reload: true
    enabled: yes
    name: vault
    state: restarted

- name: unseal vault
  hashivault_unseal:
    url: "{{ vault_leader_url | default('https://localhost:8200') }}"
    token: "{{ vault_root_token }}"
    ca_cert: "{{ vault_cert_dir }}/ca.pem"
    keys: "{{ item }}"
  with_items: "{{ vault_unseal_keys|default([]) }}"
```

**Comment by NicolasT** [comment]
Were you running `ansible-playbook` from inside a `make shell` environment? The error seems to indicate you're missing a Python package dependency, which the `make shell` environment installs for you. See https://metal-k8s.readthedocs.io/en/development-1.0/installation-guide/quickstart.html#enter-the-metalk8s-virtual-environment-shell

**Comment by rhugga** [comment]
Ahh yea, that was my issue. Forgot to source my virtualenv. Too early. No coffee. Thanks.

**Comment by rhugga** [comment]
By the way, how the hell do you post formatted text in here? code tags don't seem to work for yaml.

**Comment by NicolasT** [comment]
> By the way, how the hell do you post formatted text in here? code tags don't seem to work for yaml.

Put the block between three backticks. See https://guides.github.com/features/mastering-markdown/
