### ISSUE TITLE
Support for kubernetes 1.12.*

### ISSUE THREAD

**Issue by virtuman** [scality/metalk8s#451]
Wondering if support for kubernetes 1.12.* is going to be added some time soon?

Kubespray is already supporting kubernetes 1.12.1 https://github.com/kubernetes-incubator/kubespray/blob/master/inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml

Thank you.

**Comment by NicolasT** [comment]
Working on it! :smiley: This will go in a `development/1.2` branch and according release(s).

**Comment by NicolasT** [comment]
See #462.

**Comment by virtuman** [comment]
great stuff. thank you!
