### ISSUE TITLE
environment setup for documentation writers should be easier

### ISSUE THREAD

**Issue by tcarmet** [scality/metalk8s#485]
The documentation is getting (or will get) better everyday with new fonts, pictures, and obviously new tools to build it. 

It's pretty easy to have a working environment when you want to build the doc into html. But things can get a little bit more complicated when building the pdf.

Could we make it easy for our futures contributors and colleagues? Per example make a good use of the docker image that is already available and provide a makefile/script (whatever) to build it and run a proper shell. Any other solution will do as long as it's easy and works either on windows, mac or linux.

Thanks

**Comment by NicolasT** [comment]
Something like https://github.com/scality/metalk8s/pull/486 @tcarmet ?

**Comment by thomasdanan** [comment]
Contributing to documentation in Metal 2 is simple enough
