### ISSUE TITLE
`etcd` memory sizing

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#50]
I just ran into an issue with my `etcd` cluster (running on separate VMs, 3 nodes) where the `etcd` processes were being killed by the kernel OOM reaper because they hit the `cgroup`'s memory limit, which was set at 512MB. The VMs have (supposedly) 4GB of memory available.

Turns out, due to https://github.com/kubernetes-incubator/kubespray/blob/595e96ebf125823c04a5a7f77e002e5a6affb9f2/roles/etcd/defaults/main.yml#L42, the memory limit is set to 512MB, because apparently Ansible decides the host has less than 4GB available (`free -m` says the same thing).

Bumping the memory limit to 1024MB (by setting `etc_memory_limit` in my inventory `group_vars:etcd`) ensures `etcd` keeps running. Should we raise the default? Size this differently?...

This also shows we should invest some time in proper monitoring of the `etcd` cluster...

**Comment by xaf-scality** [comment]
Can we find a formula saying how many memory will be consume by the etcd cluster depending on the size of the k8 cluster ?
I dont like this kind "auto" limit. I would prefer to have no limit set by default for etcd cluster and having  in the inventory a comment line saying that if the server running etcd cluster are low in memory then set the limit to 1024MB (if we decide that this is the good value) with this setting line etc_memory_limit=1024MB

**Comment by NicolasT** [comment]
So you'd set it to 0 by default, and document the ability to override. Would work for me... What do you think @Zempashi @ballot-scality @alxf

**Comment by NicolasT** [comment]
Just ran into this again, needs a solution.

**Comment by alxf** [comment]
I agree with @xaf-scality, tweak the value only if necessary, and let without limit by default.
