### ISSUE TITLE
Ability to use kubectl with undefined user

### ISSUE THREAD

**Issue by itamary** [scality/metalk8s#510]
We installed Metalk8s on CentOS 7.5 server.

We create new Linux user - with no .kube/config file or KUBECONFIG environment variable - And We have full access to the Kubernetes cluster from the new user's shell.

When trying to get the config using `kubectl config view` We are getting the following empty config:
```
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
```

**Comment by NicolasT** [comment]
You're likely running this on one of the kube-master nodes.

On this node, the apiserver listens on port 8001 (or something like that, can't check right now) and allows fully unauthenticated access, and this is the default address `kubectl` uses when no configuration is provided. This, then, works, of course.

However, this may be a security issue, depending on your host setup, so we should look into disabling this access completely...

**Comment by thomasdanan** [comment]
won't do
