### ISSUE TITLE
Kubespray upgrade process and upgrade to latest kubespray with k8s 1.13.*

### ISSUE THREAD

**Issue by virtuman** [scality/metalk8s#534]
Just wondering whether upgrade of kubespray as a dependency is a straight-forward process at this point and if it could / should be changed into upstreams git branch as a dependency?

I'm curios to whether upgrade to latest kubespray is planned? and if the process of upgrade is simple, maybe simple how-to-upgrade-kubespray guide would make it possible for the community to contribute this particular upgrade quicker? Thank you

**Comment by NicolasT** [comment]
It's fairly straight-forward: updating the `git subtree`, and review. However, given a new Kubernetes version, this should go in a new version-branch of this project, which we should set up first.

I'll look into drafting some `HACKING` documentation covering this.

**Comment by NicolasT** [comment]
A 1.3 branch has been created. I'll take care of a subtree update tomorrow.

**Comment by NicolasT** [comment]
See https://github.com/scality/metalk8s/pull/537. Reviews more than welcome :wink:

**Comment by NicolasT** [comment]
Given the work on MetalK8s 2.x (which is not based on Kubespray), we'll likely not get to this.
