### ISSUE TITLE
Bootstrap salt-master

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#550]
**Goal**
Provide an implementation of the bootstrap procedure (cfr. the diagram) up to the state a `salt-master` container is running, and accessible by `salt-minion`s.

- [x]         pre_minion_checks
- [x]         disable_salt_minion_service
- [x]         stop_salt_minion_service
- [x]         configure_salt_repository
- [x]         install_salt_minion
- [x]         configure_salt_minion_local_mode
- [x]         run_bootstrap_prechecks
- [x]         install_kubelet
- [ ]         deploy_salt_master_pod

**Delivery**
The bootstrap script.

**Comment by charlesprost** [comment]
All commands are already integrated in the bootstrap script.
The one missing is the salt-master deployment, but that's tackled in #546 
Closing the issue.
