### ISSUE TITLE
CI: define contract with build team w.r.t. build dependencies and orchestration 

### ISSUE THREAD

**Issue by jbertran** [scality/metalk8s#554]
We need to define where the CI/CD build responsibilities lie. We probably want the build team to automate the process (+ necessary dependencies) within a docker image, to make this easier for devs to use.

**Comment by jbertran** [comment]
From talks with @nootal : 

* For the first iteration, the build team will provide a single-command target to be run (`make build` or similar) that will work on dev environments out-of-the-box without adding dependencies besides docker. Our responsibility will be to call this with the necessary dependencies.
* The output of the build operation will be a simple file tree for v0, with which we can start bootstrapping the next couple of tickets. Next step for output is a .iso, for which we can just add a mount step in Eve.
* "Final" milestone product, once the glue between build, salt and CI is set, will be able to use a script provided by build team to bootstrap salt on nodes, and some salt states provided by salt team to execute deployment.

**Comment by NicolasT** [comment]
Somewhat related: @nootal Did you consider using `buildah` (more precisely, `buildah bud` and `buildah push ... docker-archive:...`) instead of Docker to build container images? This would reduce the need for any custom setup (i.e. working Docker) on the build system, not require `root`,...

**Comment by charlesprost** [comment]
> Somewhat related: @nootal Did you consider using `buildah` (more precisely, `buildah bud` and `buildah push ... docker-archive:...`) instead of Docker to build container images? This would reduce the need for any custom setup (i.e. working Docker) on the build system, not require `root`,...

No, don't know about this. Will note this in the right ticket ;-
