### ISSUE TITLE
Define a working list of packages needed on the bootstrap node

### ISSUE THREAD

**Issue by charlesprost** [scality/metalk8s#559]
In order for the bootstrap node to be able to fulfill its role, it needs a few packages (and their dependencies) available locally for installation.
All these packages must be freezed (version/hash).
They must work together on the same Centos7.6 machine.

Here is the first version of the list:

- kubelet
- containerd
- salt-minion
- container-selinux
- runc
- containerd
- cri-tools
- ebtables
- socat
- kubernetes-cni
- calico-cni-plugin (for this one we only have a binary available, so we need to be able to build a package for it at first)
- m2crypto (for certs management)

**Comment by thomasdanan** [comment]
@alexandre-allard-scality isn't this issue part of what you have done for #587 ?
