### ISSUE TITLE
Provide an automatic building for the calico-cni-plugin binary

### ISSUE THREAD

**Issue by charlesprost** [scality/metalk8s#560]
It seems this binary is the only one not available as a package.

Let's find a way to automatically include it into a package, without spending too much time in this building framework since it may evolve in the future. Could be based on mock, Docker images, etc.

Resources:

- Spec file: https://gist.github.com/NicolasT/1e58dfc3e0670ce7078de1d8d939b291
- Binary: https://github.com/projectcalico/cni-plugin

**Comment by NicolasT** [comment]
Done in #590.
