### ISSUE TITLE
Define a Centos7.6 base image that will work for everyone

### ISSUE THREAD

**Issue by charlesprost** [scality/metalk8s#561]
We need to identify which Docker image should be the one on which we base everything from now on.

Let's identify it with its digest to be sure.

Let's be sure this image is identified in one place so any evolution should be propagated everywhere.

**Comment by NicolasT** [comment]
This is not just a MetalK8s concern, of course. Don't spend too much time on this topic right now, once we figure out the right technical approach company-wide, any images built as part of MetalK8s shall abide by these rules.

**Comment by jbertran** [comment]
Topic taken internally by release engineering.
