### ISSUE TITLE
Define a working list of Docker images needed on the bootstrap node

### ISSUE THREAD

**Issue by charlesprost** [scality/metalk8s#562]
In order for the bootstrap node to be able to fulfill its role, it needs Docker images available locally for deployment.
All of them must be built on the same base image as identified in #561 

Here is the first version of the list:

- etcd
- kube-apiserver and other kube-* images in order to build a proper control plane (4 images total)

**Comment by NicolasT** [comment]
Start with the output of `kubeadm config images list` or something like that.

**Comment by charlesprost** [comment]
Done in https://github.com/scality/metalk8s/pull/593/commits/cfe2c5350bb047fcc7421fcfe968178eab482802
