### ISSUE TITLE
salt-master: package `tini`

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#599]
The `salt-master` container developed in #591 uses `tini` as PID1. This is installed from a pre-built binary dropped into the image, rather than from a package.

Either package `tini` and install it, or use a similar tool available in existing repositories.

**Comment by NicolasT** [comment]
We may, actually, not require `tini` at all, because the `pause` process in a `Pod` acts as a reaper (to be investigated).

**Comment by cmonfort** [comment]
As seen with @NicolasT , we'll still use `tini` in metalk8s 2.0 (so no need to change/package anything), but drop it in 2.1 (that will use kubernetes 1.12 where PodShareProcessNamespace feature is enable by default) and leverage on `/pause` process.

**Comment by cmonfort** [comment]
Nothing to do in 2.0, resolved by #825 for 2.x
