### ISSUE TITLE
build/tests: split and document Makefile

### ISSUE THREAD

**Issue by jbertran** [scality/metalk8s#603]
Our root Makefile is starting to get rather long and complicated, and is not documented at all. Let's fix this!

Suggestions:

* Split the Makefile into sub-files according to their responsibilities - OCI, RPM, build orchestration, tests...
* Make an effort to document at least the high-level workflow of each sub-file, and the important "magic" environment variables that exist
* Add more information to `README.md` so a user can easily bootstrap a working build/test environment without having to hunt for the requirements and useful commands.

- [ ] #617 - OCI images
- [ ] #618 - RPMs 
- [ ] #619 - Salt

**Comment by slaperche-scality** [comment]
Done/made obsolete as a side-effect of https://github.com/scality/metalk8s/issues/708.
