### ISSUE TITLE
Build (or update) the Vagrantfile to test the bootstrapping process in a clean environment

### ISSUE THREAD

**Issue by charlesprost** [scality/metalk8s#611]
The Vagrantfile should start the right Centos machine, mount the static files (scripts/packages/docker images) from the build path, and execute the commands to reach the salt-available state.

Of course, it depends on:
- having run the make command in order to build/download all static files in one location
- having listed and tested the bootstrapping commands

**Comment by NicolasT** [comment]
`make vagrantup` ?

**Comment by charlesprost** [comment]
> `make vagrantup` ?

Seems like it. I've been reviewing an old TODO list and trying to identify what is missing. So you would say it's done?

**Comment by sayf-eddine-scality** [comment]
Yes +1 for closing this, `make vagrantup` does the Job, unless we want to add a target for `vagrant halt` somewhere

**Comment by charlesprost** [comment]
Already done thanks to `make vagrantup`
