### ISSUE TITLE
List bootstrapping commands in order to reach the salt-available state

### ISSUE THREAD

**Issue by charlesprost** [scality/metalk8s#612]
See https://bitbucket.org/scality/ring/src/e2e77dac77f42ac42fc32ff6f199d01668c311e5/buildchain/layers/repository/salt/

They are the commands we need to run, based on the static files available, to reach the state when we have a salt master and the local minion is now a non-local-only minion.

**Comment by charlesprost** [comment]
@NicolasT is this done also?

**Comment by NicolasT** [comment]
Hmh, not sure what this is about? @nootal

**Comment by charlesprost** [comment]
It's done in alpha1.
