### ISSUE TITLE
build: split RPM package creation from main Makefile

### ISSUE THREAD

**Issue by jbertran** [scality/metalk8s#618]
* Using an `include` in the main Makefile, split the RPM building targets from the main Makefile.
* Document the different steps as much as possible, so that a newcomer may easily understand the workflow of the Makefile.

Part of #603

**Comment by gdemonet** [comment]
Since RPM packages and repositories are quite independent from the other build targets, one can define an independent `Makefile` and run it as a "sub-`Make`" from the main one.

Here's a draft PR (#748) to show how it might look, so that we have grounds for comparing with `doit` (#708).

**Comment by slaperche-scality** [comment]
Done/made obsolete as a side-effect of https://github.com/scality/metalk8s/issues/708.
