### ISSUE TITLE
Declare CA minion in pillar

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#632]
Currently we use mine to declare salt-minion to use as CA. 

This information should be in the pillar or something else but static information.

**Comment by NicolasT** [comment]
It can go in the `bootstrapConfiguration` I guess?

**Comment by NicolasT** [comment]
(In which case the CA 'role' should not be derived from a K8s `Node` label, but set differently, somehow).

**Comment by NicolasT** [comment]
#932
