### ISSUE TITLE
Fix bootstrap script mounting point

### ISSUE THREAD

**Issue by jbertran** [scality/metalk8s#634]
Replace the hardcoded /var/scality/metalk8s-dev with the calculated product version, using a `get_product_version.sh` so we get version stuff in the CI too.

Needed in:
* `bootstrap.sh` for absolute paths
* `VagrantFile` for iso mountpoint

**Comment by NicolasT** [comment]
You don't need `get_product_version.sh`. You know you have everything at `/vagrant`, so you can use `product.txt` from `/vagrant/_build/root`, which is the intent for that file to exist in the first place.

**Comment by jbertran** [comment]
> You don't need `get_product_version.sh`. You know you have everything at `/vagrant`, so you can use `product.txt` from `/vagrant/_build/root`, which is the intent for that file to exist in the first place.

Eve needs an executable file with that name located next to `main.yaml` in order to work out the version of the current build. We want this because:

* currently the build artifacts are generated as `[...]metalk8s:staging-0.0.0`
* we want the version so that the buildbot version variable is defined, so that we can mount the ISO on the correct path without doing custom stuff with product.txt.

**Comment by jbertran** [comment]
Closed by GH-646.
