### ISSUE TITLE
De-duplicate image listing, versions,...

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#640]
It'd be really good to have this list somewhere else, where the build infrastructure also retrieves it from, etc.

_Originally posted by @NicolasT in https://github.com/scality/metalk8s/pull/604/review_comment/create_

**Comment by jbertran** [comment]
This should wait for a build system refactor - then we can specify on build, image by image whether or not it should be added to the registry.

**Comment by gdemonet** [comment]
Could be useful to be able to read this source of information from docs as well, since some expected outputs include versions (notably, K8s version).

**Comment by gdemonet** [comment]
Done (see #1477).
