### ISSUE TITLE
Pin upstream package versions for offline repository creation

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#666]
Let's get #643 in and focus on having this repo used on the node, and create a tracking ticket for package version pinning and move that to `-alpha2`.

_Originally posted by @NicolasT in https://github.com/scality/metalk8s/pull/643#issuecomment-467792843_

**Comment by slaperche-scality** [comment]
Is this done?

I think we pin most of the things (maybe too much in fact) now, no?

**Comment by gdemonet** [comment]
I guess we can close this yes, #1530 is even about "unpinning" some of those

**Comment by gdemonet** [comment]
That was done a long time ago (I think in #698).
