### ISSUE TITLE
Perform K8s API operations from Salt master

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#691]
So, here's the deal: currently, we run all these states on the `bootstrap` minion, which may be fine, but is not OK once we grow the cluster and such. The rationale is simple: this state (and others) should run just once.

This relates to #626 which would allow us to run this state only once, on the Salt master. In order for that to work, the master indeed needs creds, and ideally those are referred to from its configuration file, which we can do.

As to which creds to use: I'd like to create a `ClusterRole` and a `Role` that grants whatever access the Salt master requires to do its job (we can create those using the `admin` creds), then create a cert for the Salt master with bindings to said `(Cluster)Role`. That way, we can deploy Salt master(s) without handing out any non-required authorizations.

_Originally posted by @NicolasT in https://github.com/scality/metalk8s/pull/689/review_comment/create_

**Comment by NicolasT** [comment]
I believe this is done now, right @TeddyAndrieux ?

**Comment by TeddyAndrieux** [comment]
Yes I think
