### ISSUE TITLE
Upgrade to Helm v2.11 or newer

### ISSUE THREAD

**Issue by ssalaues** [scality/metalk8s#707]
Helm v2.11 updates their template functions library `Sprig` to v2.16.0 which added several new useful functions that are helpful in advanced templating such as `slice`. It would be nice if we could upgrade to Helm 2.11 on future release versions of MetalK8s.

I don't mind making the changes and PR but wanted to open the issue first.

**Comment by NicolasT** [comment]
PR welcome :)

**Comment by ssalaues** [comment]
Created the PR and tested locally. I don't have permissions to add reviewers so just wanted to update the status here 😃

**Comment by NicolasT** [comment]
This is now in `development/1.1`, about to land in branches up to `development/1.3`.

**Comment by NicolasT** [comment]
All done.
