### ISSUE TITLE
Create development/2.1 branch

### ISSUE THREAD

**Issue by ramanduh** [scality/metalk8s#711]
- [x] Create a new development branch from berte administration board that waterfall from devel/2.0

**Comment by jbertran** [comment]
The build for any PR related to this will fail due to #651 having been fixed with hardcoded `2.0` references. This needs to be fixed (i.e. version needs to be either obtained via saltenv, or a custom module hard-coded _on build_) before this and the following #712 can be done.

**Comment by ramanduh** [comment]
Closed by https://github.com/scality/metalk8s/pull/801/
