### ISSUE TITLE
Create development/2.2 branch

### ISSUE THREAD

**Issue by ramanduh** [scality/metalk8s#712]
Create development/2.2 that waterfall from devel/2.1

**Comment by jbertran** [comment]
The build for any PR related to this will fail due to #651 having been fixed with hardcoded `2.0` references. This needs to be fixed (i.e. version needs to be either obtained via saltenv, or a custom module hard-coded _on build_) before this can be done.

**Comment by ramanduh** [comment]
Closed by https://github.com/scality/metalk8s/pull/805/
