### ISSUE TITLE
Have a E2E testing environment available

### ISSUE THREAD

**Issue by charlesprost** [scality/metalk8s#714]
- [x] Decide which end-to-end testing framework we want to have (pytest/behave)
- [x] Bootstrap virtual env

Success if defined by having the command available in the environment (for example, being able to run `behave -h`).

**Comment by charlesprost** [comment]
We can use this as inspiration: https://bitbucket.org/scality/test-supervisor-bdd-behave/src

**Comment by sayf-eddine-scality** [comment]
closing this issue as decisions have been made
