### ISSUE TITLE
Check the salt-master and salt-minion(s) are properly configured

### ISSUE THREAD

**Issue by charlesprost** [scality/metalk8s#720]
- [ ] Following #716 : have this test in Vagrant environment
- [ ] Following #717 : have this test in CI environment

Success is defined by making sure the salt-master and salt-minion(s) are properly configured.

@TeddyAndrieux any idea what to check in order to test this?

**Comment by TeddyAndrieux** [comment]
Honnestly for me we should have unit test for salt but E2E for salt configuration is not needed I think (at least for the moment)
