### ISSUE TITLE
Make sure the UI is accessible outside of the K8S nodes

### ISSUE THREAD

**Issue by MonPote** [scality/metalk8s#729]
Some change may need to be done in order for the UI to be accessible outside of the K8S nodes (Need some investigation)

**Comment by NicolasT** [comment]
This should be done using an `Ingress` object at some point, but as long as we don't deploy an `Ingress` controller, that won't work.

We can instead deploy a `Service` of type `NodePort` for the time being.

**Comment by MonPote** [comment]
Here a small summary of what we discuss : 
1. Reverse proxy is not appropriate, because it's a back channel to the apiserver that we don't want to have (in order to let clients decide to lock down the apiserver if they want)

2. For configuration of the endpoints (apiserver, dex, grafana...), we use the same configmap approach as branding

3. For now, `--cors-allow` or whatever is fine

**Comment by NicolasT** [comment]
I'd really like to see a test as part of this PR, which validates the `index.html` can at least be retrieved from the `NodePort` (no need to test much more than that, maybe retrieve the `config.js` and validate the API-server address in there?)

May make sense for @sayf-eddine-scality or someone else in the @scality/metalk8s team to help on this :)

**Comment by carlito-scality** [comment]
@NicolasT ok I created https://github.com/scality/metalk8s/issues/820

**Comment by NicolasT** [comment]
> @NicolasT ok I created #820

Not sure how this relates?
