### ISSUE TITLE
Orchestrate runner to boostrap worker node

### ISSUE THREAD

**Issue by sayf-eddine-scality** [scality/metalk8s#735]
This runner, executed from the salt master, should, on a fresh new node with only salt-minion installed and linked to the master:
* setup containerd
* prepare certs
* setup kubelet (disabling self-registration is important)

In a workload plane node, there is:
* no master label
* no role taint
* no manifests in /etc/kubernetes/manifests
* no files used by those manifests only

Success: the orchestrate can transform a salt-minion-ready node into a node able to launch containers and part of the cluster (that means having kubelet talking to the apiserver)

**Comment by cmonfort** [comment]
Must be done after #626 has landed.
