### ISSUE TITLE
Orchestrate runner to build a control plane node on top of a workload plane node

### ISSUE THREAD

**Issue by sayf-eddine-scality** [scality/metalk8s#736]
Reuse the worker plane orchestration runner steps #735

A control plane node is first a workload plane node, then we run a few more steps on it.

For this issue, we don't care about the etcd cluster. Let's consider etcd is running in the bootstrap node only.

**Comment by NicolasT** [comment]
What's the question?

**Comment by sayf-eddine-scality** [comment]
> What's the question?
Will we be replicating the control plane on every node or for some of them, what would we be deploying exactly
