### ISSUE TITLE
Annonce New node in the API and populate needed information

### ISSUE THREAD

**Issue by sayf-eddine-scality** [scality/metalk8s#737]
Create a node object in the current API declaring the new node to join the cluster
Use the appropriate taints and labels to make it a member of the control plane
Populate the object with connection information to be used by salt-master to connect to the new node

Success: have a YAML file (see the one from https://github.com/scality/metalk8s/pull/815#issue-263185568) that contains also taints and labels so the declared node would be a part of the control plane. Use `kubectl create -n "kube-system" -f <yaml_file>` to declare the node.

**Comment by charlesprost** [comment]
@sayf-eddine-scality @NicolasT I'm trying to make sure all tickets for the control plane expansion are ready.

I'm not sure to understand this one: what would be the output?

Is it "just" a YAML file as in https://github.com/scality/metalk8s/pull/815#issue-263185568 or is it something else? is it in the doc as an example or should we have a file in the repo?

**Comment by NicolasT** [comment]
Will likely be a YAML template which can be `kubectl apply`d indeed. At some later point in time we may want to wrap some CLI utility around this, but for now YAML + `kubectl` should do.
