### ISSUE TITLE
Extend etcd cluster over the new node

### ISSUE THREAD

**Issue by sayf-eddine-scality** [scality/metalk8s#738]
This is a bit tricky, you need to:
* Annonce the extension cia etcdctl
* start the etcd container with option to join an existing cluster ( beware not to start it as a new cluster, you need to update the manifest so it does not create a new cluster each time it restart )

**Comment by slaperche-scality** [comment]
TODO:

## Automatically push the `etcd` endpoints in the mine

1. Write a custom module with a function `get_control_etcd_ips`: push IPs if `etcd` is running (for v1 we will simply check if a pod `etcd` is running)
2. use this functions in `pillar/mine_functions.sls`

## Deploy a new `etcd` node

In a new orchestrate, `deploy_etcd_on_new_node.sls`:

- Create the certificates for etcd
    - `salt 'node1' state.apply saltenv=metalk8s-2.0 metalk8s.kubeadm.init.certs.etcd-server`
    - `salt 'node1' state.apply saltenv=metalk8s-2.0 metalk8s.kubeadm.init.certs.etcd-peer`
    - `salt 'node1' state.apply saltenv=metalk8s-2.0 metalk8s.kubeadm.init.certs.etcd-healthcheck-client`
- Dump the `etcd` CA certificate (required to start `etcd`)
- Update the mine (to be sure to have an up-to-date list of cluster members).
- Spawn the new etcd by calling the state `metalk8s.bootstrap.etcd`
    - in this state we get the `etcd` IPs from the mine (if list empty, `state=new`, else `state=existing`)
    - we add IP of the current node to the set (will be used as `initial-cluster` value
    - spawn `etcd`
    - Update the mine with our IP
- Register the `etcd` node in the `etcd` cluster using `etcdctl`:
    - get the minion-id of a node with `etcd`
    - execute `cmd.run` (or python k8s client API) on this minion to run the `etcdctl` command through `kubectl` to add the new node


Edit: updated according to Charles' comment.

**Comment by charlesprost** [comment]
- see dudu's work; you need to dump the etcd CA crt in the new node before starting the pod
- don't forget in the orchestrate to update the mine before getting ips
- second update is done in the state and the first in the orchestrate
- cmd.run or call to apiserver through the python client to exec a command on a specific pod

**Comment by NicolasT** [comment]
See especially comment https://github.com/scality/metalk8s/pull/869#discussion_r269729152

I'm not sure we should retrieve the cluster layout from the mine. What if instead we retrieve a list of nodes that make up the control-plane by querying the API (or, from a Salt point-of-view, it's actually a dynamic pillar which queries the info from the API), then retrieve each node's control-plane address from the mine (it should be published already at that stage...), then create the peer list?

The only drawback I see using that approach is that we need a the K8s API to be available, so when things blow up and the API is not available, this state can't run.

In any case, I'm not sure the peer list must be exhaustive anyway? Are we sure that's the case?

**Comment by NicolasT** [comment]
So, peer list passed as `--initial-cluster` must be exhaustive (tried it).

Another thing: an `etcd` node won't start if it's not (yet) registered in the cluster (`etcdctl member add ...`). However, that's not an issue: the Pod would die after we deploy the manifest until we run `etcdctl member add`, but that's fine, `kubelet` will restart it anyway.

**Comment by NicolasT** [comment]
> in this state we get the etcd IPs from the mine (if list empty, state=new, else state=existing)

I'm a bit worried about this one (hence the comment about using the API info above). Basically, it relies on members having sent their info into the mine. If that didn't happen (for whatever reason), and we deploy a new node, we could end up with a 'new' cluster.

The mine isn't/can't be a source of truth for non-existence of things.

**Comment by NicolasT** [comment]
> execute cmd.run on this minion to run the etcdctl command through kubectl to add the new node

and

> cmd.run or call to apiserver through the python client to exec a command on a specific pod

Maybe for now, but there's definitely debt then. What we should do instead is

- provision an etcd client cert for `salt-master`, similar to how we'll create a `kubeconfig` file for it
- add the `python-etcd3` package in the `salt-master` image
- create a Salt module to manage `etcd` members in a cluster, given the above client cert
- use this module to add the new node as a member, *on the `salt-master host`*

**Comment by slaperche-scality** [comment]
Thanks for your comments.

About using the API instead of relying on the members pushing their info in the mine that was the alternative we considered yesterday, but given the time constraints we went with the mine approach.

I'll create a improvement ticket (#877) to keep track of that one, because using the API seems to be a more reliable approach!

As for `cmd.run` you're right, I'll create a debt ticket to use `python-etcd3` instead (#878).

**Comment by slaperche-scality** [comment]
Current state (pushed in review):

Everything is done except the last part, namely:
- Register the `etcd` node in the `etcd` cluster using `etcdctl`:
    - get the minion-id of a node with `etcd`
    - execute `cmd.run` (or python k8s client API) on this minion to run the `etcdctl` command through `kubectl` to add the new node
