### ISSUE TITLE
Clean Makefile output from useless prints

### ISSUE THREAD

**Issue by charlesprost** [scality/metalk8s#755]
When running the `make` command, the output contains some useless progress bars. Let's get rid of them.

**Comment by NicolasT** [comment]
That's the `docker pull` invocation, I guess? Isn't it printing this based on the terminal in use (if any)? If that's the case, we could maybe set another `TERM` in the CI environment?

**Comment by NicolasT** [comment]
Also, let's not spend too much effort on something like this when `make` may be kicked out entirely...

**Comment by charlesprost** [comment]
No, just some `curl` commands and the `mkisof` one, I've done this in drive-by while looking at the output.

**Comment by NicolasT** [comment]
Ah, `curl -s` and `mkisofs -quiet`.

We could turn `curl` and `mkisofs` invocations into

```make
CURL ?= curl
MKISOFS ?= mkisofs
...
foo:
    $(CURL) ...
```

and then, in an environment where progress is not wanted,

```shell
make CURL='curl -s' MKISOFS='mkisofs -quiet'
# Or export the variables in the environment, e.g. in CI
```

**Comment by charlesprost** [comment]
@NicolasT yeah we could do this, could be interesting. I'll create a ticket but we don't need to tackle it right now.
