### ISSUE TITLE
Remove address lookup duplication

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#757]
Currently, we spread things like

```
{% from "metalk8s/map.jinja" import networks with context %}
{% set ip_candidates = salt.network.ip_addrs(cidr=networks.control_plane) %}
```

around in the SLS files, which ain't nice.

We should calculate this value somehow once, and then be able to reference it from a single location.

Similarly, we should be able to look up such addresses of *other* nodes, e.g. to construct `etcd` peer lists.

How this should be done is TBD.

**Comment by TeddyAndrieux** [comment]
The method to get the Ip is already done by #833 (custom modules `metalk8s.get_control_plane_ips` and `metalk8s.get_workload_plane_ips`) 
Just thinking that could be a custom grains which is better 

Edit: Oh indeed we have an issue for the moment as we need pillar information to get the Ip so we can't put it in a custom grains

**Comment by NicolasT** [comment]
Can minions request grains from other nodes?

**Comment by TeddyAndrieux** [comment]
Not directly but you can have grains value in the mine
```
mine_functions:
  toto:
    - mine_function: grains.get
    - toto
```

**Comment by NicolasT** [comment]
#970
