### ISSUE TITLE
Make verbose commands depending on the environment

### ISSUE THREAD

**Issue by charlesprost** [scality/metalk8s#758]
Related to #755 

Depending on the environment (CI/local/debug...) we may want some commands to be verbose or not:

- `curl` or `curl -s`
- `mkisofs` or `mkisofs -quiet`
- `docker pull`...

As proposed by @NicolasT we could turn `curl` and `mkisofs` invocations into:
```make
CURL ?= curl
MKISOFS ?= mkisofs
...
foo:
    $(CURL) ...
```

and then, in an environment where progress is not wanted,

```shell
make CURL='curl -s' MKISOFS='mkisofs -quiet'
# Or export the variables in the environment, e.g. in CI
```

**Comment by slaperche-scality** [comment]
@nootal is this still relevant?

`curl` not used anymore, `docker` is used through the API and `-quiet` is enforced for `mkisofs`.
Moreover, we no longer use `make` and `doit` hide `stdout` (except if the task fails).

**Comment by charlesprost** [comment]
Not relevant anymore.
