### ISSUE TITLE
Deploy `prometheus-operator` as a cluster service

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#786]
**Goal:**
Create salt states to deploy prometheus-operator with kubelet using manifests.

**Dependencies:**
- [x] #997

**Details:**

In order to deploy prometheus-operator, we need to create the following objects (based on kube-prometheus manifests):

Namespace:
  - monitoring: https://github.com/coreos/prometheus-operator/blob/v0.24.0/contrib/kube-prometheus/manifests/00namespace-namespace.yaml

CRDs:
  - AlertManager: https://github.com/coreos/prometheus-operator/blob/v0.24.0/contrib/kube-prometheus/manifests/0prometheus-operator-0alertmanagerCustomResourceDefinition.yaml
  - Prometheus: https://github.com/coreos/prometheus-operator/blob/v0.24.0/contrib/kube-prometheus/manifests/0prometheus-operator-0prometheusCustomResourceDefinition.yaml
  - PrometheusRule: https://github.com/coreos/prometheus-operator/blob/v0.24.0/contrib/kube-prometheus/manifests/0prometheus-operator-0prometheusruleCustomResourceDefinition.yaml
  - ServiceMonitor: https://github.com/coreos/prometheus-operator/blob/v0.24.0/contrib/kube-prometheus/manifests/0prometheus-operator-0servicemonitorCustomResourceDefinition.yaml

Deployment: https://github.com/coreos/prometheus-operator/blob/v0.24.0/contrib/kube-prometheus/manifests/0prometheus-operator-deployment.yaml
ServiceAccount: https://github.com/coreos/prometheus-operator/blob/v0.24.0/contrib/kube-prometheus/manifests/0prometheus-operator-serviceAccount.yaml
ClusterRole: https://github.com/coreos/prometheus-operator/blob/v0.24.0/contrib/kube-prometheus/manifests/0prometheus-operator-clusterRole.yaml
ClusterRoleBinding: https://github.com/coreos/prometheus-operator/blob/v0.24.0/contrib/kube-prometheus/manifests/0prometheus-operator-clusterRoleBinding.yaml
Service: https://github.com/coreos/prometheus-operator/blob/v0.24.0/contrib/kube-prometheus/manifests/0prometheus-operator-service.yaml
ServiceMonitor: https://github.com/coreos/prometheus-operator/blob/v0.24.0/contrib/kube-prometheus/manifests/0prometheus-operator-serviceMonitor.yaml

These manifests should maybe not be used as-is, but rather tuned to fit our needs.
Also, these manifests are those for the 0.24.0 version (the one compatible with development/2.0), they must be changed for development/2.1 & development/2.2 branches to use respectively 0.28.0 & 0.29.0 versions.

**Comment by alexandre-allard** [comment]
Done in #1119
