### ISSUE TITLE
Rework UI container build process

### ISSUE THREAD

**Issue by MonPote** [scality/metalk8s#797]
Rework the build following the SaltGui one cf. ca5e8ff

**Comment by charlesprost** [comment]
@MonPote please add more information

**Comment by slaperche-scality** [comment]
Issue is lacking details.

@MonPote is this issue still relevant?
If yes, please add details, if no let's close it :slightly_smiling_face:

**Comment by NicolasT** [comment]
This may be lacking details, but why would it no longer be relevant? @MonPote @slaperche-scality 

IMHO there's no reason to close this...
