### ISSUE TITLE
Rework Makefile UI build 

### ISSUE THREAD

**Issue by MonPote** [scality/metalk8s#819]
Rework the Makefile part of the UI build to fit like this PR :
https://github.com/scality/metalk8s/pull/816/files#diff-b67911656ef5d18c4ae36cb6741b7965R26

**Comment by NicolasT** [comment]
This is #797 ?

**Comment by MonPote** [comment]
> This is #797 ?

Oh, I just understand your PR solve #797 . I will close this issue. Thanks.
