### ISSUE TITLE
Rename/move states to group them and set the right state name 

### ISSUE THREAD

**Issue by cmonfort** [scality/metalk8s#823]
State `salt/metalk8s/bootstrap/certs/clients.sls` could be renamed to something more meaningful, as it does not deal only with client certificates...

**Comment by TeddyAndrieux** [comment]
General comment:
We should refactor all our states as we no longer stick to kubeadm style (and btw it's good).

And maybe group by "service" or by "type" **TBD**

Example:
1. by service: All kubelet states in the same directory (kubelet-start, kubelet cert, kubelet kubeconfig)
2. by type: All certs states in the same directory, all kubeconfig in the same directory, ...

Personnaly prefer to group by service (1.)

**Comment by TeddyAndrieux** [comment]
Just updated the title of the issue to make it more global

**Comment by gdemonet** [comment]
+1 for grouping by service, it's much easier for discovering available formulas for a given service

**Comment by NicolasT** [comment]
+1 by service.

**Comment by TeddyAndrieux** [comment]
Ok lets group by service :) 

What need to be done

- [x]  Have a top-level `kubernetes` directory for all kubernetes salt states
- [x] Grouping CA salt states in one directory
- [x] Regroup all runners/orchestrate in dedicated directory
- [x] 1:1 mapping between roles and highstates
- [x] Move calico to a "CNI" directory
- [x] runc should be part of containerd
- [x] SA into `kubernetes` directory
- [x] Addons directory containing UI, prometheus, ...
- [x] Kube-proxy, coredns should move to `kubernetes` directory it's not "real addons" it's mandatory
- [x] `deployed.sls` it's for state that should only run on the master
- [x] move `req` to `internal` directory
- [x] don't use `pod` suffix in manifest file name

**Comment by TeddyAndrieux** [comment]
Above comment edited to include task list
