### ISSUE TITLE
Investigate Dex as OIDC provider

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#83]

**Comment by NicolasT** [comment]
https://github.com/kubernetes/charts/tree/master/stable/dex

**Comment by Ebaneck** [comment]
@NicolasT are there any current known drawbacks as to why we are not adding something like `keycloak` to our possible choice of Identity management providers list to investigate??. -> https://robertbrem.github.io/Microservices_with_Kubernetes/16_SSO_with_Keycloak/01_Setup_Keycloak/

**Comment by gdemonet** [comment]
@Ebaneck we don't want to manage a full-fledged solution for Identity management if there's no explicit need to do so. Dex plugs with external IdPs, that's what we're aiming for in production sites.

**Comment by NicolasT** [comment]
See https://github.com/scality/metalk8s/issues/84

As @gdemonet said, we don't want to integrate some heavyweight identity system and rather rely on external systems, integrating with those. Something like Keycloak would enforce deploying, managing, backing up,... some SQL server system, and whatnot.

The primary intent now is to ensure all services work with *a* OIDC provider, as simple as possible. If there's real-world need, later on we can integrate a more complicated solution.

**Comment by NicolasT** [comment]
Given we know this work for API access, UI access and Grafana, no more investigation to be done.
