### ISSUE TITLE
Keep build infra under `_build`

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#838]
Would it be possible to store `.doit.db` in `_build`, as well as the `.venv` we set up to run `doit`? It's good practice to keep 'non-source' stuff outside source folders whenever possible.

**Comment by slaperche-scality** [comment]
Yes, it's doable:
- I create the virtualenv, so obviously I can create it elsewhere
- the location of the `doit` DB can be configured with the `dep_file` entry in `doit.cfg`

Now, I'm not sure that moving those into the `_build` directory is a good move (though I understand the desire/advantage to put build-generated stuffs out of the source tree).

The first problem we have is that currently the creation of the buildroot (`_build`) is handled by `doit`, which needs its virtualenv to run: we would have a " chicken or the egg" problem here.

Could be solved by moving the "ownership" (and responsibility to create it, but also of destroying it) of `_build` from `doit` to `doit.sh`.

Still, I see another problem: now, every `doit` command will create this `_build` directory even if it's not necessary (`doit lint` for instance, but also `doit list`, `doit info`, …) that's not really clean (IMHO).

I know that linter could be run out of `doit`, using `tox`-only directly, but as mentioned in our previous discussion:
- we lack an easy way to run all the linter in a single `tox` command
- if possible I would like to keep using tox for what it's good (creating and managing virtual environment), same for `doit` (running commands).
- that won't solve the spawn of a rogue `_build` directory for other legit but not build-related commands (`list`, `help`, `info`, …).

**Comment by NicolasT** [comment]
> Could be solved by moving the "ownership" (and responsibility to create it, but also of destroying it) of _build from doit to doit.sh.

I disagree. Yes, `doit.sh` should create `_build/doit` (the venv), but the `doit` tasks should still depend on `_build` to exist/be created (which, granted, should always be the case when using `doit.sh`, but not when one happens to have `doit` installed system-wide and invoke it accordingly for whatever reason).

Basically, I think the current approach of "fail when `_build` wasn't created by `doit`, recorded in its database" is wrong. The aim for `doit` (and relevant tasks) is not *to create `_build`*, but the target is *for `_build` to exist* for future use by other targets of which `_build` is a dependency. Whether `doit` created the directory or not is irrelevant.

> Still, I see another problem: now, every doit command will create this _build directory even if it's not necessary (doit lint for instance, but also doit list, doit info, …) that's not really clean (IMHO).

Well, if the venv is `_build/doit`, then `_build` would always need to exist, even to run `./doit.sh list`, which I don't think is an issue. Why would this not be 'clean'? `doit` is the build infra, `doit list` is just invoking the build infra with a specific target/aim.

Basically, if today I `rm -rf _build` and then run `./doit.sh`, it fails. That's counter-intuitive, to say at least.

**Comment by slaperche-scality** [comment]
> the target is for _build to exist for future use by other targets of which _build is a dependency. Whether doit created the directory or not is irrelevant.

Ok, then what I can do for `_build` is to create if (and be OK if it already exists) and don't delete it on a `doit clean`. And then either I don't delete it on `clean` or I do an `rm -rf` but then it could hide files I forgot to track :/

> Basically, if today I rm -rf _build and then run ./doit.sh, it fails. That's counter-intuitive, to say at least.

Yeah because `rm -rf` is obviously not `doit` aware, a `doit clean` should be enough (now that you mention it, you may have to pass `--forget` which I should enable as default behavior for `clean`).

OK, I'll first enable `forget` as default for clean to see if it solves our issues and if not then I'll move everything under `_build` and clean will do an `rm -rf`.

**Comment by slaperche-scality** [comment]
Seems like most of the issue disappeared since  #875 and other (stop using `run_once` mainly) so I'll close this one.
