### ISSUE TITLE
Improve tasks that save container images

### ISSUE THREAD

**Issue by slaperche-scality** [scality/metalk8s#839]
Tasks that save containers images relies on the presence of a file on the disk (either the saved image or a `touch`ed file) to know if the image was pulled/built.

It's not enough though, because if you want to use the image later (e.g. with `docker run`) the image must still exists in Docker (having a local save on the disk is not enough because it could have been `docker rmi`ed), thus to be considered up-to-date those tasks must require that:
- a file exists on the disk (already done)
- the image exists in Docker

To meet the last constraint, we can implement a custom method that would check the existence of the image (by checking the return code of `docker inspect --type=image …`) and use this method for the `uptodate` attribute of the task (see doc [here](http://pydoit.org/dependencies.html#attr-uptodate)).

Since this check is common to both pulled and built images, a good place to implement this method is the base class `ContainerImage`.

EDIT: So far, this only concerns the `metalk8s-build` image.

---

To be considered: is the `touch`ed file still useful now that we also check in Docker? I think not, but to be confirmed.

**Comment by NicolasT** [comment]
This would be fixed if we simply use `skopeo copy` to pull-and-archive the image into a target archive, or not even into an archive (#1049) instead of the Docker kludge, so I'd link the tickets and fix this one by merits of #1049.

**Comment by slaperche-scality** [comment]
Hum I'm not sure about it.

What we will tackle in #1049 is the images we serve from the ISO, and the problem here (seeing that I mention `docker run`) is with images such as `metalk8s-build` which are built and then used to build other artifacts (they are not shipped with the ISO).

I'm not sure `skopeo` will help here.

Edit: In fact I think only `metalk8s-build` is concerned here, so I could as well reformulate the issue to clarify it.

**Comment by NicolasT** [comment]
Ah, good point, my bad.
