### ISSUE TITLE
Investigate Keycloak as OIDC provider

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#84]
https://www.keycloak.org/
https://medium.com/@mrbobbytables/kubernetes-day-2-operations-authn-authz-with-oidc-and-a-little-help-from-keycloak-de4ea1bdbbe
https://github.com/mrbobbytables/oidckube

**Comment by NicolasT** [comment]
Also: https://github.com/kubernetes/charts/tree/master/stable/keycloak

**Comment by thomasdanan** [comment]
@NicolasT @gdemonet @Ebaneck Now that we have integrated Dex as OIDC provider in Metalk8s, could we close this issue?

**Comment by Ebaneck** [comment]
> @NicolasT @gdemonet @Ebaneck Now that we have integrated Dex as OIDC provider in Metalk8s, could we close this issue?

Yup for me!
