### ISSUE TITLE
Integrate an OIDC provider

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#85]
Instead of provisioning a single user at deployment time, we should use K8s' OIDC authn support, through an OIDC provide we provision as part of MetalK8s, and which (initially) uses its own user-base. Later on, we can integrate with other authn systems like LDAP, AD,...

Cfr. #83 #84

**Comment by NicolasT** [comment]
To ease token retrieval and `kubeconfig` generation, https://github.com/negz/kuberos could be of use.

**Comment by NicolasT** [comment]
Or https://github.com/mintel/dex-k8s-authenticator

**Comment by NicolasT** [comment]
Difficulty with this one will be how to ease access to the K8s dashboard :-/

**Comment by NicolasT** [comment]
There's now a Kuberos chart: https://github.com/helm/charts/tree/master/stable/kuberos

**Comment by NicolasT** [comment]
Currently this ticket is about

- [x] Deploying Dex in the cluster, from the chart
- [x] Setting up Dex to use a self-signed certificate, stored in a *Secret*, with the CA available in a *ConfigMap* in *Namespace*s where services are running which require access to this file (e.g., Grafana)
- [x] Expose Dex on the control-plane ingress controller
- [x] Configure the Kubernetes API server to use Dex, using the generated CA, using `oidc:` as the prefix of authenticated entities
- [x] Configure the UI to require login through Dex
- [x] Configure Grafana to require login though Dex
- [ ] Create two static users in Dex, one `admin`, one `readonly`, with some predefined (hashed) password
- [x] Add a *ClusterRoleBinding* for the `oidc:admin` user to have full access
- [ ] Add a `metalk8s:readonly` *ClusterRole* which gives reasonable read-only access to some cluster resources (*Node*s, *Namespace*s, *Pod*s, *Volume*s, *PersistentVolume*s, maybe some others)
- [ ] Add a *ClusterRoleBindding* for the `oidc:readonly` user to the `metalk8s:readonly` *ClusterRole*

**Comment by thomasdanan** [comment]
Dex is now embedded in metalk8s 2.X and some admin user is pre-provisioned. Closing this one.
