### ISSUE TITLE
Review storage provisioning

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#87]
Related to #1 

We currently pre-provision a couple of LVM2 Logical Volumes of specific sizes and inject these as `PersistentVolume`s resources. This is a somewhat inflexible approach.

Though we likely should keep using LVM2 as a  base storage technology, using e.g. CSI (as suggested by @Zempashi) could make this somewhat more flexible. CSI is, however, not yet entirely stable.

There's an LVM2 CSI driver from MesosSphere we may want to use or contribute to (https://github.com/mesosphere/csilvm, https://mesosphere.com/blog/open-source-storage-ecosystem/). There's another plugin at https://github.com/wavezhang/k8s-csi-lvm which seems less polished.

**Comment by Zempashi** [comment]
https://ember-csi.io/ one more in the list

**Comment by NicolasT** [comment]
Link dump:

https://github.com/kubernetes-incubator/external-storage/issues/651
https://github.com/kubernetes/community/pull/1914
https://github.com/kubernetes-incubator/external-storage/issues/1015

**Comment by NicolasT** [comment]
@Zempashi I briefly looked into EmberCSI in the past, and had some concerns (maybe unwarranted, though):

- It requires a Cinder setup, which is quite a big deal
- If I'm not mistaken it creates Cinder volumes, then exposes them in K8s over iSCSI or whatever NAS/SAN protocol, so the storage is remote, not local...
- It requires a stateful data storage system setup somewhere. Ideally I think an LVM-based solution should only rely on what's available in the K8s API, and what's presented by the LVM subsystem on the local machine, instead of requiring some extra database to be deployed.

**Comment by Zempashi** [comment]
yes I had the same concern

**Comment by thomasdanan** [comment]
@slaperche-scality @gdemonet @NicolasT is this issue makes sense in the context of https://github.com/scality/metalk8s/issues/1997 epic? or should we close it?

**Comment by gdemonet** [comment]
Implementation of the Storage Operator was already sufficient to close this issue IMO. Considerations w.r.t to using a CSI driver discussed here are not applicable to our Operator.

**Comment by thomasdanan** [comment]
CSI driver not applicable to Metal2 Storage Operator
