### ISSUE TITLE
Use python-etcd3 instead of call to etcdctl

### ISSUE THREAD

**Issue by slaperche-scality** [scality/metalk8s#878]
Instead of issuing call to the `etcdctl` binary, we should use the `etcd` API through  `python-etcd3`.

This would requires:
- provision an etcd client cert for salt-master, similar to how we'll create a kubeconfig file for it
- add the python-etcd3 package in the salt-master image
- create a Salt module to manage etcd members in a cluster, given the above client cert
- use this module to add the new node as a member, on the salt-master host
 
Source: https://github.com/scality/metalk8s/issues/738#issuecomment-477402323

**Comment by TeddyAndrieux** [comment]
Also need to be replaced in etcd upgrade orchestrate 
https://github.com/scality/metalk8s/pull/1030#discussion_r280584127
