### ISSUE TITLE
Use Vagrant snapshot features in DoIt

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#880]
Currently, developers trying to run a bootstrap deployment in a fresh Vagrant environment can either do so from scratch every time (i.e. `vagrant destroy -f` before running `./doit.sh vagrantup`), or using snapshots (i.e. `vagrant snapshot restore bootstrap my_snapshot`).

In any case, neither of these two approaches are used in the current buildchain, and developers still require manual action.

We advocate that:
- [ ] `doit vagrantup` depends on a snapshot being created for the un-provisioned VMs
- [ ] `doit clean vagrantup` restores said snapshots

**Comment by slaperche-scality** [comment]
For the `doit clean vagrantup` part it's clearly doable with a custom clean actions, see [here](http://pydoit.org/cmd_other.html#clean).
