### ISSUE TITLE
Improve "bootstrap re-run" test

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#881]
Currently, the test scenario is:

```
Given bootstrap was run once
When we run bootstrap a second time
Then the Kubernetes API is available
```

This means the test execution will run the bootstrap twice, even though the test is run after an initial bootstrap was already run.
An acceptable solution, since we already mark this test as `@post`, would be to only run it in the `When`:

```diff
-Given bootstrap was run once
+Given the Kubernetes API is available
 When we run bootstrap a second time
 Then the Kubernetes API is available
```

**Comment by NicolasT** [comment]
That's some low-hanging fruit to speed up CI... Any takers @scality/metalk8s ?
