### ISSUE TITLE
Expose control- and workload-plane networks to bastion VM in multi-nodes deployment

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#889]
The current multi-nodes deployment in Eve is done as follows (roughly):

1. We spawn an Openstack worker, later named **the Bastion**
2. From the Bastion, we run a Terraform plan to spawn a **Bootstrap** node, with a few other **Nodes** for cluster expansion

The Bastion is thus responsible for creating the networks used by Bootstrap and the other Nodes. However, contrary to the local Vagrant configuration, the Bastion cannot attach itself to these networks. When we run the test suite remotely from the Bastion (as we would locally, outside of the Vagrant VMs), it thus cannot use the IPs from said networks, which will prevent the tests to access the deployed services through HTTP(S) (currently, most of the tests use SSH to run `kubectl` directly on the bootstrap node).

Exposing such networks to the Bastion should be done as soon as possible to avoid adding too many workarounds in our test suite.

**Comment by charlesprost** [comment]
Another option, maybe technically easier than exposing internal networks to the CI worker, could be by creating a true bastion/client that is part of the internal networks, but not part of the k8s cluster.

So the CI worker would have to create another machine, integrate it into the k8s networks, and execute the test suite from it. That would mean cloning the repo (or at least the test suite) on this new VM, and installing dependencies.

cc @gdemonet

**Comment by gdemonet** [comment]
That is a solution indeed, but it means adding a bunch of `ssh` and `scp` steps to run tests and retrieve their results for pushing into artifacts. I'll try to setup an IP-IP tunnel, propose a PR, and if it's deemed readable enough by the team, merge it.

The biggest advantage of such an approach is the similarity with our local Vagrant deployment (no ssh involved).

**Comment by gdemonet** [comment]
Closed by #988
