### ISSUE TITLE
Review name used in the Salt mine

### ISSUE THREAD

**Issue by slaperche-scality** [scality/metalk8s#890]
Some names, such as `kubernetes_etcd_ca_server` are a bit odd (e.g. `sth_sth_ca_server` to represent a certificate).

We may want to review the naming of what we put in the mine, to check if the name used are meaningful.

_Originally posted by @NicolasT in https://github.com/scality/metalk8s/pull/869_

**Comment by sayf-eddine-scality** [comment]
target branch should be 2.0
