### ISSUE TITLE
Ensure Salt minion ID equals Kubernetes node ID

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#895]
When deploying Salt minion, we must (pre)configure the `minion_id` to match the node name as registered in Kubernetes, since we need this information to match nodes to minions at certain places (e.g. `ext_pillar`).

**Comment by slaperche-scality** [comment]
Where/when should we set the `minion_id` and where its value should come from?

Is it during one of the steps of `deploy_salt_minion_on_new_node.sls`?

**Comment by NicolasT** [comment]
When installing `salt-minion`, before starting it. It's a file in `/etc/salt`. The value should be the name of the node as it's created in the K8s API. This name is known when the orchestration is invoked, and can as such be passed along.

**Comment by TeddyAndrieux** [comment]
For me should be part of the state `salt/metalk8s/salt/minion/configured.sls`.

I think we should retrieve it from k8s as an external pillar.

Note: Take care for the first bootstrap node.
Maybe if not pillar data we should use `__salt__['network.get_hostname']`

**Comment by TeddyAndrieux** [comment]
Ok after some reflection ext_pillar is not needed and not a good idea here.

We should directly use the minion_id as is because we use salt-ssh when we deploy and at this time minion id is the kubernetes node name.

So I just suggest to use `grains['id']` and put it in the minion config as minion_id

**Comment by NicolasT** [comment]
Sounds good to me.
