### ISSUE TITLE
Use a state instead of an orchestrator for worker plane

### ISSUE THREAD

**Issue by ramanduh** [scality/metalk8s#903]
```
metalk8s:
  'G@role:woker-plane': 
    - ....
```

Since everything here is on the target node and a 'state', over time this `playbook` should basically only invoke `state.highstate` on the target node, given we have an appropriate 'top' generated by a `master_tops` module.

_Originally posted by @NicolasT in https://github.com/scality/metalk8s/pull/892/files_

**Comment by NicolasT** [comment]
We can't use grains for roles. See #742.

**Comment by NicolasT** [comment]
I changed the title of this ticket.

Being a workload-plane node is a simple 'state' of a node (which can of course `include` other states). It's not related to a 'top file', though of course this state can be 'assigned' to a node in its 'top'.

**Comment by NicolasT** [comment]
I think this should be alpha3 @gdemonet

**Comment by gdemonet** [comment]
Ok I'll move it, although the discussion for what goes into alpha3 is yet to happen (this week hopefully)

**Comment by TeddyAndrieux** [comment]
This top.sls should use the roles from #925 to execute the right thing on the right minion

**Comment by TeddyAndrieux** [comment]
Fixed by #967
