### ISSUE TITLE
kube-proxy is not set with the correct hostname overide when expanding worker plane

### ISSUE THREAD

**Issue by ramanduh** [scality/metalk8s#912]
In kube-proxy configmap, the `hostnameOverride` is always set to bootstrap no matter of the node name. When performing the expansion, this value should be `node1` on node `node1`.

To do so, we can set the value to `hostnameOverride: ""` and override it from the Command:
```      
/usr/local/bin/kube-proxy
 --config=/var/lib/kube-proxy/config.conf
 --hostname-override=$(NODE_NAME)
```
cf kubeadm

**Comment by NicolasT** [comment]
Could you point to what `kubeadm` does exactly?

**Comment by ramanduh** [comment]
@NicolasT , in fact `kubeadm` behaves like I described in the ticket. I did not find an URL to a document explaining it but I find it out by creating a cluster with kubeadm
