### ISSUE TITLE
ISO filename should contain the metalk8s version

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#919]
The builded iso should contain the metalk8s version in the filename

**Comment by NicolasT** [comment]
Why's that? The ISO is deliberately self-describing (hence `product.txt`).

**Comment by TeddyAndrieux** [comment]
Yes I know but for me could be cool if we also have it in the filename to know when we have several iso the version of the iso before extracting it.

**Comment by NicolasT** [comment]
```
$ isoinfo -x /PRODUCT.TXT\;1 -i _build/metalk8s.iso 
NAME=MetalK8s
VERSION=2.0.0-dev
SHORT_VERSION=2.0
GIT=2.0.0-alpha1-225-gd36fd94a-dirty
DEVELOPMENT_RELEASE=1
BUILD_TIMESTAMP=2019-04-02T00:45:12Z
BUILD_HOST=beta.nicolast.be
```

**Comment by TeddyAndrieux** [comment]
Oh !! Ok lets close this one

**Comment by TeddyAndrieux** [comment]
Oh ok lets close this one
