### ISSUE TITLE
Mount all iso listed in BootstrapConfig

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#924]
BootstrapConfig should include a list of iso that a salt modules/states automatically mount all of them in the right place.

**When ?**
It's basically the first action the user should do, call the right salt state that "prepare" the iso

**Where ?**
Proposition:
Should be at `/srv/scality/metalk8s-<version>` but we need to be able to know the version of the iso before extracting.
We could use something like this:
```
isoinfo -x /PRODUCT.TXT\;1 -i _build/metalk8s.iso
NAME=MetalK8s
VERSION=2.2.0-dev
SHORT_VERSION=2.2
GIT=2.0.0-alpha1-377-gc692ee47
DEVELOPMENT_RELEASE=1
BUILD_TIMESTAMP=2019-04-03T08:22:16Z
BUILD_HOST=teddy-Latitude-E7450
```

The salt states should:
- mount all the iso listed in the BootstrapConfig file
- (re)configure salt master
- "deploy" all registry image in the local regisitry
- (re)configure nginx to serve the new packagges

**Comment by gdemonet** [comment]
So would we consider the new workflows to look like:

1. Initial install
    + First mount your `metalk8s-X` ISO wherever
    + Specify where your `metalk8s-X` ISO is located in `BootstrapConfiguration`
    + Running the `bootstrap.sh` script first runs this state to (re-)mount said ISO before anything

2. Upgrade
    + Add the new `metalk8s-Y` ISO location in `BootstrapConfiguration`
    + Run some `salt bootstrap metalk8s.iso.all_mounted saltenv=metalk8s-X` to mount `metalk8s-Y` as well
    + Then run the upgrade scenario from `metalk8s-Y` saltenv

I'm not sure what you meant by "the salt states should...", but I don't think we want the ISO-related states to populate the Docker registry/Yum repositories ; it should remain in the `metalk8s.registry` and `metalk8s.repo` states.

**Comment by TeddyAndrieux** [comment]
For 1. I agree
 
2. For me should be more an "include state" like `metalk8s.prepare` that btw do the `iso.all_mounted` and also include the registriy and repo configuration salt states.

> I'm not sure what you meant by "the salt states should...", but I don't think we want the ISO-related states to populate the Docker registry/Yum repositories ; it should remain in the `metalk8s.registry` and `metalk8s.repo` states.

It's not really the iso-related state yes it's more a "preparation state"

**Comment by NicolasT** [comment]
Eventually, ensuring all ISOs are mounted and the Salt `file_roots` etc. are properly configured according to the bootstrap config, should be part of the 'bootstrap node role' (triggered by corresponding highstate), of course.

**Comment by TeddyAndrieux** [comment]
I think this ticket should also include the right salt master manifest changes to mount all the `salt` and `pillar` directory of each versions

**Comment by NicolasT** [comment]
Some WiP stuff in https://github.com/scality/metalk8s/commit/c2aa4c538a0f2b8f3912887873e05899375a85a2 could serve as a base.
