### ISSUE TITLE
Create/use several roles for deployment

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#925]
We should have several roles gathered from K8S though an external pillar, used to execute the right states on the right minions in a top.sls.

We should have 2 separate external pillar:
- one loading the BootstrapConfiguration
- one getting all k8s related informations

List of roles (maybe need to be completed/updated):
- nodes: kubelet + CNI
- etcd: kubelet + etcd
- master: kubelet + apiserver + controller-manager + scheduler
- infra: kubelet + CNI + special taints

Roles could be store in k8s as label `node-role.kubernetes.io/<roles>`

And somes roles set staticly by the BootstrapConfiguration for all CA.

Looks at #742 for more detail about final expected result

**Comment by NicolasT** [comment]
`infra` is `kubelet + CNI`, like `node`, but with a taint set such that only workloads we specifically allow to run on these nodes will be scheduled here. Thinking of CoreDNS, Prometheus,... any non-application workload. It's definitely not `k-a`, `k-c-m`, `k-s`.

**Comment by TeddyAndrieux** [comment]
Oh ok! Updated

**Comment by NicolasT** [comment]
Heavily relates to #742 and the according document.

**Comment by TeddyAndrieux** [comment]
Yes kind of. I would say it's only a part of #742.
For me we can separate:
- ext_pillar + set of roles in apiserver this ticket
- refactor orchestrate to top.sls #903

**Comment by NicolasT** [comment]
@TeddyAndrieux Can we consider this to be 'done'?

**Comment by gdemonet** [comment]
Aren't we still missing the `infra` role? In `pillar/top.sls.in`:

```
{%- set roles = ['bootstrap', 'ca', 'etcd', 'master', 'node'] -%}
```

**Comment by NicolasT** [comment]
`infra` is not a real 'role', as in, it only comes with some taints. There's no particular pillar data for it.
