### ISSUE TITLE
Get the different unique ip using an external pillar

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#927]
Currently we use control_plane ip from the mine with the "bootstrap" minion id to get the endpoint for repository, master, ... (maybe some others)

But we should not get those from the mine as they should all be unique and any minion can push to the mine. 
We should use an external pillar that read this IP from apiserver (and default to localhost when we have no apiserver)

**Comment by NicolasT** [comment]
In a way, duplicate of https://github.com/scality/metalk8s/issues/896

**Comment by TeddyAndrieux** [comment]
Oh yes indeed will move your ticket to alpha3 because I think we should do it now and close this one

**Comment by TeddyAndrieux** [comment]
Duplicates with #896
