### ISSUE TITLE
Use IPVS for proxy

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#95]
Kubernetes 1.11 graduates the IPVS backend for `kube-proxy` to stable. Let's switch to it before MetalK8s 1.0.

**Comment by NicolasT** [comment]
This may be blocked by https://github.com/kubernetes/kubernetes/issues/57841 (if we care enough).

**Comment by NicolasT** [comment]
Whilst this may be useful to have, it may be a bit too soon, e.g. due to https://docs.projectcalico.org/v3.1/usage/enabling-ipvs

**Comment by m1093782566** [comment]
Calico document should be updated.

~kube-proxy has a known issue affecting hosts with host interfaces that that are not named using the pattern ethN.~

**Comment by NicolasT** [comment]
Thanks @m1093782566, that's some good information/feedback!
