### ISSUE TITLE
Collect containers log files as artifacts if the CI fails

### ISSUE THREAD

**Issue by sayf-eddine-scality** [scality/metalk8s#950]
Having to guess what was the error if we get `error exceing inside container` or `connection refused` needs either some black magic or more logs
So unless someone had attended some courses at Hogwarts I suggest collecting all log files of the containers (mainly the bootstrap node) to help dig out the main cause, we can add an eve step that send the archive to the artifact server

PS: open for discussion

**Comment by xaf-scality** [comment]
Could be nice to have it also during the bootstrap install when it failed.

**Comment by NicolasT** [comment]
> Could be nice to have it also during the bootstrap install when it failed.

That's now in `/var/log/metalk8s-bootstrap.log`.

**Comment by sayf-eddine-scality** [comment]
pushing this to medium, as we re going to use sos reports and implementing salt states to install it and custom sos plugins tailored for metalk8s

**Comment by jbertran** [comment]
Reopening for addition to CI.
