### ISSUE TITLE
Ensure versions of Docker and `node_exporter` are pinned

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#962]
Currently, when running MetalK8s 1.x, a `yum upgrade` may decide to upgrade the version of Docker and `node_exporter` running on a node. We should `yum versionlock` them.

**Comment by NicolasT** [comment]
This is done, right @alexandre-allard-scality ?

**Comment by thomasdanan** [comment]
@alexandre-allard-scality is this issue done? if yes can you close it? Thanks ...
