### ISSUE TITLE
Check vagrant snaphot list before creation

### ISSUE THREAD

**Issue by cmonfort** [scality/metalk8s#971]
We could check if the snapshot exist in vagrant (by checking the output of `vagrant snapshot list`) before creating it, instead of blindly using doit `run_once` mechanism.

_Originally posted by @slaperche-scality in https://github.com/scality/metalk8s/pull/968_

**Comment by slaperche-scality** [comment]
Fixed by https://github.com/scality/metalk8s/issues/1345 (commit d721854b1)
