### ISSUE TITLE
Add automated test for upgradeand rollback/downgrade

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#983]
Add some test for upgrade and rollback of metalk8s using the upgrade runner #981.

Those test need a real cluster first (more than a single bootstrap node) #982.

This test should be able to run in the CI using a "marked" artifacts to know "from where" you want to upgrade and then rollback

**Comment by jbertran** [comment]
Closed due to presence of more precise tickets:

* #1125 
* #1126 
* #1127 
* #1128
