### ISSUE TITLE
Port docs/Makefile to doit

### ISSUE THREAD

**Issue by slaperche-scality** [scality/metalk8s#999]
We still have a Makefile, in the `doc` directory.

This should be implemented in `doit`.

**Comment by NicolasT** [comment]
For the `docs` tree, we'll use Sphinx, whose quickstart script generates a suitable `Makefile` (and `make.bat`), so no need for this.

Furthermore, we put that `Makefile` invocation behind a `tox` target which manages a virtualenv in which the right Sphinx version, and all dependencies, plugins,... are installed.
